// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dataflow_in_loop_Bat_1 (
        ap_clk,
        ap_rst,
        in_stream_TDATA,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TUSER,
        in_stream_TLAST,
        in_stream_TID,
        in_stream_TDEST,
        n_0_i_i,
        out_stream_TDATA,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST,
        n_0_i_i_ap_vld,
        in_stream_TVALID,
        in_stream_TREADY,
        ap_start,
        out_stream_TVALID,
        out_stream_TREADY,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input   ap_clk;
input   ap_rst;
input  [63:0] in_stream_TDATA;
input  [7:0] in_stream_TKEEP;
input  [7:0] in_stream_TSTRB;
input  [0:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
input  [0:0] in_stream_TID;
input  [0:0] in_stream_TDEST;
input  [11:0] n_0_i_i;
output  [31:0] out_stream_TDATA;
output  [0:0] out_stream_TKEEP;
output  [0:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;
input   n_0_i_i_ap_vld;
input   in_stream_TVALID;
output   in_stream_TREADY;
input   ap_start;
output   out_stream_TVALID;
input   out_stream_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire   [7:0] x_local_0_V_i_q0;
wire   [7:0] x_local_0_V_t_q0;
wire   [7:0] x_local_1_V_i_q0;
wire   [7:0] x_local_1_V_t_q0;
wire   [7:0] x_local_2_V_i_q0;
wire   [7:0] x_local_2_V_t_q0;
wire   [7:0] x_local_3_V_i_q0;
wire   [7:0] x_local_3_V_t_q0;
wire   [7:0] x_local_4_V_i_q0;
wire   [7:0] x_local_4_V_t_q0;
wire   [7:0] x_local_5_V_i_q0;
wire   [7:0] x_local_5_V_t_q0;
wire   [7:0] x_local_6_V_i_q0;
wire   [7:0] x_local_6_V_t_q0;
wire   [7:0] x_local_7_V_i_q0;
wire   [7:0] x_local_7_V_t_q0;
wire   [7:0] x_local_8_V_i_q0;
wire   [7:0] x_local_8_V_t_q0;
wire   [7:0] x_local_9_V_i_q0;
wire   [7:0] x_local_9_V_t_q0;
wire   [7:0] x_local_10_V_i_q0;
wire   [7:0] x_local_10_V_t_q0;
wire   [7:0] x_local_11_V_i_q0;
wire   [7:0] x_local_11_V_t_q0;
wire   [7:0] x_local_12_V_i_q0;
wire   [7:0] x_local_12_V_t_q0;
wire   [7:0] x_local_13_V_i_q0;
wire   [7:0] x_local_13_V_t_q0;
wire   [7:0] x_local_14_V_i_q0;
wire   [7:0] x_local_14_V_t_q0;
wire   [7:0] x_local_15_V_i_q0;
wire   [7:0] x_local_15_V_t_q0;
wire    dataflow_in_loop_Bat_2_U0_ap_start;
wire    dataflow_in_loop_Bat_2_U0_ap_done;
wire    dataflow_in_loop_Bat_2_U0_ap_continue;
wire    dataflow_in_loop_Bat_2_U0_ap_idle;
wire    dataflow_in_loop_Bat_2_U0_ap_ready;
wire    dataflow_in_loop_Bat_2_U0_start_out;
wire    dataflow_in_loop_Bat_2_U0_start_write;
wire   [11:0] dataflow_in_loop_Bat_2_U0_n_0_i_i_out_din;
wire    dataflow_in_loop_Bat_2_U0_n_0_i_i_out_write;
wire    dataflow_in_loop_Bat_1_1_U0_ap_start;
wire    dataflow_in_loop_Bat_1_1_U0_ap_done;
wire    dataflow_in_loop_Bat_1_1_U0_ap_continue;
wire    dataflow_in_loop_Bat_1_1_U0_ap_idle;
wire    dataflow_in_loop_Bat_1_1_U0_ap_ready;
wire    dataflow_in_loop_Bat_1_1_U0_start_out;
wire    dataflow_in_loop_Bat_1_1_U0_start_write;
wire    dataflow_in_loop_Bat_1_1_U0_n_0_i_i_read;
wire   [11:0] dataflow_in_loop_Bat_1_1_U0_n_0_i_i_out_din;
wire    dataflow_in_loop_Bat_1_1_U0_n_0_i_i_out_write;
wire    load_and_calc_norm_U0_ap_start;
wire    load_and_calc_norm_U0_ap_done;
wire    load_and_calc_norm_U0_ap_continue;
wire    load_and_calc_norm_U0_ap_idle;
wire    load_and_calc_norm_U0_ap_ready;
wire    load_and_calc_norm_U0_in_stream_TREADY;
wire   [5:0] load_and_calc_norm_U0_x_local_0_V_address0;
wire    load_and_calc_norm_U0_x_local_0_V_ce0;
wire    load_and_calc_norm_U0_x_local_0_V_we0;
wire   [7:0] load_and_calc_norm_U0_x_local_0_V_d0;
wire   [5:0] load_and_calc_norm_U0_x_local_1_V_address0;
wire    load_and_calc_norm_U0_x_local_1_V_ce0;
wire    load_and_calc_norm_U0_x_local_1_V_we0;
wire   [7:0] load_and_calc_norm_U0_x_local_1_V_d0;
wire   [5:0] load_and_calc_norm_U0_x_local_2_V_address0;
wire    load_and_calc_norm_U0_x_local_2_V_ce0;
wire    load_and_calc_norm_U0_x_local_2_V_we0;
wire   [7:0] load_and_calc_norm_U0_x_local_2_V_d0;
wire   [5:0] load_and_calc_norm_U0_x_local_3_V_address0;
wire    load_and_calc_norm_U0_x_local_3_V_ce0;
wire    load_and_calc_norm_U0_x_local_3_V_we0;
wire   [7:0] load_and_calc_norm_U0_x_local_3_V_d0;
wire   [5:0] load_and_calc_norm_U0_x_local_4_V_address0;
wire    load_and_calc_norm_U0_x_local_4_V_ce0;
wire    load_and_calc_norm_U0_x_local_4_V_we0;
wire   [7:0] load_and_calc_norm_U0_x_local_4_V_d0;
wire   [5:0] load_and_calc_norm_U0_x_local_5_V_address0;
wire    load_and_calc_norm_U0_x_local_5_V_ce0;
wire    load_and_calc_norm_U0_x_local_5_V_we0;
wire   [7:0] load_and_calc_norm_U0_x_local_5_V_d0;
wire   [5:0] load_and_calc_norm_U0_x_local_6_V_address0;
wire    load_and_calc_norm_U0_x_local_6_V_ce0;
wire    load_and_calc_norm_U0_x_local_6_V_we0;
wire   [7:0] load_and_calc_norm_U0_x_local_6_V_d0;
wire   [5:0] load_and_calc_norm_U0_x_local_7_V_address0;
wire    load_and_calc_norm_U0_x_local_7_V_ce0;
wire    load_and_calc_norm_U0_x_local_7_V_we0;
wire   [7:0] load_and_calc_norm_U0_x_local_7_V_d0;
wire   [5:0] load_and_calc_norm_U0_x_local_8_V_address0;
wire    load_and_calc_norm_U0_x_local_8_V_ce0;
wire    load_and_calc_norm_U0_x_local_8_V_we0;
wire   [7:0] load_and_calc_norm_U0_x_local_8_V_d0;
wire   [5:0] load_and_calc_norm_U0_x_local_9_V_address0;
wire    load_and_calc_norm_U0_x_local_9_V_ce0;
wire    load_and_calc_norm_U0_x_local_9_V_we0;
wire   [7:0] load_and_calc_norm_U0_x_local_9_V_d0;
wire   [5:0] load_and_calc_norm_U0_x_local_10_V_address0;
wire    load_and_calc_norm_U0_x_local_10_V_ce0;
wire    load_and_calc_norm_U0_x_local_10_V_we0;
wire   [7:0] load_and_calc_norm_U0_x_local_10_V_d0;
wire   [5:0] load_and_calc_norm_U0_x_local_11_V_address0;
wire    load_and_calc_norm_U0_x_local_11_V_ce0;
wire    load_and_calc_norm_U0_x_local_11_V_we0;
wire   [7:0] load_and_calc_norm_U0_x_local_11_V_d0;
wire   [5:0] load_and_calc_norm_U0_x_local_12_V_address0;
wire    load_and_calc_norm_U0_x_local_12_V_ce0;
wire    load_and_calc_norm_U0_x_local_12_V_we0;
wire   [7:0] load_and_calc_norm_U0_x_local_12_V_d0;
wire   [5:0] load_and_calc_norm_U0_x_local_13_V_address0;
wire    load_and_calc_norm_U0_x_local_13_V_ce0;
wire    load_and_calc_norm_U0_x_local_13_V_we0;
wire   [7:0] load_and_calc_norm_U0_x_local_13_V_d0;
wire   [5:0] load_and_calc_norm_U0_x_local_14_V_address0;
wire    load_and_calc_norm_U0_x_local_14_V_ce0;
wire    load_and_calc_norm_U0_x_local_14_V_we0;
wire   [7:0] load_and_calc_norm_U0_x_local_14_V_d0;
wire   [5:0] load_and_calc_norm_U0_x_local_15_V_address0;
wire    load_and_calc_norm_U0_x_local_15_V_ce0;
wire    load_and_calc_norm_U0_x_local_15_V_we0;
wire   [7:0] load_and_calc_norm_U0_x_local_15_V_d0;
wire   [23:0] load_and_calc_norm_U0_ap_return;
wire    ap_channel_done_op_V_assign1_channel;
wire    op_V_assign1_channel_full_n;
reg    ap_sync_reg_channel_write_op_V_assign1_channel;
wire    ap_sync_channel_write_op_V_assign1_channel;
wire    ap_channel_done_x_local_15_V;
wire    load_and_calc_norm_U0_x_local_15_V_full_n;
reg    ap_sync_reg_channel_write_x_local_15_V;
wire    ap_sync_channel_write_x_local_15_V;
wire    ap_channel_done_x_local_14_V;
wire    load_and_calc_norm_U0_x_local_14_V_full_n;
reg    ap_sync_reg_channel_write_x_local_14_V;
wire    ap_sync_channel_write_x_local_14_V;
wire    ap_channel_done_x_local_13_V;
wire    load_and_calc_norm_U0_x_local_13_V_full_n;
reg    ap_sync_reg_channel_write_x_local_13_V;
wire    ap_sync_channel_write_x_local_13_V;
wire    ap_channel_done_x_local_12_V;
wire    load_and_calc_norm_U0_x_local_12_V_full_n;
reg    ap_sync_reg_channel_write_x_local_12_V;
wire    ap_sync_channel_write_x_local_12_V;
wire    ap_channel_done_x_local_11_V;
wire    load_and_calc_norm_U0_x_local_11_V_full_n;
reg    ap_sync_reg_channel_write_x_local_11_V;
wire    ap_sync_channel_write_x_local_11_V;
wire    ap_channel_done_x_local_10_V;
wire    load_and_calc_norm_U0_x_local_10_V_full_n;
reg    ap_sync_reg_channel_write_x_local_10_V;
wire    ap_sync_channel_write_x_local_10_V;
wire    ap_channel_done_x_local_9_V;
wire    load_and_calc_norm_U0_x_local_9_V_full_n;
reg    ap_sync_reg_channel_write_x_local_9_V;
wire    ap_sync_channel_write_x_local_9_V;
wire    ap_channel_done_x_local_8_V;
wire    load_and_calc_norm_U0_x_local_8_V_full_n;
reg    ap_sync_reg_channel_write_x_local_8_V;
wire    ap_sync_channel_write_x_local_8_V;
wire    ap_channel_done_x_local_7_V;
wire    load_and_calc_norm_U0_x_local_7_V_full_n;
reg    ap_sync_reg_channel_write_x_local_7_V;
wire    ap_sync_channel_write_x_local_7_V;
wire    ap_channel_done_x_local_6_V;
wire    load_and_calc_norm_U0_x_local_6_V_full_n;
reg    ap_sync_reg_channel_write_x_local_6_V;
wire    ap_sync_channel_write_x_local_6_V;
wire    ap_channel_done_x_local_5_V;
wire    load_and_calc_norm_U0_x_local_5_V_full_n;
reg    ap_sync_reg_channel_write_x_local_5_V;
wire    ap_sync_channel_write_x_local_5_V;
wire    ap_channel_done_x_local_4_V;
wire    load_and_calc_norm_U0_x_local_4_V_full_n;
reg    ap_sync_reg_channel_write_x_local_4_V;
wire    ap_sync_channel_write_x_local_4_V;
wire    ap_channel_done_x_local_3_V;
wire    load_and_calc_norm_U0_x_local_3_V_full_n;
reg    ap_sync_reg_channel_write_x_local_3_V;
wire    ap_sync_channel_write_x_local_3_V;
wire    ap_channel_done_x_local_2_V;
wire    load_and_calc_norm_U0_x_local_2_V_full_n;
reg    ap_sync_reg_channel_write_x_local_2_V;
wire    ap_sync_channel_write_x_local_2_V;
wire    ap_channel_done_x_local_1_V;
wire    load_and_calc_norm_U0_x_local_1_V_full_n;
reg    ap_sync_reg_channel_write_x_local_1_V;
wire    ap_sync_channel_write_x_local_1_V;
wire    ap_channel_done_x_local_0_V;
wire    load_and_calc_norm_U0_x_local_0_V_full_n;
reg    ap_sync_reg_channel_write_x_local_0_V;
wire    ap_sync_channel_write_x_local_0_V;
wire    compute_class_U0_ap_start;
wire    compute_class_U0_ap_done;
wire    compute_class_U0_ap_continue;
wire    compute_class_U0_ap_idle;
wire    compute_class_U0_ap_ready;
wire   [5:0] compute_class_U0_x_local_0_V_address0;
wire    compute_class_U0_x_local_0_V_ce0;
wire   [5:0] compute_class_U0_x_local_1_V_address0;
wire    compute_class_U0_x_local_1_V_ce0;
wire   [5:0] compute_class_U0_x_local_2_V_address0;
wire    compute_class_U0_x_local_2_V_ce0;
wire   [5:0] compute_class_U0_x_local_3_V_address0;
wire    compute_class_U0_x_local_3_V_ce0;
wire   [5:0] compute_class_U0_x_local_4_V_address0;
wire    compute_class_U0_x_local_4_V_ce0;
wire   [5:0] compute_class_U0_x_local_5_V_address0;
wire    compute_class_U0_x_local_5_V_ce0;
wire   [5:0] compute_class_U0_x_local_6_V_address0;
wire    compute_class_U0_x_local_6_V_ce0;
wire   [5:0] compute_class_U0_x_local_7_V_address0;
wire    compute_class_U0_x_local_7_V_ce0;
wire   [5:0] compute_class_U0_x_local_8_V_address0;
wire    compute_class_U0_x_local_8_V_ce0;
wire   [5:0] compute_class_U0_x_local_9_V_address0;
wire    compute_class_U0_x_local_9_V_ce0;
wire   [5:0] compute_class_U0_x_local_10_V_address0;
wire    compute_class_U0_x_local_10_V_ce0;
wire   [5:0] compute_class_U0_x_local_11_V_address0;
wire    compute_class_U0_x_local_11_V_ce0;
wire   [5:0] compute_class_U0_x_local_12_V_address0;
wire    compute_class_U0_x_local_12_V_ce0;
wire   [5:0] compute_class_U0_x_local_13_V_address0;
wire    compute_class_U0_x_local_13_V_ce0;
wire   [5:0] compute_class_U0_x_local_14_V_address0;
wire    compute_class_U0_x_local_14_V_ce0;
wire   [5:0] compute_class_U0_x_local_15_V_address0;
wire    compute_class_U0_x_local_15_V_ce0;
wire   [31:0] compute_class_U0_ap_return;
wire    ap_channel_done_res_internal_V;
wire    res_internal_V_full_n;
wire    p_ADSD_Classifier_cp_4_U0_ap_start;
wire    p_ADSD_Classifier_cp_4_U0_ap_done;
wire    p_ADSD_Classifier_cp_4_U0_ap_continue;
wire    p_ADSD_Classifier_cp_4_U0_ap_idle;
wire    p_ADSD_Classifier_cp_4_U0_ap_ready;
wire   [31:0] p_ADSD_Classifier_cp_4_U0_tmp_data_V19;
wire    p_ADSD_Classifier_cp_4_U0_tmp_data_V19_ap_vld;
wire    ap_channel_done_tmp_data_V;
wire    tmp_data_V_full_n;
wire    p_ADSD_Classifier_cp_3_U0_ap_start;
wire    p_ADSD_Classifier_cp_3_U0_ap_done;
wire    p_ADSD_Classifier_cp_3_U0_ap_continue;
wire    p_ADSD_Classifier_cp_3_U0_ap_idle;
wire    p_ADSD_Classifier_cp_3_U0_ap_ready;
wire   [0:0] p_ADSD_Classifier_cp_3_U0_tmp_keep_V20;
wire    p_ADSD_Classifier_cp_3_U0_tmp_keep_V20_ap_vld;
wire    ap_channel_done_tmp_keep_V;
wire    tmp_keep_V_full_n;
wire    p_ADSD_Classifier_cp_2_U0_ap_start;
wire    p_ADSD_Classifier_cp_2_U0_ap_done;
wire    p_ADSD_Classifier_cp_2_U0_ap_continue;
wire    p_ADSD_Classifier_cp_2_U0_ap_idle;
wire    p_ADSD_Classifier_cp_2_U0_ap_ready;
wire   [0:0] p_ADSD_Classifier_cp_2_U0_tmp_strb_V21;
wire    p_ADSD_Classifier_cp_2_U0_tmp_strb_V21_ap_vld;
wire    ap_channel_done_tmp_strb_V;
wire    tmp_strb_V_full_n;
wire    p_ADSD_Classifier_cp_1_U0_ap_start;
wire    p_ADSD_Classifier_cp_1_U0_ap_done;
wire    p_ADSD_Classifier_cp_1_U0_ap_continue;
wire    p_ADSD_Classifier_cp_1_U0_ap_idle;
wire    p_ADSD_Classifier_cp_1_U0_ap_ready;
wire    p_ADSD_Classifier_cp_1_U0_n_0_i_i_read;
wire   [0:0] p_ADSD_Classifier_cp_1_U0_tmp_last_V22;
wire    p_ADSD_Classifier_cp_1_U0_tmp_last_V22_ap_vld;
wire    ap_channel_done_tmp_last_V;
wire    tmp_last_V_full_n;
wire    p_ADSD_Classifier_cp_U0_ap_start;
wire    p_ADSD_Classifier_cp_U0_ap_done;
wire    p_ADSD_Classifier_cp_U0_ap_continue;
wire    p_ADSD_Classifier_cp_U0_ap_idle;
wire    p_ADSD_Classifier_cp_U0_ap_ready;
wire   [31:0] p_ADSD_Classifier_cp_U0_out_stream_TDATA;
wire    p_ADSD_Classifier_cp_U0_out_stream_TVALID;
wire   [0:0] p_ADSD_Classifier_cp_U0_out_stream_TKEEP;
wire   [0:0] p_ADSD_Classifier_cp_U0_out_stream_TSTRB;
wire   [0:0] p_ADSD_Classifier_cp_U0_out_stream_TLAST;
wire    ap_sync_continue;
wire    x_local_0_V_i_full_n;
wire    x_local_0_V_t_empty_n;
wire    x_local_1_V_i_full_n;
wire    x_local_1_V_t_empty_n;
wire    x_local_2_V_i_full_n;
wire    x_local_2_V_t_empty_n;
wire    x_local_3_V_i_full_n;
wire    x_local_3_V_t_empty_n;
wire    x_local_4_V_i_full_n;
wire    x_local_4_V_t_empty_n;
wire    x_local_5_V_i_full_n;
wire    x_local_5_V_t_empty_n;
wire    x_local_6_V_i_full_n;
wire    x_local_6_V_t_empty_n;
wire    x_local_7_V_i_full_n;
wire    x_local_7_V_t_empty_n;
wire    x_local_8_V_i_full_n;
wire    x_local_8_V_t_empty_n;
wire    x_local_9_V_i_full_n;
wire    x_local_9_V_t_empty_n;
wire    x_local_10_V_i_full_n;
wire    x_local_10_V_t_empty_n;
wire    x_local_11_V_i_full_n;
wire    x_local_11_V_t_empty_n;
wire    x_local_12_V_i_full_n;
wire    x_local_12_V_t_empty_n;
wire    x_local_13_V_i_full_n;
wire    x_local_13_V_t_empty_n;
wire    x_local_14_V_i_full_n;
wire    x_local_14_V_t_empty_n;
wire    x_local_15_V_i_full_n;
wire    x_local_15_V_t_empty_n;
wire    n_0_i_i_c1_full_n;
wire   [11:0] n_0_i_i_c1_dout;
wire    n_0_i_i_c1_empty_n;
wire    n_0_i_i_c_full_n;
wire   [11:0] n_0_i_i_c_dout;
wire    n_0_i_i_c_empty_n;
wire   [23:0] op_V_assign1_channel_dout;
wire    op_V_assign1_channel_empty_n;
wire   [31:0] res_internal_V_dout;
wire    res_internal_V_empty_n;
wire   [31:0] tmp_data_V_dout;
wire    tmp_data_V_empty_n;
wire   [0:0] tmp_keep_V_dout;
wire    tmp_keep_V_empty_n;
wire   [0:0] tmp_strb_V_dout;
wire    tmp_strb_V_empty_n;
wire   [0:0] tmp_last_V_dout;
wire    tmp_last_V_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_load_and_calc_norm_U0_ap_ready;
wire    ap_sync_load_and_calc_norm_U0_ap_ready;
reg   [1:0] load_and_calc_norm_U0_ap_ready_count;
reg    ap_sync_reg_dataflow_in_loop_Bat_2_U0_ap_ready;
wire    ap_sync_dataflow_in_loop_Bat_2_U0_ap_ready;
reg   [1:0] dataflow_in_loop_Bat_2_U0_ap_ready_count;
wire   [0:0] start_for_dataflow_in_loop_Bat_1_1_U0_din;
wire    start_for_dataflow_in_loop_Bat_1_1_U0_full_n;
wire   [0:0] start_for_dataflow_in_loop_Bat_1_1_U0_dout;
wire    start_for_dataflow_in_loop_Bat_1_1_U0_empty_n;
wire   [0:0] start_for_p_ADSD_Classifier_cp_1_U0_din;
wire    start_for_p_ADSD_Classifier_cp_1_U0_full_n;
wire   [0:0] start_for_p_ADSD_Classifier_cp_1_U0_dout;
wire    start_for_p_ADSD_Classifier_cp_1_U0_empty_n;
wire    load_and_calc_norm_U0_start_full_n;
wire    load_and_calc_norm_U0_start_write;
wire    compute_class_U0_start_full_n;
wire    compute_class_U0_start_write;
wire    p_ADSD_Classifier_cp_4_U0_start_full_n;
wire    p_ADSD_Classifier_cp_4_U0_start_write;
wire    p_ADSD_Classifier_cp_3_U0_start_full_n;
wire    p_ADSD_Classifier_cp_3_U0_start_write;
wire    p_ADSD_Classifier_cp_2_U0_start_full_n;
wire    p_ADSD_Classifier_cp_2_U0_start_write;
wire    p_ADSD_Classifier_cp_1_U0_start_full_n;
wire    p_ADSD_Classifier_cp_1_U0_start_write;
wire    p_ADSD_Classifier_cp_U0_start_full_n;
wire    p_ADSD_Classifier_cp_U0_start_write;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_op_V_assign1_channel = 1'b0;
#0 ap_sync_reg_channel_write_x_local_15_V = 1'b0;
#0 ap_sync_reg_channel_write_x_local_14_V = 1'b0;
#0 ap_sync_reg_channel_write_x_local_13_V = 1'b0;
#0 ap_sync_reg_channel_write_x_local_12_V = 1'b0;
#0 ap_sync_reg_channel_write_x_local_11_V = 1'b0;
#0 ap_sync_reg_channel_write_x_local_10_V = 1'b0;
#0 ap_sync_reg_channel_write_x_local_9_V = 1'b0;
#0 ap_sync_reg_channel_write_x_local_8_V = 1'b0;
#0 ap_sync_reg_channel_write_x_local_7_V = 1'b0;
#0 ap_sync_reg_channel_write_x_local_6_V = 1'b0;
#0 ap_sync_reg_channel_write_x_local_5_V = 1'b0;
#0 ap_sync_reg_channel_write_x_local_4_V = 1'b0;
#0 ap_sync_reg_channel_write_x_local_3_V = 1'b0;
#0 ap_sync_reg_channel_write_x_local_2_V = 1'b0;
#0 ap_sync_reg_channel_write_x_local_1_V = 1'b0;
#0 ap_sync_reg_channel_write_x_local_0_V = 1'b0;
#0 ap_sync_reg_load_and_calc_norm_U0_ap_ready = 1'b0;
#0 load_and_calc_norm_U0_ap_ready_count = 2'd0;
#0 ap_sync_reg_dataflow_in_loop_Bat_2_U0_ap_ready = 1'b0;
#0 dataflow_in_loop_Bat_2_U0_ap_ready_count = 2'd0;
end

dataflow_in_loop_0iy #(
    .DataWidth( 8 ),
    .AddressRange( 49 ),
    .AddressWidth( 6 ))
x_local_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(load_and_calc_norm_U0_x_local_0_V_address0),
    .i_ce0(load_and_calc_norm_U0_x_local_0_V_ce0),
    .i_we0(load_and_calc_norm_U0_x_local_0_V_we0),
    .i_d0(load_and_calc_norm_U0_x_local_0_V_d0),
    .i_q0(x_local_0_V_i_q0),
    .t_address0(compute_class_U0_x_local_0_V_address0),
    .t_ce0(compute_class_U0_x_local_0_V_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(x_local_0_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(x_local_0_V_i_full_n),
    .i_write(ap_channel_done_x_local_0_V),
    .t_empty_n(x_local_0_V_t_empty_n),
    .t_read(compute_class_U0_ap_ready)
);

dataflow_in_loop_0iy #(
    .DataWidth( 8 ),
    .AddressRange( 49 ),
    .AddressWidth( 6 ))
x_local_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(load_and_calc_norm_U0_x_local_1_V_address0),
    .i_ce0(load_and_calc_norm_U0_x_local_1_V_ce0),
    .i_we0(load_and_calc_norm_U0_x_local_1_V_we0),
    .i_d0(load_and_calc_norm_U0_x_local_1_V_d0),
    .i_q0(x_local_1_V_i_q0),
    .t_address0(compute_class_U0_x_local_1_V_address0),
    .t_ce0(compute_class_U0_x_local_1_V_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(x_local_1_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(x_local_1_V_i_full_n),
    .i_write(ap_channel_done_x_local_1_V),
    .t_empty_n(x_local_1_V_t_empty_n),
    .t_read(compute_class_U0_ap_ready)
);

dataflow_in_loop_0iy #(
    .DataWidth( 8 ),
    .AddressRange( 49 ),
    .AddressWidth( 6 ))
x_local_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(load_and_calc_norm_U0_x_local_2_V_address0),
    .i_ce0(load_and_calc_norm_U0_x_local_2_V_ce0),
    .i_we0(load_and_calc_norm_U0_x_local_2_V_we0),
    .i_d0(load_and_calc_norm_U0_x_local_2_V_d0),
    .i_q0(x_local_2_V_i_q0),
    .t_address0(compute_class_U0_x_local_2_V_address0),
    .t_ce0(compute_class_U0_x_local_2_V_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(x_local_2_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(x_local_2_V_i_full_n),
    .i_write(ap_channel_done_x_local_2_V),
    .t_empty_n(x_local_2_V_t_empty_n),
    .t_read(compute_class_U0_ap_ready)
);

dataflow_in_loop_0iy #(
    .DataWidth( 8 ),
    .AddressRange( 49 ),
    .AddressWidth( 6 ))
x_local_3_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(load_and_calc_norm_U0_x_local_3_V_address0),
    .i_ce0(load_and_calc_norm_U0_x_local_3_V_ce0),
    .i_we0(load_and_calc_norm_U0_x_local_3_V_we0),
    .i_d0(load_and_calc_norm_U0_x_local_3_V_d0),
    .i_q0(x_local_3_V_i_q0),
    .t_address0(compute_class_U0_x_local_3_V_address0),
    .t_ce0(compute_class_U0_x_local_3_V_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(x_local_3_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(x_local_3_V_i_full_n),
    .i_write(ap_channel_done_x_local_3_V),
    .t_empty_n(x_local_3_V_t_empty_n),
    .t_read(compute_class_U0_ap_ready)
);

dataflow_in_loop_0iy #(
    .DataWidth( 8 ),
    .AddressRange( 49 ),
    .AddressWidth( 6 ))
x_local_4_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(load_and_calc_norm_U0_x_local_4_V_address0),
    .i_ce0(load_and_calc_norm_U0_x_local_4_V_ce0),
    .i_we0(load_and_calc_norm_U0_x_local_4_V_we0),
    .i_d0(load_and_calc_norm_U0_x_local_4_V_d0),
    .i_q0(x_local_4_V_i_q0),
    .t_address0(compute_class_U0_x_local_4_V_address0),
    .t_ce0(compute_class_U0_x_local_4_V_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(x_local_4_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(x_local_4_V_i_full_n),
    .i_write(ap_channel_done_x_local_4_V),
    .t_empty_n(x_local_4_V_t_empty_n),
    .t_read(compute_class_U0_ap_ready)
);

dataflow_in_loop_0iy #(
    .DataWidth( 8 ),
    .AddressRange( 49 ),
    .AddressWidth( 6 ))
x_local_5_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(load_and_calc_norm_U0_x_local_5_V_address0),
    .i_ce0(load_and_calc_norm_U0_x_local_5_V_ce0),
    .i_we0(load_and_calc_norm_U0_x_local_5_V_we0),
    .i_d0(load_and_calc_norm_U0_x_local_5_V_d0),
    .i_q0(x_local_5_V_i_q0),
    .t_address0(compute_class_U0_x_local_5_V_address0),
    .t_ce0(compute_class_U0_x_local_5_V_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(x_local_5_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(x_local_5_V_i_full_n),
    .i_write(ap_channel_done_x_local_5_V),
    .t_empty_n(x_local_5_V_t_empty_n),
    .t_read(compute_class_U0_ap_ready)
);

dataflow_in_loop_0iy #(
    .DataWidth( 8 ),
    .AddressRange( 49 ),
    .AddressWidth( 6 ))
x_local_6_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(load_and_calc_norm_U0_x_local_6_V_address0),
    .i_ce0(load_and_calc_norm_U0_x_local_6_V_ce0),
    .i_we0(load_and_calc_norm_U0_x_local_6_V_we0),
    .i_d0(load_and_calc_norm_U0_x_local_6_V_d0),
    .i_q0(x_local_6_V_i_q0),
    .t_address0(compute_class_U0_x_local_6_V_address0),
    .t_ce0(compute_class_U0_x_local_6_V_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(x_local_6_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(x_local_6_V_i_full_n),
    .i_write(ap_channel_done_x_local_6_V),
    .t_empty_n(x_local_6_V_t_empty_n),
    .t_read(compute_class_U0_ap_ready)
);

dataflow_in_loop_0iy #(
    .DataWidth( 8 ),
    .AddressRange( 49 ),
    .AddressWidth( 6 ))
x_local_7_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(load_and_calc_norm_U0_x_local_7_V_address0),
    .i_ce0(load_and_calc_norm_U0_x_local_7_V_ce0),
    .i_we0(load_and_calc_norm_U0_x_local_7_V_we0),
    .i_d0(load_and_calc_norm_U0_x_local_7_V_d0),
    .i_q0(x_local_7_V_i_q0),
    .t_address0(compute_class_U0_x_local_7_V_address0),
    .t_ce0(compute_class_U0_x_local_7_V_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(x_local_7_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(x_local_7_V_i_full_n),
    .i_write(ap_channel_done_x_local_7_V),
    .t_empty_n(x_local_7_V_t_empty_n),
    .t_read(compute_class_U0_ap_ready)
);

dataflow_in_loop_0iy #(
    .DataWidth( 8 ),
    .AddressRange( 49 ),
    .AddressWidth( 6 ))
x_local_8_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(load_and_calc_norm_U0_x_local_8_V_address0),
    .i_ce0(load_and_calc_norm_U0_x_local_8_V_ce0),
    .i_we0(load_and_calc_norm_U0_x_local_8_V_we0),
    .i_d0(load_and_calc_norm_U0_x_local_8_V_d0),
    .i_q0(x_local_8_V_i_q0),
    .t_address0(compute_class_U0_x_local_8_V_address0),
    .t_ce0(compute_class_U0_x_local_8_V_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(x_local_8_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(x_local_8_V_i_full_n),
    .i_write(ap_channel_done_x_local_8_V),
    .t_empty_n(x_local_8_V_t_empty_n),
    .t_read(compute_class_U0_ap_ready)
);

dataflow_in_loop_0iy #(
    .DataWidth( 8 ),
    .AddressRange( 49 ),
    .AddressWidth( 6 ))
x_local_9_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(load_and_calc_norm_U0_x_local_9_V_address0),
    .i_ce0(load_and_calc_norm_U0_x_local_9_V_ce0),
    .i_we0(load_and_calc_norm_U0_x_local_9_V_we0),
    .i_d0(load_and_calc_norm_U0_x_local_9_V_d0),
    .i_q0(x_local_9_V_i_q0),
    .t_address0(compute_class_U0_x_local_9_V_address0),
    .t_ce0(compute_class_U0_x_local_9_V_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(x_local_9_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(x_local_9_V_i_full_n),
    .i_write(ap_channel_done_x_local_9_V),
    .t_empty_n(x_local_9_V_t_empty_n),
    .t_read(compute_class_U0_ap_ready)
);

dataflow_in_loop_0iy #(
    .DataWidth( 8 ),
    .AddressRange( 49 ),
    .AddressWidth( 6 ))
x_local_10_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(load_and_calc_norm_U0_x_local_10_V_address0),
    .i_ce0(load_and_calc_norm_U0_x_local_10_V_ce0),
    .i_we0(load_and_calc_norm_U0_x_local_10_V_we0),
    .i_d0(load_and_calc_norm_U0_x_local_10_V_d0),
    .i_q0(x_local_10_V_i_q0),
    .t_address0(compute_class_U0_x_local_10_V_address0),
    .t_ce0(compute_class_U0_x_local_10_V_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(x_local_10_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(x_local_10_V_i_full_n),
    .i_write(ap_channel_done_x_local_10_V),
    .t_empty_n(x_local_10_V_t_empty_n),
    .t_read(compute_class_U0_ap_ready)
);

dataflow_in_loop_0iy #(
    .DataWidth( 8 ),
    .AddressRange( 49 ),
    .AddressWidth( 6 ))
x_local_11_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(load_and_calc_norm_U0_x_local_11_V_address0),
    .i_ce0(load_and_calc_norm_U0_x_local_11_V_ce0),
    .i_we0(load_and_calc_norm_U0_x_local_11_V_we0),
    .i_d0(load_and_calc_norm_U0_x_local_11_V_d0),
    .i_q0(x_local_11_V_i_q0),
    .t_address0(compute_class_U0_x_local_11_V_address0),
    .t_ce0(compute_class_U0_x_local_11_V_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(x_local_11_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(x_local_11_V_i_full_n),
    .i_write(ap_channel_done_x_local_11_V),
    .t_empty_n(x_local_11_V_t_empty_n),
    .t_read(compute_class_U0_ap_ready)
);

dataflow_in_loop_0iy #(
    .DataWidth( 8 ),
    .AddressRange( 49 ),
    .AddressWidth( 6 ))
x_local_12_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(load_and_calc_norm_U0_x_local_12_V_address0),
    .i_ce0(load_and_calc_norm_U0_x_local_12_V_ce0),
    .i_we0(load_and_calc_norm_U0_x_local_12_V_we0),
    .i_d0(load_and_calc_norm_U0_x_local_12_V_d0),
    .i_q0(x_local_12_V_i_q0),
    .t_address0(compute_class_U0_x_local_12_V_address0),
    .t_ce0(compute_class_U0_x_local_12_V_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(x_local_12_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(x_local_12_V_i_full_n),
    .i_write(ap_channel_done_x_local_12_V),
    .t_empty_n(x_local_12_V_t_empty_n),
    .t_read(compute_class_U0_ap_ready)
);

dataflow_in_loop_0iy #(
    .DataWidth( 8 ),
    .AddressRange( 49 ),
    .AddressWidth( 6 ))
x_local_13_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(load_and_calc_norm_U0_x_local_13_V_address0),
    .i_ce0(load_and_calc_norm_U0_x_local_13_V_ce0),
    .i_we0(load_and_calc_norm_U0_x_local_13_V_we0),
    .i_d0(load_and_calc_norm_U0_x_local_13_V_d0),
    .i_q0(x_local_13_V_i_q0),
    .t_address0(compute_class_U0_x_local_13_V_address0),
    .t_ce0(compute_class_U0_x_local_13_V_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(x_local_13_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(x_local_13_V_i_full_n),
    .i_write(ap_channel_done_x_local_13_V),
    .t_empty_n(x_local_13_V_t_empty_n),
    .t_read(compute_class_U0_ap_ready)
);

dataflow_in_loop_0iy #(
    .DataWidth( 8 ),
    .AddressRange( 49 ),
    .AddressWidth( 6 ))
x_local_14_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(load_and_calc_norm_U0_x_local_14_V_address0),
    .i_ce0(load_and_calc_norm_U0_x_local_14_V_ce0),
    .i_we0(load_and_calc_norm_U0_x_local_14_V_we0),
    .i_d0(load_and_calc_norm_U0_x_local_14_V_d0),
    .i_q0(x_local_14_V_i_q0),
    .t_address0(compute_class_U0_x_local_14_V_address0),
    .t_ce0(compute_class_U0_x_local_14_V_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(x_local_14_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(x_local_14_V_i_full_n),
    .i_write(ap_channel_done_x_local_14_V),
    .t_empty_n(x_local_14_V_t_empty_n),
    .t_read(compute_class_U0_ap_ready)
);

dataflow_in_loop_0iy #(
    .DataWidth( 8 ),
    .AddressRange( 49 ),
    .AddressWidth( 6 ))
x_local_15_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .i_address0(load_and_calc_norm_U0_x_local_15_V_address0),
    .i_ce0(load_and_calc_norm_U0_x_local_15_V_ce0),
    .i_we0(load_and_calc_norm_U0_x_local_15_V_we0),
    .i_d0(load_and_calc_norm_U0_x_local_15_V_d0),
    .i_q0(x_local_15_V_i_q0),
    .t_address0(compute_class_U0_x_local_15_V_address0),
    .t_ce0(compute_class_U0_x_local_15_V_ce0),
    .t_we0(1'b0),
    .t_d0(8'd0),
    .t_q0(x_local_15_V_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(x_local_15_V_i_full_n),
    .i_write(ap_channel_done_x_local_15_V),
    .t_empty_n(x_local_15_V_t_empty_n),
    .t_read(compute_class_U0_ap_ready)
);

dataflow_in_loop_Bat_2 dataflow_in_loop_Bat_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(dataflow_in_loop_Bat_2_U0_ap_start),
    .start_full_n(start_for_dataflow_in_loop_Bat_1_1_U0_full_n),
    .ap_done(dataflow_in_loop_Bat_2_U0_ap_done),
    .ap_continue(dataflow_in_loop_Bat_2_U0_ap_continue),
    .ap_idle(dataflow_in_loop_Bat_2_U0_ap_idle),
    .ap_ready(dataflow_in_loop_Bat_2_U0_ap_ready),
    .start_out(dataflow_in_loop_Bat_2_U0_start_out),
    .start_write(dataflow_in_loop_Bat_2_U0_start_write),
    .n_0_i_i(n_0_i_i),
    .n_0_i_i_out_din(dataflow_in_loop_Bat_2_U0_n_0_i_i_out_din),
    .n_0_i_i_out_full_n(n_0_i_i_c1_full_n),
    .n_0_i_i_out_write(dataflow_in_loop_Bat_2_U0_n_0_i_i_out_write)
);

dataflow_in_loop_Bat_1_1 dataflow_in_loop_Bat_1_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(dataflow_in_loop_Bat_1_1_U0_ap_start),
    .start_full_n(start_for_p_ADSD_Classifier_cp_1_U0_full_n),
    .ap_done(dataflow_in_loop_Bat_1_1_U0_ap_done),
    .ap_continue(dataflow_in_loop_Bat_1_1_U0_ap_continue),
    .ap_idle(dataflow_in_loop_Bat_1_1_U0_ap_idle),
    .ap_ready(dataflow_in_loop_Bat_1_1_U0_ap_ready),
    .start_out(dataflow_in_loop_Bat_1_1_U0_start_out),
    .start_write(dataflow_in_loop_Bat_1_1_U0_start_write),
    .n_0_i_i_dout(n_0_i_i_c1_dout),
    .n_0_i_i_empty_n(n_0_i_i_c1_empty_n),
    .n_0_i_i_read(dataflow_in_loop_Bat_1_1_U0_n_0_i_i_read),
    .n_0_i_i_out_din(dataflow_in_loop_Bat_1_1_U0_n_0_i_i_out_din),
    .n_0_i_i_out_full_n(n_0_i_i_c_full_n),
    .n_0_i_i_out_write(dataflow_in_loop_Bat_1_1_U0_n_0_i_i_out_write)
);

load_and_calc_norm load_and_calc_norm_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(load_and_calc_norm_U0_ap_start),
    .ap_done(load_and_calc_norm_U0_ap_done),
    .ap_continue(load_and_calc_norm_U0_ap_continue),
    .ap_idle(load_and_calc_norm_U0_ap_idle),
    .ap_ready(load_and_calc_norm_U0_ap_ready),
    .in_stream_TDATA(in_stream_TDATA),
    .in_stream_TVALID(in_stream_TVALID),
    .in_stream_TREADY(load_and_calc_norm_U0_in_stream_TREADY),
    .in_stream_TKEEP(in_stream_TKEEP),
    .in_stream_TSTRB(in_stream_TSTRB),
    .in_stream_TUSER(in_stream_TUSER),
    .in_stream_TLAST(in_stream_TLAST),
    .in_stream_TID(in_stream_TID),
    .in_stream_TDEST(in_stream_TDEST),
    .x_local_0_V_address0(load_and_calc_norm_U0_x_local_0_V_address0),
    .x_local_0_V_ce0(load_and_calc_norm_U0_x_local_0_V_ce0),
    .x_local_0_V_we0(load_and_calc_norm_U0_x_local_0_V_we0),
    .x_local_0_V_d0(load_and_calc_norm_U0_x_local_0_V_d0),
    .x_local_1_V_address0(load_and_calc_norm_U0_x_local_1_V_address0),
    .x_local_1_V_ce0(load_and_calc_norm_U0_x_local_1_V_ce0),
    .x_local_1_V_we0(load_and_calc_norm_U0_x_local_1_V_we0),
    .x_local_1_V_d0(load_and_calc_norm_U0_x_local_1_V_d0),
    .x_local_2_V_address0(load_and_calc_norm_U0_x_local_2_V_address0),
    .x_local_2_V_ce0(load_and_calc_norm_U0_x_local_2_V_ce0),
    .x_local_2_V_we0(load_and_calc_norm_U0_x_local_2_V_we0),
    .x_local_2_V_d0(load_and_calc_norm_U0_x_local_2_V_d0),
    .x_local_3_V_address0(load_and_calc_norm_U0_x_local_3_V_address0),
    .x_local_3_V_ce0(load_and_calc_norm_U0_x_local_3_V_ce0),
    .x_local_3_V_we0(load_and_calc_norm_U0_x_local_3_V_we0),
    .x_local_3_V_d0(load_and_calc_norm_U0_x_local_3_V_d0),
    .x_local_4_V_address0(load_and_calc_norm_U0_x_local_4_V_address0),
    .x_local_4_V_ce0(load_and_calc_norm_U0_x_local_4_V_ce0),
    .x_local_4_V_we0(load_and_calc_norm_U0_x_local_4_V_we0),
    .x_local_4_V_d0(load_and_calc_norm_U0_x_local_4_V_d0),
    .x_local_5_V_address0(load_and_calc_norm_U0_x_local_5_V_address0),
    .x_local_5_V_ce0(load_and_calc_norm_U0_x_local_5_V_ce0),
    .x_local_5_V_we0(load_and_calc_norm_U0_x_local_5_V_we0),
    .x_local_5_V_d0(load_and_calc_norm_U0_x_local_5_V_d0),
    .x_local_6_V_address0(load_and_calc_norm_U0_x_local_6_V_address0),
    .x_local_6_V_ce0(load_and_calc_norm_U0_x_local_6_V_ce0),
    .x_local_6_V_we0(load_and_calc_norm_U0_x_local_6_V_we0),
    .x_local_6_V_d0(load_and_calc_norm_U0_x_local_6_V_d0),
    .x_local_7_V_address0(load_and_calc_norm_U0_x_local_7_V_address0),
    .x_local_7_V_ce0(load_and_calc_norm_U0_x_local_7_V_ce0),
    .x_local_7_V_we0(load_and_calc_norm_U0_x_local_7_V_we0),
    .x_local_7_V_d0(load_and_calc_norm_U0_x_local_7_V_d0),
    .x_local_8_V_address0(load_and_calc_norm_U0_x_local_8_V_address0),
    .x_local_8_V_ce0(load_and_calc_norm_U0_x_local_8_V_ce0),
    .x_local_8_V_we0(load_and_calc_norm_U0_x_local_8_V_we0),
    .x_local_8_V_d0(load_and_calc_norm_U0_x_local_8_V_d0),
    .x_local_9_V_address0(load_and_calc_norm_U0_x_local_9_V_address0),
    .x_local_9_V_ce0(load_and_calc_norm_U0_x_local_9_V_ce0),
    .x_local_9_V_we0(load_and_calc_norm_U0_x_local_9_V_we0),
    .x_local_9_V_d0(load_and_calc_norm_U0_x_local_9_V_d0),
    .x_local_10_V_address0(load_and_calc_norm_U0_x_local_10_V_address0),
    .x_local_10_V_ce0(load_and_calc_norm_U0_x_local_10_V_ce0),
    .x_local_10_V_we0(load_and_calc_norm_U0_x_local_10_V_we0),
    .x_local_10_V_d0(load_and_calc_norm_U0_x_local_10_V_d0),
    .x_local_11_V_address0(load_and_calc_norm_U0_x_local_11_V_address0),
    .x_local_11_V_ce0(load_and_calc_norm_U0_x_local_11_V_ce0),
    .x_local_11_V_we0(load_and_calc_norm_U0_x_local_11_V_we0),
    .x_local_11_V_d0(load_and_calc_norm_U0_x_local_11_V_d0),
    .x_local_12_V_address0(load_and_calc_norm_U0_x_local_12_V_address0),
    .x_local_12_V_ce0(load_and_calc_norm_U0_x_local_12_V_ce0),
    .x_local_12_V_we0(load_and_calc_norm_U0_x_local_12_V_we0),
    .x_local_12_V_d0(load_and_calc_norm_U0_x_local_12_V_d0),
    .x_local_13_V_address0(load_and_calc_norm_U0_x_local_13_V_address0),
    .x_local_13_V_ce0(load_and_calc_norm_U0_x_local_13_V_ce0),
    .x_local_13_V_we0(load_and_calc_norm_U0_x_local_13_V_we0),
    .x_local_13_V_d0(load_and_calc_norm_U0_x_local_13_V_d0),
    .x_local_14_V_address0(load_and_calc_norm_U0_x_local_14_V_address0),
    .x_local_14_V_ce0(load_and_calc_norm_U0_x_local_14_V_ce0),
    .x_local_14_V_we0(load_and_calc_norm_U0_x_local_14_V_we0),
    .x_local_14_V_d0(load_and_calc_norm_U0_x_local_14_V_d0),
    .x_local_15_V_address0(load_and_calc_norm_U0_x_local_15_V_address0),
    .x_local_15_V_ce0(load_and_calc_norm_U0_x_local_15_V_ce0),
    .x_local_15_V_we0(load_and_calc_norm_U0_x_local_15_V_we0),
    .x_local_15_V_d0(load_and_calc_norm_U0_x_local_15_V_d0),
    .ap_return(load_and_calc_norm_U0_ap_return)
);

compute_class compute_class_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(compute_class_U0_ap_start),
    .ap_done(compute_class_U0_ap_done),
    .ap_continue(compute_class_U0_ap_continue),
    .ap_idle(compute_class_U0_ap_idle),
    .ap_ready(compute_class_U0_ap_ready),
    .x_local_0_V_address0(compute_class_U0_x_local_0_V_address0),
    .x_local_0_V_ce0(compute_class_U0_x_local_0_V_ce0),
    .x_local_0_V_q0(x_local_0_V_t_q0),
    .x_local_1_V_address0(compute_class_U0_x_local_1_V_address0),
    .x_local_1_V_ce0(compute_class_U0_x_local_1_V_ce0),
    .x_local_1_V_q0(x_local_1_V_t_q0),
    .x_local_2_V_address0(compute_class_U0_x_local_2_V_address0),
    .x_local_2_V_ce0(compute_class_U0_x_local_2_V_ce0),
    .x_local_2_V_q0(x_local_2_V_t_q0),
    .x_local_3_V_address0(compute_class_U0_x_local_3_V_address0),
    .x_local_3_V_ce0(compute_class_U0_x_local_3_V_ce0),
    .x_local_3_V_q0(x_local_3_V_t_q0),
    .x_local_4_V_address0(compute_class_U0_x_local_4_V_address0),
    .x_local_4_V_ce0(compute_class_U0_x_local_4_V_ce0),
    .x_local_4_V_q0(x_local_4_V_t_q0),
    .x_local_5_V_address0(compute_class_U0_x_local_5_V_address0),
    .x_local_5_V_ce0(compute_class_U0_x_local_5_V_ce0),
    .x_local_5_V_q0(x_local_5_V_t_q0),
    .x_local_6_V_address0(compute_class_U0_x_local_6_V_address0),
    .x_local_6_V_ce0(compute_class_U0_x_local_6_V_ce0),
    .x_local_6_V_q0(x_local_6_V_t_q0),
    .x_local_7_V_address0(compute_class_U0_x_local_7_V_address0),
    .x_local_7_V_ce0(compute_class_U0_x_local_7_V_ce0),
    .x_local_7_V_q0(x_local_7_V_t_q0),
    .x_local_8_V_address0(compute_class_U0_x_local_8_V_address0),
    .x_local_8_V_ce0(compute_class_U0_x_local_8_V_ce0),
    .x_local_8_V_q0(x_local_8_V_t_q0),
    .x_local_9_V_address0(compute_class_U0_x_local_9_V_address0),
    .x_local_9_V_ce0(compute_class_U0_x_local_9_V_ce0),
    .x_local_9_V_q0(x_local_9_V_t_q0),
    .x_local_10_V_address0(compute_class_U0_x_local_10_V_address0),
    .x_local_10_V_ce0(compute_class_U0_x_local_10_V_ce0),
    .x_local_10_V_q0(x_local_10_V_t_q0),
    .x_local_11_V_address0(compute_class_U0_x_local_11_V_address0),
    .x_local_11_V_ce0(compute_class_U0_x_local_11_V_ce0),
    .x_local_11_V_q0(x_local_11_V_t_q0),
    .x_local_12_V_address0(compute_class_U0_x_local_12_V_address0),
    .x_local_12_V_ce0(compute_class_U0_x_local_12_V_ce0),
    .x_local_12_V_q0(x_local_12_V_t_q0),
    .x_local_13_V_address0(compute_class_U0_x_local_13_V_address0),
    .x_local_13_V_ce0(compute_class_U0_x_local_13_V_ce0),
    .x_local_13_V_q0(x_local_13_V_t_q0),
    .x_local_14_V_address0(compute_class_U0_x_local_14_V_address0),
    .x_local_14_V_ce0(compute_class_U0_x_local_14_V_ce0),
    .x_local_14_V_q0(x_local_14_V_t_q0),
    .x_local_15_V_address0(compute_class_U0_x_local_15_V_address0),
    .x_local_15_V_ce0(compute_class_U0_x_local_15_V_ce0),
    .x_local_15_V_q0(x_local_15_V_t_q0),
    .p_read(op_V_assign1_channel_dout),
    .ap_return(compute_class_U0_ap_return)
);

p_ADSD_Classifier_cp_4 p_ADSD_Classifier_cp_4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(p_ADSD_Classifier_cp_4_U0_ap_start),
    .ap_done(p_ADSD_Classifier_cp_4_U0_ap_done),
    .ap_continue(p_ADSD_Classifier_cp_4_U0_ap_continue),
    .ap_idle(p_ADSD_Classifier_cp_4_U0_ap_idle),
    .ap_ready(p_ADSD_Classifier_cp_4_U0_ap_ready),
    .p_read(res_internal_V_dout),
    .tmp_data_V19(p_ADSD_Classifier_cp_4_U0_tmp_data_V19),
    .tmp_data_V19_ap_vld(p_ADSD_Classifier_cp_4_U0_tmp_data_V19_ap_vld)
);

p_ADSD_Classifier_cp_3 p_ADSD_Classifier_cp_3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(p_ADSD_Classifier_cp_3_U0_ap_start),
    .ap_done(p_ADSD_Classifier_cp_3_U0_ap_done),
    .ap_continue(p_ADSD_Classifier_cp_3_U0_ap_continue),
    .ap_idle(p_ADSD_Classifier_cp_3_U0_ap_idle),
    .ap_ready(p_ADSD_Classifier_cp_3_U0_ap_ready),
    .tmp_keep_V20(p_ADSD_Classifier_cp_3_U0_tmp_keep_V20),
    .tmp_keep_V20_ap_vld(p_ADSD_Classifier_cp_3_U0_tmp_keep_V20_ap_vld)
);

p_ADSD_Classifier_cp_2 p_ADSD_Classifier_cp_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(p_ADSD_Classifier_cp_2_U0_ap_start),
    .ap_done(p_ADSD_Classifier_cp_2_U0_ap_done),
    .ap_continue(p_ADSD_Classifier_cp_2_U0_ap_continue),
    .ap_idle(p_ADSD_Classifier_cp_2_U0_ap_idle),
    .ap_ready(p_ADSD_Classifier_cp_2_U0_ap_ready),
    .tmp_strb_V21(p_ADSD_Classifier_cp_2_U0_tmp_strb_V21),
    .tmp_strb_V21_ap_vld(p_ADSD_Classifier_cp_2_U0_tmp_strb_V21_ap_vld)
);

p_ADSD_Classifier_cp_1 p_ADSD_Classifier_cp_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(p_ADSD_Classifier_cp_1_U0_ap_start),
    .ap_done(p_ADSD_Classifier_cp_1_U0_ap_done),
    .ap_continue(p_ADSD_Classifier_cp_1_U0_ap_continue),
    .ap_idle(p_ADSD_Classifier_cp_1_U0_ap_idle),
    .ap_ready(p_ADSD_Classifier_cp_1_U0_ap_ready),
    .n_0_i_i_dout(n_0_i_i_c_dout),
    .n_0_i_i_empty_n(n_0_i_i_c_empty_n),
    .n_0_i_i_read(p_ADSD_Classifier_cp_1_U0_n_0_i_i_read),
    .tmp_last_V22(p_ADSD_Classifier_cp_1_U0_tmp_last_V22),
    .tmp_last_V22_ap_vld(p_ADSD_Classifier_cp_1_U0_tmp_last_V22_ap_vld)
);

p_ADSD_Classifier_cp p_ADSD_Classifier_cp_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(p_ADSD_Classifier_cp_U0_ap_start),
    .ap_done(p_ADSD_Classifier_cp_U0_ap_done),
    .ap_continue(p_ADSD_Classifier_cp_U0_ap_continue),
    .ap_idle(p_ADSD_Classifier_cp_U0_ap_idle),
    .ap_ready(p_ADSD_Classifier_cp_U0_ap_ready),
    .out_stream_TDATA(p_ADSD_Classifier_cp_U0_out_stream_TDATA),
    .out_stream_TVALID(p_ADSD_Classifier_cp_U0_out_stream_TVALID),
    .out_stream_TREADY(out_stream_TREADY),
    .out_stream_TKEEP(p_ADSD_Classifier_cp_U0_out_stream_TKEEP),
    .out_stream_TSTRB(p_ADSD_Classifier_cp_U0_out_stream_TSTRB),
    .out_stream_TLAST(p_ADSD_Classifier_cp_U0_out_stream_TLAST),
    .tmp_data_V19(tmp_data_V_dout),
    .tmp_keep_V20(tmp_keep_V_dout),
    .tmp_strb_V21(tmp_strb_V_dout),
    .tmp_last_V22(tmp_last_V_dout)
);

fifo_w12_d2_A n_0_i_i_c1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_Bat_2_U0_n_0_i_i_out_din),
    .if_full_n(n_0_i_i_c1_full_n),
    .if_write(dataflow_in_loop_Bat_2_U0_n_0_i_i_out_write),
    .if_dout(n_0_i_i_c1_dout),
    .if_empty_n(n_0_i_i_c1_empty_n),
    .if_read(dataflow_in_loop_Bat_1_1_U0_n_0_i_i_read)
);

fifo_w12_d2_A n_0_i_i_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dataflow_in_loop_Bat_1_1_U0_n_0_i_i_out_din),
    .if_full_n(n_0_i_i_c_full_n),
    .if_write(dataflow_in_loop_Bat_1_1_U0_n_0_i_i_out_write),
    .if_dout(n_0_i_i_c_dout),
    .if_empty_n(n_0_i_i_c_empty_n),
    .if_read(p_ADSD_Classifier_cp_1_U0_n_0_i_i_read)
);

fifo_w24_d2_A op_V_assign1_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(load_and_calc_norm_U0_ap_return),
    .if_full_n(op_V_assign1_channel_full_n),
    .if_write(ap_channel_done_op_V_assign1_channel),
    .if_dout(op_V_assign1_channel_dout),
    .if_empty_n(op_V_assign1_channel_empty_n),
    .if_read(compute_class_U0_ap_ready)
);

fifo_w32_d2_A res_internal_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_class_U0_ap_return),
    .if_full_n(res_internal_V_full_n),
    .if_write(compute_class_U0_ap_done),
    .if_dout(res_internal_V_dout),
    .if_empty_n(res_internal_V_empty_n),
    .if_read(p_ADSD_Classifier_cp_4_U0_ap_ready)
);

fifo_w32_d2_A tmp_data_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(p_ADSD_Classifier_cp_4_U0_tmp_data_V19),
    .if_full_n(tmp_data_V_full_n),
    .if_write(p_ADSD_Classifier_cp_4_U0_ap_done),
    .if_dout(tmp_data_V_dout),
    .if_empty_n(tmp_data_V_empty_n),
    .if_read(p_ADSD_Classifier_cp_U0_ap_ready)
);

fifo_w1_d2_A tmp_keep_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(p_ADSD_Classifier_cp_3_U0_tmp_keep_V20),
    .if_full_n(tmp_keep_V_full_n),
    .if_write(p_ADSD_Classifier_cp_3_U0_ap_done),
    .if_dout(tmp_keep_V_dout),
    .if_empty_n(tmp_keep_V_empty_n),
    .if_read(p_ADSD_Classifier_cp_U0_ap_ready)
);

fifo_w1_d2_A tmp_strb_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(p_ADSD_Classifier_cp_2_U0_tmp_strb_V21),
    .if_full_n(tmp_strb_V_full_n),
    .if_write(p_ADSD_Classifier_cp_2_U0_ap_done),
    .if_dout(tmp_strb_V_dout),
    .if_empty_n(tmp_strb_V_empty_n),
    .if_read(p_ADSD_Classifier_cp_U0_ap_ready)
);

fifo_w1_d2_A tmp_last_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(p_ADSD_Classifier_cp_1_U0_tmp_last_V22),
    .if_full_n(tmp_last_V_full_n),
    .if_write(p_ADSD_Classifier_cp_1_U0_ap_done),
    .if_dout(tmp_last_V_dout),
    .if_empty_n(tmp_last_V_empty_n),
    .if_read(p_ADSD_Classifier_cp_U0_ap_ready)
);

start_for_dataflobgk start_for_dataflobgk_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dataflow_in_loop_Bat_1_1_U0_din),
    .if_full_n(start_for_dataflow_in_loop_Bat_1_1_U0_full_n),
    .if_write(dataflow_in_loop_Bat_2_U0_start_write),
    .if_dout(start_for_dataflow_in_loop_Bat_1_1_U0_dout),
    .if_empty_n(start_for_dataflow_in_loop_Bat_1_1_U0_empty_n),
    .if_read(dataflow_in_loop_Bat_1_1_U0_ap_ready)
);

start_for_p_ADSD_bhl start_for_p_ADSD_bhl_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_p_ADSD_Classifier_cp_1_U0_din),
    .if_full_n(start_for_p_ADSD_Classifier_cp_1_U0_full_n),
    .if_write(dataflow_in_loop_Bat_1_1_U0_start_write),
    .if_dout(start_for_p_ADSD_Classifier_cp_1_U0_dout),
    .if_empty_n(start_for_p_ADSD_Classifier_cp_1_U0_empty_n),
    .if_read(p_ADSD_Classifier_cp_1_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_op_V_assign1_channel <= 1'b0;
    end else begin
        if (((load_and_calc_norm_U0_ap_done & load_and_calc_norm_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_op_V_assign1_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_op_V_assign1_channel <= ap_sync_channel_write_op_V_assign1_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_x_local_0_V <= 1'b0;
    end else begin
        if (((load_and_calc_norm_U0_ap_done & load_and_calc_norm_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_x_local_0_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_x_local_0_V <= ap_sync_channel_write_x_local_0_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_x_local_10_V <= 1'b0;
    end else begin
        if (((load_and_calc_norm_U0_ap_done & load_and_calc_norm_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_x_local_10_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_x_local_10_V <= ap_sync_channel_write_x_local_10_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_x_local_11_V <= 1'b0;
    end else begin
        if (((load_and_calc_norm_U0_ap_done & load_and_calc_norm_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_x_local_11_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_x_local_11_V <= ap_sync_channel_write_x_local_11_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_x_local_12_V <= 1'b0;
    end else begin
        if (((load_and_calc_norm_U0_ap_done & load_and_calc_norm_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_x_local_12_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_x_local_12_V <= ap_sync_channel_write_x_local_12_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_x_local_13_V <= 1'b0;
    end else begin
        if (((load_and_calc_norm_U0_ap_done & load_and_calc_norm_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_x_local_13_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_x_local_13_V <= ap_sync_channel_write_x_local_13_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_x_local_14_V <= 1'b0;
    end else begin
        if (((load_and_calc_norm_U0_ap_done & load_and_calc_norm_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_x_local_14_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_x_local_14_V <= ap_sync_channel_write_x_local_14_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_x_local_15_V <= 1'b0;
    end else begin
        if (((load_and_calc_norm_U0_ap_done & load_and_calc_norm_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_x_local_15_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_x_local_15_V <= ap_sync_channel_write_x_local_15_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_x_local_1_V <= 1'b0;
    end else begin
        if (((load_and_calc_norm_U0_ap_done & load_and_calc_norm_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_x_local_1_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_x_local_1_V <= ap_sync_channel_write_x_local_1_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_x_local_2_V <= 1'b0;
    end else begin
        if (((load_and_calc_norm_U0_ap_done & load_and_calc_norm_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_x_local_2_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_x_local_2_V <= ap_sync_channel_write_x_local_2_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_x_local_3_V <= 1'b0;
    end else begin
        if (((load_and_calc_norm_U0_ap_done & load_and_calc_norm_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_x_local_3_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_x_local_3_V <= ap_sync_channel_write_x_local_3_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_x_local_4_V <= 1'b0;
    end else begin
        if (((load_and_calc_norm_U0_ap_done & load_and_calc_norm_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_x_local_4_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_x_local_4_V <= ap_sync_channel_write_x_local_4_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_x_local_5_V <= 1'b0;
    end else begin
        if (((load_and_calc_norm_U0_ap_done & load_and_calc_norm_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_x_local_5_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_x_local_5_V <= ap_sync_channel_write_x_local_5_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_x_local_6_V <= 1'b0;
    end else begin
        if (((load_and_calc_norm_U0_ap_done & load_and_calc_norm_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_x_local_6_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_x_local_6_V <= ap_sync_channel_write_x_local_6_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_x_local_7_V <= 1'b0;
    end else begin
        if (((load_and_calc_norm_U0_ap_done & load_and_calc_norm_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_x_local_7_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_x_local_7_V <= ap_sync_channel_write_x_local_7_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_x_local_8_V <= 1'b0;
    end else begin
        if (((load_and_calc_norm_U0_ap_done & load_and_calc_norm_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_x_local_8_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_x_local_8_V <= ap_sync_channel_write_x_local_8_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_x_local_9_V <= 1'b0;
    end else begin
        if (((load_and_calc_norm_U0_ap_done & load_and_calc_norm_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_x_local_9_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_x_local_9_V <= ap_sync_channel_write_x_local_9_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_dataflow_in_loop_Bat_2_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_dataflow_in_loop_Bat_2_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_dataflow_in_loop_Bat_2_U0_ap_ready <= ap_sync_dataflow_in_loop_Bat_2_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_load_and_calc_norm_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_load_and_calc_norm_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_load_and_calc_norm_U0_ap_ready <= ap_sync_load_and_calc_norm_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((dataflow_in_loop_Bat_2_U0_ap_ready == 1'b0) & (ap_sync_ready == 1'b1))) begin
        dataflow_in_loop_Bat_2_U0_ap_ready_count <= (dataflow_in_loop_Bat_2_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (dataflow_in_loop_Bat_2_U0_ap_ready == 1'b1))) begin
        dataflow_in_loop_Bat_2_U0_ap_ready_count <= (dataflow_in_loop_Bat_2_U0_ap_ready_count + 2'd1);
    end
end

always @ (posedge ap_clk) begin
    if (((load_and_calc_norm_U0_ap_ready == 1'b0) & (ap_sync_ready == 1'b1))) begin
        load_and_calc_norm_U0_ap_ready_count <= (load_and_calc_norm_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (load_and_calc_norm_U0_ap_ready == 1'b1))) begin
        load_and_calc_norm_U0_ap_ready_count <= (load_and_calc_norm_U0_ap_ready_count + 2'd1);
    end
end

assign ap_channel_done_op_V_assign1_channel = (load_and_calc_norm_U0_ap_done & (ap_sync_reg_channel_write_op_V_assign1_channel ^ 1'b1));

assign ap_channel_done_res_internal_V = compute_class_U0_ap_done;

assign ap_channel_done_tmp_data_V = p_ADSD_Classifier_cp_4_U0_ap_done;

assign ap_channel_done_tmp_keep_V = p_ADSD_Classifier_cp_3_U0_ap_done;

assign ap_channel_done_tmp_last_V = p_ADSD_Classifier_cp_1_U0_ap_done;

assign ap_channel_done_tmp_strb_V = p_ADSD_Classifier_cp_2_U0_ap_done;

assign ap_channel_done_x_local_0_V = (load_and_calc_norm_U0_ap_done & (ap_sync_reg_channel_write_x_local_0_V ^ 1'b1));

assign ap_channel_done_x_local_10_V = (load_and_calc_norm_U0_ap_done & (ap_sync_reg_channel_write_x_local_10_V ^ 1'b1));

assign ap_channel_done_x_local_11_V = (load_and_calc_norm_U0_ap_done & (ap_sync_reg_channel_write_x_local_11_V ^ 1'b1));

assign ap_channel_done_x_local_12_V = (load_and_calc_norm_U0_ap_done & (ap_sync_reg_channel_write_x_local_12_V ^ 1'b1));

assign ap_channel_done_x_local_13_V = (load_and_calc_norm_U0_ap_done & (ap_sync_reg_channel_write_x_local_13_V ^ 1'b1));

assign ap_channel_done_x_local_14_V = (load_and_calc_norm_U0_ap_done & (ap_sync_reg_channel_write_x_local_14_V ^ 1'b1));

assign ap_channel_done_x_local_15_V = (load_and_calc_norm_U0_ap_done & (ap_sync_reg_channel_write_x_local_15_V ^ 1'b1));

assign ap_channel_done_x_local_1_V = (load_and_calc_norm_U0_ap_done & (ap_sync_reg_channel_write_x_local_1_V ^ 1'b1));

assign ap_channel_done_x_local_2_V = (load_and_calc_norm_U0_ap_done & (ap_sync_reg_channel_write_x_local_2_V ^ 1'b1));

assign ap_channel_done_x_local_3_V = (load_and_calc_norm_U0_ap_done & (ap_sync_reg_channel_write_x_local_3_V ^ 1'b1));

assign ap_channel_done_x_local_4_V = (load_and_calc_norm_U0_ap_done & (ap_sync_reg_channel_write_x_local_4_V ^ 1'b1));

assign ap_channel_done_x_local_5_V = (load_and_calc_norm_U0_ap_done & (ap_sync_reg_channel_write_x_local_5_V ^ 1'b1));

assign ap_channel_done_x_local_6_V = (load_and_calc_norm_U0_ap_done & (ap_sync_reg_channel_write_x_local_6_V ^ 1'b1));

assign ap_channel_done_x_local_7_V = (load_and_calc_norm_U0_ap_done & (ap_sync_reg_channel_write_x_local_7_V ^ 1'b1));

assign ap_channel_done_x_local_8_V = (load_and_calc_norm_U0_ap_done & (ap_sync_reg_channel_write_x_local_8_V ^ 1'b1));

assign ap_channel_done_x_local_9_V = (load_and_calc_norm_U0_ap_done & (ap_sync_reg_channel_write_x_local_9_V ^ 1'b1));

assign ap_done = p_ADSD_Classifier_cp_U0_ap_done;

assign ap_idle = (p_ADSD_Classifier_cp_U0_ap_idle & p_ADSD_Classifier_cp_4_U0_ap_idle & p_ADSD_Classifier_cp_3_U0_ap_idle & p_ADSD_Classifier_cp_2_U0_ap_idle & p_ADSD_Classifier_cp_1_U0_ap_idle & load_and_calc_norm_U0_ap_idle & (tmp_last_V_empty_n ^ 1'b1) & (tmp_strb_V_empty_n ^ 1'b1) & (tmp_keep_V_empty_n ^ 1'b1) & (tmp_data_V_empty_n ^ 1'b1) & (res_internal_V_empty_n ^ 1'b1) & (op_V_assign1_channel_empty_n ^ 1'b1) & (x_local_15_V_t_empty_n ^ 1'b1) & (x_local_14_V_t_empty_n ^ 1'b1) & (x_local_13_V_t_empty_n ^ 1'b1) & (x_local_12_V_t_empty_n ^ 1'b1) & (x_local_11_V_t_empty_n ^ 1'b1) & (x_local_10_V_t_empty_n ^ 1'b1) & (x_local_9_V_t_empty_n ^ 1'b1) & (x_local_8_V_t_empty_n ^ 1'b1) & (x_local_7_V_t_empty_n ^ 1'b1) & (x_local_6_V_t_empty_n ^ 1'b1) & (x_local_5_V_t_empty_n ^ 1'b1) & (x_local_4_V_t_empty_n ^ 1'b1) & (x_local_3_V_t_empty_n ^ 1'b1) & (x_local_2_V_t_empty_n ^ 1'b1) & (x_local_1_V_t_empty_n ^ 1'b1) & (x_local_0_V_t_empty_n ^ 1'b1) & dataflow_in_loop_Bat_2_U0_ap_idle & dataflow_in_loop_Bat_1_1_U0_ap_idle & compute_class_U0_ap_idle);

assign ap_ready = ap_sync_ready;

assign ap_sync_channel_write_op_V_assign1_channel = ((op_V_assign1_channel_full_n & ap_channel_done_op_V_assign1_channel) | ap_sync_reg_channel_write_op_V_assign1_channel);

assign ap_sync_channel_write_x_local_0_V = ((load_and_calc_norm_U0_x_local_0_V_full_n & ap_channel_done_x_local_0_V) | ap_sync_reg_channel_write_x_local_0_V);

assign ap_sync_channel_write_x_local_10_V = ((load_and_calc_norm_U0_x_local_10_V_full_n & ap_channel_done_x_local_10_V) | ap_sync_reg_channel_write_x_local_10_V);

assign ap_sync_channel_write_x_local_11_V = ((load_and_calc_norm_U0_x_local_11_V_full_n & ap_channel_done_x_local_11_V) | ap_sync_reg_channel_write_x_local_11_V);

assign ap_sync_channel_write_x_local_12_V = ((load_and_calc_norm_U0_x_local_12_V_full_n & ap_channel_done_x_local_12_V) | ap_sync_reg_channel_write_x_local_12_V);

assign ap_sync_channel_write_x_local_13_V = ((load_and_calc_norm_U0_x_local_13_V_full_n & ap_channel_done_x_local_13_V) | ap_sync_reg_channel_write_x_local_13_V);

assign ap_sync_channel_write_x_local_14_V = ((load_and_calc_norm_U0_x_local_14_V_full_n & ap_channel_done_x_local_14_V) | ap_sync_reg_channel_write_x_local_14_V);

assign ap_sync_channel_write_x_local_15_V = ((load_and_calc_norm_U0_x_local_15_V_full_n & ap_channel_done_x_local_15_V) | ap_sync_reg_channel_write_x_local_15_V);

assign ap_sync_channel_write_x_local_1_V = ((load_and_calc_norm_U0_x_local_1_V_full_n & ap_channel_done_x_local_1_V) | ap_sync_reg_channel_write_x_local_1_V);

assign ap_sync_channel_write_x_local_2_V = ((load_and_calc_norm_U0_x_local_2_V_full_n & ap_channel_done_x_local_2_V) | ap_sync_reg_channel_write_x_local_2_V);

assign ap_sync_channel_write_x_local_3_V = ((load_and_calc_norm_U0_x_local_3_V_full_n & ap_channel_done_x_local_3_V) | ap_sync_reg_channel_write_x_local_3_V);

assign ap_sync_channel_write_x_local_4_V = ((load_and_calc_norm_U0_x_local_4_V_full_n & ap_channel_done_x_local_4_V) | ap_sync_reg_channel_write_x_local_4_V);

assign ap_sync_channel_write_x_local_5_V = ((load_and_calc_norm_U0_x_local_5_V_full_n & ap_channel_done_x_local_5_V) | ap_sync_reg_channel_write_x_local_5_V);

assign ap_sync_channel_write_x_local_6_V = ((load_and_calc_norm_U0_x_local_6_V_full_n & ap_channel_done_x_local_6_V) | ap_sync_reg_channel_write_x_local_6_V);

assign ap_sync_channel_write_x_local_7_V = ((load_and_calc_norm_U0_x_local_7_V_full_n & ap_channel_done_x_local_7_V) | ap_sync_reg_channel_write_x_local_7_V);

assign ap_sync_channel_write_x_local_8_V = ((load_and_calc_norm_U0_x_local_8_V_full_n & ap_channel_done_x_local_8_V) | ap_sync_reg_channel_write_x_local_8_V);

assign ap_sync_channel_write_x_local_9_V = ((load_and_calc_norm_U0_x_local_9_V_full_n & ap_channel_done_x_local_9_V) | ap_sync_reg_channel_write_x_local_9_V);

assign ap_sync_continue = ap_continue;

assign ap_sync_dataflow_in_loop_Bat_2_U0_ap_ready = (dataflow_in_loop_Bat_2_U0_ap_ready | ap_sync_reg_dataflow_in_loop_Bat_2_U0_ap_ready);

assign ap_sync_done = p_ADSD_Classifier_cp_U0_ap_done;

assign ap_sync_load_and_calc_norm_U0_ap_ready = (load_and_calc_norm_U0_ap_ready | ap_sync_reg_load_and_calc_norm_U0_ap_ready);

assign ap_sync_ready = (ap_sync_load_and_calc_norm_U0_ap_ready & ap_sync_dataflow_in_loop_Bat_2_U0_ap_ready);

assign compute_class_U0_ap_continue = res_internal_V_full_n;

assign compute_class_U0_ap_start = (x_local_9_V_t_empty_n & x_local_8_V_t_empty_n & x_local_7_V_t_empty_n & x_local_6_V_t_empty_n & x_local_5_V_t_empty_n & x_local_4_V_t_empty_n & x_local_3_V_t_empty_n & x_local_2_V_t_empty_n & x_local_1_V_t_empty_n & x_local_15_V_t_empty_n & x_local_14_V_t_empty_n & x_local_13_V_t_empty_n & x_local_12_V_t_empty_n & x_local_11_V_t_empty_n & x_local_10_V_t_empty_n & x_local_0_V_t_empty_n & op_V_assign1_channel_empty_n);

assign compute_class_U0_start_full_n = 1'b1;

assign compute_class_U0_start_write = 1'b0;

assign dataflow_in_loop_Bat_1_1_U0_ap_continue = 1'b1;

assign dataflow_in_loop_Bat_1_1_U0_ap_start = start_for_dataflow_in_loop_Bat_1_1_U0_empty_n;

assign dataflow_in_loop_Bat_2_U0_ap_continue = 1'b1;

assign dataflow_in_loop_Bat_2_U0_ap_start = ((ap_sync_reg_dataflow_in_loop_Bat_2_U0_ap_ready ^ 1'b1) & ap_start);

assign in_stream_TREADY = load_and_calc_norm_U0_in_stream_TREADY;

assign load_and_calc_norm_U0_ap_continue = (ap_sync_channel_write_x_local_9_V & ap_sync_channel_write_x_local_8_V & ap_sync_channel_write_x_local_7_V & ap_sync_channel_write_x_local_6_V & ap_sync_channel_write_x_local_5_V & ap_sync_channel_write_x_local_4_V & ap_sync_channel_write_x_local_3_V & ap_sync_channel_write_x_local_2_V & ap_sync_channel_write_x_local_1_V & ap_sync_channel_write_x_local_15_V & ap_sync_channel_write_x_local_14_V & ap_sync_channel_write_x_local_13_V & ap_sync_channel_write_x_local_12_V & ap_sync_channel_write_x_local_11_V & ap_sync_channel_write_x_local_10_V & ap_sync_channel_write_x_local_0_V & ap_sync_channel_write_op_V_assign1_channel);

assign load_and_calc_norm_U0_ap_start = ((ap_sync_reg_load_and_calc_norm_U0_ap_ready ^ 1'b1) & ap_start);

assign load_and_calc_norm_U0_start_full_n = 1'b1;

assign load_and_calc_norm_U0_start_write = 1'b0;

assign load_and_calc_norm_U0_x_local_0_V_full_n = x_local_0_V_i_full_n;

assign load_and_calc_norm_U0_x_local_10_V_full_n = x_local_10_V_i_full_n;

assign load_and_calc_norm_U0_x_local_11_V_full_n = x_local_11_V_i_full_n;

assign load_and_calc_norm_U0_x_local_12_V_full_n = x_local_12_V_i_full_n;

assign load_and_calc_norm_U0_x_local_13_V_full_n = x_local_13_V_i_full_n;

assign load_and_calc_norm_U0_x_local_14_V_full_n = x_local_14_V_i_full_n;

assign load_and_calc_norm_U0_x_local_15_V_full_n = x_local_15_V_i_full_n;

assign load_and_calc_norm_U0_x_local_1_V_full_n = x_local_1_V_i_full_n;

assign load_and_calc_norm_U0_x_local_2_V_full_n = x_local_2_V_i_full_n;

assign load_and_calc_norm_U0_x_local_3_V_full_n = x_local_3_V_i_full_n;

assign load_and_calc_norm_U0_x_local_4_V_full_n = x_local_4_V_i_full_n;

assign load_and_calc_norm_U0_x_local_5_V_full_n = x_local_5_V_i_full_n;

assign load_and_calc_norm_U0_x_local_6_V_full_n = x_local_6_V_i_full_n;

assign load_and_calc_norm_U0_x_local_7_V_full_n = x_local_7_V_i_full_n;

assign load_and_calc_norm_U0_x_local_8_V_full_n = x_local_8_V_i_full_n;

assign load_and_calc_norm_U0_x_local_9_V_full_n = x_local_9_V_i_full_n;

assign out_stream_TDATA = p_ADSD_Classifier_cp_U0_out_stream_TDATA;

assign out_stream_TKEEP = p_ADSD_Classifier_cp_U0_out_stream_TKEEP;

assign out_stream_TLAST = p_ADSD_Classifier_cp_U0_out_stream_TLAST;

assign out_stream_TSTRB = p_ADSD_Classifier_cp_U0_out_stream_TSTRB;

assign out_stream_TVALID = p_ADSD_Classifier_cp_U0_out_stream_TVALID;

assign p_ADSD_Classifier_cp_1_U0_ap_continue = tmp_last_V_full_n;

assign p_ADSD_Classifier_cp_1_U0_ap_start = start_for_p_ADSD_Classifier_cp_1_U0_empty_n;

assign p_ADSD_Classifier_cp_1_U0_start_full_n = 1'b1;

assign p_ADSD_Classifier_cp_1_U0_start_write = 1'b0;

assign p_ADSD_Classifier_cp_2_U0_ap_continue = tmp_strb_V_full_n;

assign p_ADSD_Classifier_cp_2_U0_ap_start = ap_start;

assign p_ADSD_Classifier_cp_2_U0_start_full_n = 1'b1;

assign p_ADSD_Classifier_cp_2_U0_start_write = 1'b0;

assign p_ADSD_Classifier_cp_3_U0_ap_continue = tmp_keep_V_full_n;

assign p_ADSD_Classifier_cp_3_U0_ap_start = ap_start;

assign p_ADSD_Classifier_cp_3_U0_start_full_n = 1'b1;

assign p_ADSD_Classifier_cp_3_U0_start_write = 1'b0;

assign p_ADSD_Classifier_cp_4_U0_ap_continue = tmp_data_V_full_n;

assign p_ADSD_Classifier_cp_4_U0_ap_start = res_internal_V_empty_n;

assign p_ADSD_Classifier_cp_4_U0_start_full_n = 1'b1;

assign p_ADSD_Classifier_cp_4_U0_start_write = 1'b0;

assign p_ADSD_Classifier_cp_U0_ap_continue = ap_continue;

assign p_ADSD_Classifier_cp_U0_ap_start = (tmp_strb_V_empty_n & tmp_last_V_empty_n & tmp_keep_V_empty_n & tmp_data_V_empty_n);

assign p_ADSD_Classifier_cp_U0_start_full_n = 1'b1;

assign p_ADSD_Classifier_cp_U0_start_write = 1'b0;

assign start_for_dataflow_in_loop_Bat_1_1_U0_din = 1'b1;

assign start_for_p_ADSD_Classifier_cp_1_U0_din = 1'b1;

endmodule //dataflow_in_loop_Bat_1
