// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module load_and_calc_norm61 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TUSER,
        in_stream_TLAST,
        in_stream_TID,
        in_stream_TDEST,
        x_local_0_V_address0,
        x_local_0_V_ce0,
        x_local_0_V_we0,
        x_local_0_V_d0,
        x_local_1_V_address0,
        x_local_1_V_ce0,
        x_local_1_V_we0,
        x_local_1_V_d0,
        x_local_2_V_address0,
        x_local_2_V_ce0,
        x_local_2_V_we0,
        x_local_2_V_d0,
        x_local_3_V_address0,
        x_local_3_V_ce0,
        x_local_3_V_we0,
        x_local_3_V_d0,
        x_local_4_V_address0,
        x_local_4_V_ce0,
        x_local_4_V_we0,
        x_local_4_V_d0,
        x_local_5_V_address0,
        x_local_5_V_ce0,
        x_local_5_V_we0,
        x_local_5_V_d0,
        x_local_6_V_address0,
        x_local_6_V_ce0,
        x_local_6_V_we0,
        x_local_6_V_d0,
        x_local_7_V_address0,
        x_local_7_V_ce0,
        x_local_7_V_we0,
        x_local_7_V_d0,
        x_local_8_V_address0,
        x_local_8_V_ce0,
        x_local_8_V_we0,
        x_local_8_V_d0,
        x_local_9_V_address0,
        x_local_9_V_ce0,
        x_local_9_V_we0,
        x_local_9_V_d0,
        x_local_10_V_address0,
        x_local_10_V_ce0,
        x_local_10_V_we0,
        x_local_10_V_d0,
        x_local_11_V_address0,
        x_local_11_V_ce0,
        x_local_11_V_we0,
        x_local_11_V_d0,
        x_local_12_V_address0,
        x_local_12_V_ce0,
        x_local_12_V_we0,
        x_local_12_V_d0,
        x_local_13_V_address0,
        x_local_13_V_ce0,
        x_local_13_V_we0,
        x_local_13_V_d0,
        x_local_14_V_address0,
        x_local_14_V_ce0,
        x_local_14_V_we0,
        x_local_14_V_d0,
        x_local_15_V_address0,
        x_local_15_V_ce0,
        x_local_15_V_we0,
        x_local_15_V_d0,
        n_0_i_i,
        n_0_i_i_out_din,
        n_0_i_i_out_full_n,
        n_0_i_i_out_write,
        ap_return
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state5 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [63:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [7:0] in_stream_TKEEP;
input  [7:0] in_stream_TSTRB;
input  [0:0] in_stream_TUSER;
input  [0:0] in_stream_TLAST;
input  [0:0] in_stream_TID;
input  [0:0] in_stream_TDEST;
output  [5:0] x_local_0_V_address0;
output   x_local_0_V_ce0;
output   x_local_0_V_we0;
output  [7:0] x_local_0_V_d0;
output  [5:0] x_local_1_V_address0;
output   x_local_1_V_ce0;
output   x_local_1_V_we0;
output  [7:0] x_local_1_V_d0;
output  [5:0] x_local_2_V_address0;
output   x_local_2_V_ce0;
output   x_local_2_V_we0;
output  [7:0] x_local_2_V_d0;
output  [5:0] x_local_3_V_address0;
output   x_local_3_V_ce0;
output   x_local_3_V_we0;
output  [7:0] x_local_3_V_d0;
output  [5:0] x_local_4_V_address0;
output   x_local_4_V_ce0;
output   x_local_4_V_we0;
output  [7:0] x_local_4_V_d0;
output  [5:0] x_local_5_V_address0;
output   x_local_5_V_ce0;
output   x_local_5_V_we0;
output  [7:0] x_local_5_V_d0;
output  [5:0] x_local_6_V_address0;
output   x_local_6_V_ce0;
output   x_local_6_V_we0;
output  [7:0] x_local_6_V_d0;
output  [5:0] x_local_7_V_address0;
output   x_local_7_V_ce0;
output   x_local_7_V_we0;
output  [7:0] x_local_7_V_d0;
output  [5:0] x_local_8_V_address0;
output   x_local_8_V_ce0;
output   x_local_8_V_we0;
output  [7:0] x_local_8_V_d0;
output  [5:0] x_local_9_V_address0;
output   x_local_9_V_ce0;
output   x_local_9_V_we0;
output  [7:0] x_local_9_V_d0;
output  [5:0] x_local_10_V_address0;
output   x_local_10_V_ce0;
output   x_local_10_V_we0;
output  [7:0] x_local_10_V_d0;
output  [5:0] x_local_11_V_address0;
output   x_local_11_V_ce0;
output   x_local_11_V_we0;
output  [7:0] x_local_11_V_d0;
output  [5:0] x_local_12_V_address0;
output   x_local_12_V_ce0;
output   x_local_12_V_we0;
output  [7:0] x_local_12_V_d0;
output  [5:0] x_local_13_V_address0;
output   x_local_13_V_ce0;
output   x_local_13_V_we0;
output  [7:0] x_local_13_V_d0;
output  [5:0] x_local_14_V_address0;
output   x_local_14_V_ce0;
output   x_local_14_V_we0;
output  [7:0] x_local_14_V_d0;
output  [5:0] x_local_15_V_address0;
output   x_local_15_V_ce0;
output   x_local_15_V_we0;
output  [7:0] x_local_15_V_d0;
input  [11:0] n_0_i_i;
output  [11:0] n_0_i_i_out_din;
input   n_0_i_i_out_full_n;
output   n_0_i_i_out_write;
output  [23:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg x_local_0_V_ce0;
reg x_local_0_V_we0;
reg x_local_1_V_ce0;
reg x_local_1_V_we0;
reg x_local_2_V_ce0;
reg x_local_2_V_we0;
reg x_local_3_V_ce0;
reg x_local_3_V_we0;
reg x_local_4_V_ce0;
reg x_local_4_V_we0;
reg x_local_5_V_ce0;
reg x_local_5_V_we0;
reg x_local_6_V_ce0;
reg x_local_6_V_we0;
reg x_local_7_V_ce0;
reg x_local_7_V_we0;
reg x_local_8_V_ce0;
reg x_local_8_V_we0;
reg x_local_9_V_ce0;
reg x_local_9_V_we0;
reg x_local_10_V_ce0;
reg x_local_10_V_we0;
reg x_local_11_V_ce0;
reg x_local_11_V_we0;
reg x_local_12_V_ce0;
reg x_local_12_V_we0;
reg x_local_13_V_ce0;
reg x_local_13_V_we0;
reg x_local_14_V_ce0;
reg x_local_14_V_we0;
reg x_local_15_V_ce0;
reg x_local_15_V_we0;
reg n_0_i_i_out_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [63:0] in_stream_V_data_V_0_data_out;
wire    in_stream_V_data_V_0_vld_in;
wire    in_stream_V_data_V_0_vld_out;
wire    in_stream_V_data_V_0_ack_in;
reg    in_stream_V_data_V_0_ack_out;
reg   [63:0] in_stream_V_data_V_0_payload_A;
reg   [63:0] in_stream_V_data_V_0_payload_B;
reg    in_stream_V_data_V_0_sel_rd;
reg    in_stream_V_data_V_0_sel_wr;
wire    in_stream_V_data_V_0_sel;
wire    in_stream_V_data_V_0_load_A;
wire    in_stream_V_data_V_0_load_B;
reg   [1:0] in_stream_V_data_V_0_state;
wire    in_stream_V_data_V_0_state_cmp_full;
wire    in_stream_V_dest_V_0_vld_in;
reg    in_stream_V_dest_V_0_ack_out;
reg   [1:0] in_stream_V_dest_V_0_state;
reg    in_stream_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond1_i_i_reg_722;
reg    n_0_i_i_out_blk_n;
reg   [23:0] calculated_norm_V_reg_374;
reg   [6:0] i_i_i_reg_386;
wire   [0:0] exitcond1_i_i_fu_397_p2;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond1_i_i_reg_722_pp0_iter1_reg;
wire   [6:0] i_fu_403_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] tmp_2_fu_409_p1;
reg   [0:0] tmp_2_reg_731;
reg   [5:0] tmp_2_cast_i_i_reg_735;
wire   [15:0] r_V_2_i_i_fu_516_p2;
reg   [15:0] r_V_2_i_i_reg_740;
wire   [15:0] r_V_3_i_i_fu_538_p2;
reg   [15:0] r_V_3_i_i_reg_745;
wire   [15:0] r_V_6_i_i_fu_620_p2;
reg   [15:0] r_V_6_i_i_reg_750;
wire   [15:0] r_V_7_i_i_fu_642_p2;
reg   [15:0] r_V_7_i_i_reg_755;
wire   [23:0] tmp1_fu_648_p2;
reg   [23:0] tmp1_reg_760;
wire   [23:0] tmp4_fu_654_p2;
reg   [23:0] tmp4_reg_765;
wire   [23:0] p_Val2_4_7_i_i_fu_716_p2;
reg    ap_enable_reg_pp0_iter2;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
wire   [63:0] newIndex1_i_i_fu_433_p1;
wire  signed [7:0] tmp_3_fu_427_p1;
wire  signed [7:0] p_Result_1_i_i_fu_470_p4;
wire  signed [7:0] p_Result_2_i_i_fu_500_p4;
wire  signed [7:0] p_Result_3_i_i_fu_522_p4;
wire  signed [7:0] p_Result_4_i_i_fu_544_p4;
wire  signed [7:0] p_Result_5_i_i_fu_574_p4;
wire  signed [7:0] p_Result_6_i_i_fu_604_p4;
wire  signed [7:0] p_Result_7_i_i_fu_626_p4;
wire  signed [7:0] r_V_i_i_fu_456_p0;
wire  signed [15:0] OP1_V_i_i_fu_452_p1;
wire  signed [7:0] r_V_i_i_fu_456_p1;
wire   [15:0] r_V_i_i_fu_456_p2;
wire  signed [7:0] r_V_1_i_i_fu_486_p0;
wire  signed [15:0] OP1_V_1_i_i_fu_482_p1;
wire  signed [7:0] r_V_1_i_i_fu_486_p1;
wire   [15:0] r_V_1_i_i_fu_486_p2;
wire  signed [7:0] r_V_2_i_i_fu_516_p0;
wire  signed [15:0] OP1_V_2_i_i_fu_512_p1;
wire  signed [7:0] r_V_2_i_i_fu_516_p1;
wire  signed [7:0] r_V_3_i_i_fu_538_p0;
wire  signed [15:0] OP1_V_3_i_i_fu_534_p1;
wire  signed [7:0] r_V_3_i_i_fu_538_p1;
wire  signed [7:0] r_V_4_i_i_fu_560_p0;
wire  signed [15:0] OP1_V_4_i_i_fu_556_p1;
wire  signed [7:0] r_V_4_i_i_fu_560_p1;
wire   [15:0] r_V_4_i_i_fu_560_p2;
wire  signed [7:0] r_V_5_i_i_fu_590_p0;
wire  signed [15:0] OP1_V_5_i_i_fu_586_p1;
wire  signed [7:0] r_V_5_i_i_fu_590_p1;
wire   [15:0] r_V_5_i_i_fu_590_p2;
wire  signed [7:0] r_V_6_i_i_fu_620_p0;
wire  signed [15:0] OP1_V_6_i_i_fu_616_p1;
wire  signed [7:0] r_V_6_i_i_fu_620_p1;
wire  signed [7:0] r_V_7_i_i_fu_642_p0;
wire  signed [15:0] OP1_V_7_i_i_fu_638_p1;
wire  signed [7:0] r_V_7_i_i_fu_642_p1;
wire   [23:0] tmp_9_1_i_i_fu_492_p3;
wire   [23:0] tmp_9_i_i_fu_462_p3;
wire   [23:0] tmp_9_5_i_i_fu_596_p3;
wire   [23:0] tmp_9_4_i_i_fu_566_p3;
wire   [23:0] tmp_9_3_i_i_fu_667_p3;
wire   [23:0] tmp_9_2_i_i_fu_660_p3;
wire   [23:0] tmp2_fu_688_p2;
wire   [23:0] tmp_9_7_i_i_fu_681_p3;
wire   [23:0] tmp_9_6_i_i_fu_674_p3;
wire   [23:0] tmp5_fu_699_p2;
wire   [23:0] tmp_fu_694_p2;
wire   [23:0] tmp3_fu_705_p2;
wire   [23:0] tmp_1_fu_710_p2;
wire    ap_CS_fsm_state5;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 in_stream_V_data_V_0_sel_rd = 1'b0;
#0 in_stream_V_data_V_0_sel_wr = 1'b0;
#0 in_stream_V_data_V_0_state = 2'd0;
#0 in_stream_V_dest_V_0_state = 2'd0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state5)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((ap_start == 1'b0) | (n_0_i_i_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if ((~((ap_start == 1'b0) | (n_0_i_i_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        in_stream_V_data_V_0_sel_rd <= 1'b0;
    end else begin
        if (((in_stream_V_data_V_0_ack_out == 1'b1) & (in_stream_V_data_V_0_vld_out == 1'b1))) begin
            in_stream_V_data_V_0_sel_rd <= ~in_stream_V_data_V_0_sel_rd;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        in_stream_V_data_V_0_sel_wr <= 1'b0;
    end else begin
        if (((in_stream_V_data_V_0_ack_in == 1'b1) & (in_stream_V_data_V_0_vld_in == 1'b1))) begin
            in_stream_V_data_V_0_sel_wr <= ~in_stream_V_data_V_0_sel_wr;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        in_stream_V_data_V_0_state <= 2'd0;
    end else begin
        if ((((in_stream_V_data_V_0_state == 2'd2) & (in_stream_V_data_V_0_vld_in == 1'b0)) | ((in_stream_V_data_V_0_state == 2'd3) & (in_stream_V_data_V_0_vld_in == 1'b0) & (in_stream_V_data_V_0_ack_out == 1'b1)))) begin
            in_stream_V_data_V_0_state <= 2'd2;
        end else if ((((in_stream_V_data_V_0_state == 2'd1) & (in_stream_V_data_V_0_ack_out == 1'b0)) | ((in_stream_V_data_V_0_state == 2'd3) & (in_stream_V_data_V_0_ack_out == 1'b0) & (in_stream_V_data_V_0_vld_in == 1'b1)))) begin
            in_stream_V_data_V_0_state <= 2'd1;
        end else if (((~((in_stream_V_data_V_0_vld_in == 1'b0) & (in_stream_V_data_V_0_ack_out == 1'b1)) & ~((in_stream_V_data_V_0_ack_out == 1'b0) & (in_stream_V_data_V_0_vld_in == 1'b1)) & (in_stream_V_data_V_0_state == 2'd3)) | ((in_stream_V_data_V_0_state == 2'd1) & (in_stream_V_data_V_0_ack_out == 1'b1)) | ((in_stream_V_data_V_0_state == 2'd2) & (in_stream_V_data_V_0_vld_in == 1'b1)))) begin
            in_stream_V_data_V_0_state <= 2'd3;
        end else begin
            in_stream_V_data_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        in_stream_V_dest_V_0_state <= 2'd0;
    end else begin
        if ((((in_stream_V_dest_V_0_state == 2'd2) & (in_stream_V_dest_V_0_vld_in == 1'b0)) | ((in_stream_V_dest_V_0_state == 2'd3) & (in_stream_V_dest_V_0_vld_in == 1'b0) & (in_stream_V_dest_V_0_ack_out == 1'b1)))) begin
            in_stream_V_dest_V_0_state <= 2'd2;
        end else if ((((in_stream_V_dest_V_0_state == 2'd1) & (in_stream_V_dest_V_0_ack_out == 1'b0)) | ((in_stream_V_dest_V_0_state == 2'd3) & (in_stream_V_dest_V_0_ack_out == 1'b0) & (in_stream_V_dest_V_0_vld_in == 1'b1)))) begin
            in_stream_V_dest_V_0_state <= 2'd1;
        end else if (((~((in_stream_V_dest_V_0_vld_in == 1'b0) & (in_stream_V_dest_V_0_ack_out == 1'b1)) & ~((in_stream_V_dest_V_0_ack_out == 1'b0) & (in_stream_V_dest_V_0_vld_in == 1'b1)) & (in_stream_V_dest_V_0_state == 2'd3)) | ((in_stream_V_dest_V_0_state == 2'd1) & (in_stream_V_dest_V_0_ack_out == 1'b1)) | ((in_stream_V_dest_V_0_state == 2'd2) & (in_stream_V_dest_V_0_vld_in == 1'b1)))) begin
            in_stream_V_dest_V_0_state <= 2'd3;
        end else begin
            in_stream_V_dest_V_0_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond1_i_i_reg_722_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        calculated_norm_V_reg_374 <= p_Val2_4_7_i_i_fu_716_p2;
    end else if ((~((ap_start == 1'b0) | (n_0_i_i_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        calculated_norm_V_reg_374 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond1_i_i_fu_397_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_i_i_reg_386 <= i_fu_403_p2;
    end else if ((~((ap_start == 1'b0) | (n_0_i_i_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_i_i_reg_386 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        exitcond1_i_i_reg_722 <= exitcond1_i_i_fu_397_p2;
        exitcond1_i_i_reg_722_pp0_iter1_reg <= exitcond1_i_i_reg_722;
    end
end

always @ (posedge ap_clk) begin
    if ((in_stream_V_data_V_0_load_A == 1'b1)) begin
        in_stream_V_data_V_0_payload_A <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((in_stream_V_data_V_0_load_B == 1'b1)) begin
        in_stream_V_data_V_0_payload_B <= in_stream_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond1_i_i_reg_722 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        r_V_2_i_i_reg_740 <= r_V_2_i_i_fu_516_p2;
        r_V_3_i_i_reg_745 <= r_V_3_i_i_fu_538_p2;
        r_V_6_i_i_reg_750 <= r_V_6_i_i_fu_620_p2;
        r_V_7_i_i_reg_755 <= r_V_7_i_i_fu_642_p2;
        tmp1_reg_760[23 : 8] <= tmp1_fu_648_p2[23 : 8];
        tmp4_reg_765[23 : 8] <= tmp4_fu_654_p2[23 : 8];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond1_i_i_fu_397_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_2_cast_i_i_reg_735 <= {{i_i_i_reg_386[6:1]}};
        tmp_2_reg_731 <= tmp_2_fu_409_p1;
    end
end

always @ (*) begin
    if ((exitcond1_i_i_fu_397_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (exitcond1_i_i_reg_722 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_TDATA_blk_n = in_stream_V_data_V_0_state[1'd0];
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond1_i_i_reg_722 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_V_data_V_0_ack_out = 1'b1;
    end else begin
        in_stream_V_data_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((in_stream_V_data_V_0_sel == 1'b1)) begin
        in_stream_V_data_V_0_data_out = in_stream_V_data_V_0_payload_B;
    end else begin
        in_stream_V_data_V_0_data_out = in_stream_V_data_V_0_payload_A;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (exitcond1_i_i_reg_722 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_V_dest_V_0_ack_out = 1'b1;
    end else begin
        in_stream_V_dest_V_0_ack_out = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        n_0_i_i_out_blk_n = n_0_i_i_out_full_n;
    end else begin
        n_0_i_i_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (n_0_i_i_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        n_0_i_i_out_write = 1'b1;
    end else begin
        n_0_i_i_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_0_V_ce0 = 1'b1;
    end else begin
        x_local_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_reg_731 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_0_V_we0 = 1'b1;
    end else begin
        x_local_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_10_V_ce0 = 1'b1;
    end else begin
        x_local_10_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_reg_731 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_10_V_we0 = 1'b1;
    end else begin
        x_local_10_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_11_V_ce0 = 1'b1;
    end else begin
        x_local_11_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_reg_731 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_11_V_we0 = 1'b1;
    end else begin
        x_local_11_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_12_V_ce0 = 1'b1;
    end else begin
        x_local_12_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_reg_731 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_12_V_we0 = 1'b1;
    end else begin
        x_local_12_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_13_V_ce0 = 1'b1;
    end else begin
        x_local_13_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_reg_731 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_13_V_we0 = 1'b1;
    end else begin
        x_local_13_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_14_V_ce0 = 1'b1;
    end else begin
        x_local_14_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_reg_731 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_14_V_we0 = 1'b1;
    end else begin
        x_local_14_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_15_V_ce0 = 1'b1;
    end else begin
        x_local_15_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_reg_731 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_15_V_we0 = 1'b1;
    end else begin
        x_local_15_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_1_V_ce0 = 1'b1;
    end else begin
        x_local_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_reg_731 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_1_V_we0 = 1'b1;
    end else begin
        x_local_1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_2_V_ce0 = 1'b1;
    end else begin
        x_local_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_reg_731 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_2_V_we0 = 1'b1;
    end else begin
        x_local_2_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_3_V_ce0 = 1'b1;
    end else begin
        x_local_3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_reg_731 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_3_V_we0 = 1'b1;
    end else begin
        x_local_3_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_4_V_ce0 = 1'b1;
    end else begin
        x_local_4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_reg_731 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_4_V_we0 = 1'b1;
    end else begin
        x_local_4_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_5_V_ce0 = 1'b1;
    end else begin
        x_local_5_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_reg_731 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_5_V_we0 = 1'b1;
    end else begin
        x_local_5_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_6_V_ce0 = 1'b1;
    end else begin
        x_local_6_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_reg_731 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_6_V_we0 = 1'b1;
    end else begin
        x_local_6_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_7_V_ce0 = 1'b1;
    end else begin
        x_local_7_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_reg_731 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_7_V_we0 = 1'b1;
    end else begin
        x_local_7_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_8_V_ce0 = 1'b1;
    end else begin
        x_local_8_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_reg_731 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_8_V_we0 = 1'b1;
    end else begin
        x_local_8_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_9_V_ce0 = 1'b1;
    end else begin
        x_local_9_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_reg_731 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_local_9_V_we0 = 1'b1;
    end else begin
        x_local_9_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (n_0_i_i_out_full_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (exitcond1_i_i_fu_397_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (exitcond1_i_i_fu_397_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign OP1_V_1_i_i_fu_482_p1 = p_Result_1_i_i_fu_470_p4;

assign OP1_V_2_i_i_fu_512_p1 = p_Result_2_i_i_fu_500_p4;

assign OP1_V_3_i_i_fu_534_p1 = p_Result_3_i_i_fu_522_p4;

assign OP1_V_4_i_i_fu_556_p1 = p_Result_4_i_i_fu_544_p4;

assign OP1_V_5_i_i_fu_586_p1 = p_Result_5_i_i_fu_574_p4;

assign OP1_V_6_i_i_fu_616_p1 = p_Result_6_i_i_fu_604_p4;

assign OP1_V_7_i_i_fu_638_p1 = p_Result_7_i_i_fu_626_p4;

assign OP1_V_i_i_fu_452_p1 = tmp_3_fu_427_p1;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((exitcond1_i_i_reg_722 == 1'd0) & (in_stream_V_data_V_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((exitcond1_i_i_reg_722 == 1'd0) & (in_stream_V_data_V_0_vld_out == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (n_0_i_i_out_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((exitcond1_i_i_reg_722 == 1'd0) & (in_stream_V_data_V_0_vld_out == 1'b0));
end

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_return = calculated_norm_V_reg_374;

assign exitcond1_i_i_fu_397_p2 = ((i_i_i_reg_386 == 7'd98) ? 1'b1 : 1'b0);

assign i_fu_403_p2 = (i_i_i_reg_386 + 7'd1);

assign in_stream_TREADY = in_stream_V_dest_V_0_state[1'd1];

assign in_stream_V_data_V_0_ack_in = in_stream_V_data_V_0_state[1'd1];

assign in_stream_V_data_V_0_load_A = (in_stream_V_data_V_0_state_cmp_full & ~in_stream_V_data_V_0_sel_wr);

assign in_stream_V_data_V_0_load_B = (in_stream_V_data_V_0_state_cmp_full & in_stream_V_data_V_0_sel_wr);

assign in_stream_V_data_V_0_sel = in_stream_V_data_V_0_sel_rd;

assign in_stream_V_data_V_0_state_cmp_full = ((in_stream_V_data_V_0_state != 2'd1) ? 1'b1 : 1'b0);

assign in_stream_V_data_V_0_vld_in = in_stream_TVALID;

assign in_stream_V_data_V_0_vld_out = in_stream_V_data_V_0_state[1'd0];

assign in_stream_V_dest_V_0_vld_in = in_stream_TVALID;

assign n_0_i_i_out_din = n_0_i_i;

assign newIndex1_i_i_fu_433_p1 = tmp_2_cast_i_i_reg_735;

assign p_Result_1_i_i_fu_470_p4 = {{in_stream_V_data_V_0_data_out[15:8]}};

assign p_Result_2_i_i_fu_500_p4 = {{in_stream_V_data_V_0_data_out[23:16]}};

assign p_Result_3_i_i_fu_522_p4 = {{in_stream_V_data_V_0_data_out[31:24]}};

assign p_Result_4_i_i_fu_544_p4 = {{in_stream_V_data_V_0_data_out[39:32]}};

assign p_Result_5_i_i_fu_574_p4 = {{in_stream_V_data_V_0_data_out[47:40]}};

assign p_Result_6_i_i_fu_604_p4 = {{in_stream_V_data_V_0_data_out[55:48]}};

assign p_Result_7_i_i_fu_626_p4 = {{in_stream_V_data_V_0_data_out[63:56]}};

assign p_Val2_4_7_i_i_fu_716_p2 = (tmp_1_fu_710_p2 + calculated_norm_V_reg_374);

assign r_V_1_i_i_fu_486_p0 = OP1_V_1_i_i_fu_482_p1;

assign r_V_1_i_i_fu_486_p1 = OP1_V_1_i_i_fu_482_p1;

assign r_V_1_i_i_fu_486_p2 = ($signed(r_V_1_i_i_fu_486_p0) * $signed(r_V_1_i_i_fu_486_p1));

assign r_V_2_i_i_fu_516_p0 = OP1_V_2_i_i_fu_512_p1;

assign r_V_2_i_i_fu_516_p1 = OP1_V_2_i_i_fu_512_p1;

assign r_V_2_i_i_fu_516_p2 = ($signed(r_V_2_i_i_fu_516_p0) * $signed(r_V_2_i_i_fu_516_p1));

assign r_V_3_i_i_fu_538_p0 = OP1_V_3_i_i_fu_534_p1;

assign r_V_3_i_i_fu_538_p1 = OP1_V_3_i_i_fu_534_p1;

assign r_V_3_i_i_fu_538_p2 = ($signed(r_V_3_i_i_fu_538_p0) * $signed(r_V_3_i_i_fu_538_p1));

assign r_V_4_i_i_fu_560_p0 = OP1_V_4_i_i_fu_556_p1;

assign r_V_4_i_i_fu_560_p1 = OP1_V_4_i_i_fu_556_p1;

assign r_V_4_i_i_fu_560_p2 = ($signed(r_V_4_i_i_fu_560_p0) * $signed(r_V_4_i_i_fu_560_p1));

assign r_V_5_i_i_fu_590_p0 = OP1_V_5_i_i_fu_586_p1;

assign r_V_5_i_i_fu_590_p1 = OP1_V_5_i_i_fu_586_p1;

assign r_V_5_i_i_fu_590_p2 = ($signed(r_V_5_i_i_fu_590_p0) * $signed(r_V_5_i_i_fu_590_p1));

assign r_V_6_i_i_fu_620_p0 = OP1_V_6_i_i_fu_616_p1;

assign r_V_6_i_i_fu_620_p1 = OP1_V_6_i_i_fu_616_p1;

assign r_V_6_i_i_fu_620_p2 = ($signed(r_V_6_i_i_fu_620_p0) * $signed(r_V_6_i_i_fu_620_p1));

assign r_V_7_i_i_fu_642_p0 = OP1_V_7_i_i_fu_638_p1;

assign r_V_7_i_i_fu_642_p1 = OP1_V_7_i_i_fu_638_p1;

assign r_V_7_i_i_fu_642_p2 = ($signed(r_V_7_i_i_fu_642_p0) * $signed(r_V_7_i_i_fu_642_p1));

assign r_V_i_i_fu_456_p0 = OP1_V_i_i_fu_452_p1;

assign r_V_i_i_fu_456_p1 = OP1_V_i_i_fu_452_p1;

assign r_V_i_i_fu_456_p2 = ($signed(r_V_i_i_fu_456_p0) * $signed(r_V_i_i_fu_456_p1));

assign tmp1_fu_648_p2 = (tmp_9_1_i_i_fu_492_p3 + tmp_9_i_i_fu_462_p3);

assign tmp2_fu_688_p2 = (tmp_9_3_i_i_fu_667_p3 + tmp_9_2_i_i_fu_660_p3);

assign tmp3_fu_705_p2 = (tmp4_reg_765 + tmp5_fu_699_p2);

assign tmp4_fu_654_p2 = (tmp_9_5_i_i_fu_596_p3 + tmp_9_4_i_i_fu_566_p3);

assign tmp5_fu_699_p2 = (tmp_9_7_i_i_fu_681_p3 + tmp_9_6_i_i_fu_674_p3);

assign tmp_1_fu_710_p2 = (tmp_fu_694_p2 + tmp3_fu_705_p2);

assign tmp_2_fu_409_p1 = i_i_i_reg_386[0:0];

assign tmp_3_fu_427_p1 = in_stream_V_data_V_0_data_out[7:0];

assign tmp_9_1_i_i_fu_492_p3 = {{r_V_1_i_i_fu_486_p2}, {8'd0}};

assign tmp_9_2_i_i_fu_660_p3 = {{r_V_2_i_i_reg_740}, {8'd0}};

assign tmp_9_3_i_i_fu_667_p3 = {{r_V_3_i_i_reg_745}, {8'd0}};

assign tmp_9_4_i_i_fu_566_p3 = {{r_V_4_i_i_fu_560_p2}, {8'd0}};

assign tmp_9_5_i_i_fu_596_p3 = {{r_V_5_i_i_fu_590_p2}, {8'd0}};

assign tmp_9_6_i_i_fu_674_p3 = {{r_V_6_i_i_reg_750}, {8'd0}};

assign tmp_9_7_i_i_fu_681_p3 = {{r_V_7_i_i_reg_755}, {8'd0}};

assign tmp_9_i_i_fu_462_p3 = {{r_V_i_i_fu_456_p2}, {8'd0}};

assign tmp_fu_694_p2 = (tmp1_reg_760 + tmp2_fu_688_p2);

assign x_local_0_V_address0 = newIndex1_i_i_fu_433_p1;

assign x_local_0_V_d0 = tmp_3_fu_427_p1;

assign x_local_10_V_address0 = newIndex1_i_i_fu_433_p1;

assign x_local_10_V_d0 = {{in_stream_V_data_V_0_data_out[23:16]}};

assign x_local_11_V_address0 = newIndex1_i_i_fu_433_p1;

assign x_local_11_V_d0 = {{in_stream_V_data_V_0_data_out[31:24]}};

assign x_local_12_V_address0 = newIndex1_i_i_fu_433_p1;

assign x_local_12_V_d0 = {{in_stream_V_data_V_0_data_out[39:32]}};

assign x_local_13_V_address0 = newIndex1_i_i_fu_433_p1;

assign x_local_13_V_d0 = {{in_stream_V_data_V_0_data_out[47:40]}};

assign x_local_14_V_address0 = newIndex1_i_i_fu_433_p1;

assign x_local_14_V_d0 = {{in_stream_V_data_V_0_data_out[55:48]}};

assign x_local_15_V_address0 = newIndex1_i_i_fu_433_p1;

assign x_local_15_V_d0 = {{in_stream_V_data_V_0_data_out[63:56]}};

assign x_local_1_V_address0 = newIndex1_i_i_fu_433_p1;

assign x_local_1_V_d0 = {{in_stream_V_data_V_0_data_out[15:8]}};

assign x_local_2_V_address0 = newIndex1_i_i_fu_433_p1;

assign x_local_2_V_d0 = {{in_stream_V_data_V_0_data_out[23:16]}};

assign x_local_3_V_address0 = newIndex1_i_i_fu_433_p1;

assign x_local_3_V_d0 = {{in_stream_V_data_V_0_data_out[31:24]}};

assign x_local_4_V_address0 = newIndex1_i_i_fu_433_p1;

assign x_local_4_V_d0 = {{in_stream_V_data_V_0_data_out[39:32]}};

assign x_local_5_V_address0 = newIndex1_i_i_fu_433_p1;

assign x_local_5_V_d0 = {{in_stream_V_data_V_0_data_out[47:40]}};

assign x_local_6_V_address0 = newIndex1_i_i_fu_433_p1;

assign x_local_6_V_d0 = {{in_stream_V_data_V_0_data_out[55:48]}};

assign x_local_7_V_address0 = newIndex1_i_i_fu_433_p1;

assign x_local_7_V_d0 = {{in_stream_V_data_V_0_data_out[63:56]}};

assign x_local_8_V_address0 = newIndex1_i_i_fu_433_p1;

assign x_local_8_V_d0 = tmp_3_fu_427_p1;

assign x_local_9_V_address0 = newIndex1_i_i_fu_433_p1;

assign x_local_9_V_d0 = {{in_stream_V_data_V_0_data_out[15:8]}};

always @ (posedge ap_clk) begin
    tmp1_reg_760[7:0] <= 8'b00000000;
    tmp4_reg_765[7:0] <= 8'b00000000;
end

endmodule //load_and_calc_norm61
