// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module load_data48 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        m_axi_x_V_AWVALID,
        m_axi_x_V_AWREADY,
        m_axi_x_V_AWADDR,
        m_axi_x_V_AWID,
        m_axi_x_V_AWLEN,
        m_axi_x_V_AWSIZE,
        m_axi_x_V_AWBURST,
        m_axi_x_V_AWLOCK,
        m_axi_x_V_AWCACHE,
        m_axi_x_V_AWPROT,
        m_axi_x_V_AWQOS,
        m_axi_x_V_AWREGION,
        m_axi_x_V_AWUSER,
        m_axi_x_V_WVALID,
        m_axi_x_V_WREADY,
        m_axi_x_V_WDATA,
        m_axi_x_V_WSTRB,
        m_axi_x_V_WLAST,
        m_axi_x_V_WID,
        m_axi_x_V_WUSER,
        m_axi_x_V_ARVALID,
        m_axi_x_V_ARREADY,
        m_axi_x_V_ARADDR,
        m_axi_x_V_ARID,
        m_axi_x_V_ARLEN,
        m_axi_x_V_ARSIZE,
        m_axi_x_V_ARBURST,
        m_axi_x_V_ARLOCK,
        m_axi_x_V_ARCACHE,
        m_axi_x_V_ARPROT,
        m_axi_x_V_ARQOS,
        m_axi_x_V_ARREGION,
        m_axi_x_V_ARUSER,
        m_axi_x_V_RVALID,
        m_axi_x_V_RREADY,
        m_axi_x_V_RDATA,
        m_axi_x_V_RLAST,
        m_axi_x_V_RID,
        m_axi_x_V_RUSER,
        m_axi_x_V_RRESP,
        m_axi_x_V_BVALID,
        m_axi_x_V_BREADY,
        m_axi_x_V_BRESP,
        m_axi_x_V_BID,
        m_axi_x_V_BUSER,
        x_V_offset,
        x_local_0_V_address0,
        x_local_0_V_ce0,
        x_local_0_V_we0,
        x_local_0_V_d0,
        x_local_1_V_address0,
        x_local_1_V_ce0,
        x_local_1_V_we0,
        x_local_1_V_d0,
        x_local_2_V_address0,
        x_local_2_V_ce0,
        x_local_2_V_we0,
        x_local_2_V_d0,
        x_local_3_V_address0,
        x_local_3_V_ce0,
        x_local_3_V_we0,
        x_local_3_V_d0,
        x_local_4_V_address0,
        x_local_4_V_ce0,
        x_local_4_V_we0,
        x_local_4_V_d0,
        x_local_5_V_address0,
        x_local_5_V_ce0,
        x_local_5_V_we0,
        x_local_5_V_d0,
        x_local_6_V_address0,
        x_local_6_V_ce0,
        x_local_6_V_we0,
        x_local_6_V_d0,
        x_local_7_V_address0,
        x_local_7_V_ce0,
        x_local_7_V_we0,
        x_local_7_V_d0,
        x_local_8_V_address0,
        x_local_8_V_ce0,
        x_local_8_V_we0,
        x_local_8_V_d0,
        x_local_9_V_address0,
        x_local_9_V_ce0,
        x_local_9_V_we0,
        x_local_9_V_d0,
        x_local_10_V_address0,
        x_local_10_V_ce0,
        x_local_10_V_we0,
        x_local_10_V_d0,
        x_local_11_V_address0,
        x_local_11_V_ce0,
        x_local_11_V_we0,
        x_local_11_V_d0,
        x_local_12_V_address0,
        x_local_12_V_ce0,
        x_local_12_V_we0,
        x_local_12_V_d0,
        x_local_13_V_address0,
        x_local_13_V_ce0,
        x_local_13_V_we0,
        x_local_13_V_d0,
        x_local_14_V_address0,
        x_local_14_V_ce0,
        x_local_14_V_we0,
        x_local_14_V_d0,
        x_local_15_V_address0,
        x_local_15_V_ce0,
        x_local_15_V_we0,
        x_local_15_V_d0,
        x_norm_in_V,
        x_norm_in_V_out_din,
        x_norm_in_V_out_full_n,
        x_norm_in_V_out_write
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_pp0_stage0 = 9'd128;
parameter    ap_ST_fsm_state11 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   m_axi_x_V_AWVALID;
input   m_axi_x_V_AWREADY;
output  [31:0] m_axi_x_V_AWADDR;
output  [0:0] m_axi_x_V_AWID;
output  [31:0] m_axi_x_V_AWLEN;
output  [2:0] m_axi_x_V_AWSIZE;
output  [1:0] m_axi_x_V_AWBURST;
output  [1:0] m_axi_x_V_AWLOCK;
output  [3:0] m_axi_x_V_AWCACHE;
output  [2:0] m_axi_x_V_AWPROT;
output  [3:0] m_axi_x_V_AWQOS;
output  [3:0] m_axi_x_V_AWREGION;
output  [0:0] m_axi_x_V_AWUSER;
output   m_axi_x_V_WVALID;
input   m_axi_x_V_WREADY;
output  [63:0] m_axi_x_V_WDATA;
output  [7:0] m_axi_x_V_WSTRB;
output   m_axi_x_V_WLAST;
output  [0:0] m_axi_x_V_WID;
output  [0:0] m_axi_x_V_WUSER;
output   m_axi_x_V_ARVALID;
input   m_axi_x_V_ARREADY;
output  [31:0] m_axi_x_V_ARADDR;
output  [0:0] m_axi_x_V_ARID;
output  [31:0] m_axi_x_V_ARLEN;
output  [2:0] m_axi_x_V_ARSIZE;
output  [1:0] m_axi_x_V_ARBURST;
output  [1:0] m_axi_x_V_ARLOCK;
output  [3:0] m_axi_x_V_ARCACHE;
output  [2:0] m_axi_x_V_ARPROT;
output  [3:0] m_axi_x_V_ARQOS;
output  [3:0] m_axi_x_V_ARREGION;
output  [0:0] m_axi_x_V_ARUSER;
input   m_axi_x_V_RVALID;
output   m_axi_x_V_RREADY;
input  [63:0] m_axi_x_V_RDATA;
input   m_axi_x_V_RLAST;
input  [0:0] m_axi_x_V_RID;
input  [0:0] m_axi_x_V_RUSER;
input  [1:0] m_axi_x_V_RRESP;
input   m_axi_x_V_BVALID;
output   m_axi_x_V_BREADY;
input  [1:0] m_axi_x_V_BRESP;
input  [0:0] m_axi_x_V_BID;
input  [0:0] m_axi_x_V_BUSER;
input  [31:0] x_V_offset;
output  [5:0] x_local_0_V_address0;
output   x_local_0_V_ce0;
output   x_local_0_V_we0;
output  [7:0] x_local_0_V_d0;
output  [5:0] x_local_1_V_address0;
output   x_local_1_V_ce0;
output   x_local_1_V_we0;
output  [7:0] x_local_1_V_d0;
output  [5:0] x_local_2_V_address0;
output   x_local_2_V_ce0;
output   x_local_2_V_we0;
output  [7:0] x_local_2_V_d0;
output  [5:0] x_local_3_V_address0;
output   x_local_3_V_ce0;
output   x_local_3_V_we0;
output  [7:0] x_local_3_V_d0;
output  [5:0] x_local_4_V_address0;
output   x_local_4_V_ce0;
output   x_local_4_V_we0;
output  [7:0] x_local_4_V_d0;
output  [5:0] x_local_5_V_address0;
output   x_local_5_V_ce0;
output   x_local_5_V_we0;
output  [7:0] x_local_5_V_d0;
output  [5:0] x_local_6_V_address0;
output   x_local_6_V_ce0;
output   x_local_6_V_we0;
output  [7:0] x_local_6_V_d0;
output  [5:0] x_local_7_V_address0;
output   x_local_7_V_ce0;
output   x_local_7_V_we0;
output  [7:0] x_local_7_V_d0;
output  [5:0] x_local_8_V_address0;
output   x_local_8_V_ce0;
output   x_local_8_V_we0;
output  [7:0] x_local_8_V_d0;
output  [5:0] x_local_9_V_address0;
output   x_local_9_V_ce0;
output   x_local_9_V_we0;
output  [7:0] x_local_9_V_d0;
output  [5:0] x_local_10_V_address0;
output   x_local_10_V_ce0;
output   x_local_10_V_we0;
output  [7:0] x_local_10_V_d0;
output  [5:0] x_local_11_V_address0;
output   x_local_11_V_ce0;
output   x_local_11_V_we0;
output  [7:0] x_local_11_V_d0;
output  [5:0] x_local_12_V_address0;
output   x_local_12_V_ce0;
output   x_local_12_V_we0;
output  [7:0] x_local_12_V_d0;
output  [5:0] x_local_13_V_address0;
output   x_local_13_V_ce0;
output   x_local_13_V_we0;
output  [7:0] x_local_13_V_d0;
output  [5:0] x_local_14_V_address0;
output   x_local_14_V_ce0;
output   x_local_14_V_we0;
output  [7:0] x_local_14_V_d0;
output  [5:0] x_local_15_V_address0;
output   x_local_15_V_ce0;
output   x_local_15_V_we0;
output  [7:0] x_local_15_V_d0;
input  [23:0] x_norm_in_V;
output  [23:0] x_norm_in_V_out_din;
input   x_norm_in_V_out_full_n;
output   x_norm_in_V_out_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_x_V_ARVALID;
reg m_axi_x_V_RREADY;
reg x_local_0_V_ce0;
reg x_local_0_V_we0;
reg x_local_1_V_ce0;
reg x_local_1_V_we0;
reg x_local_2_V_ce0;
reg x_local_2_V_we0;
reg x_local_3_V_ce0;
reg x_local_3_V_we0;
reg x_local_4_V_ce0;
reg x_local_4_V_we0;
reg x_local_5_V_ce0;
reg x_local_5_V_we0;
reg x_local_6_V_ce0;
reg x_local_6_V_we0;
reg x_local_7_V_ce0;
reg x_local_7_V_we0;
reg x_local_8_V_ce0;
reg x_local_8_V_we0;
reg x_local_9_V_ce0;
reg x_local_9_V_we0;
reg x_local_10_V_ce0;
reg x_local_10_V_we0;
reg x_local_11_V_ce0;
reg x_local_11_V_we0;
reg x_local_12_V_ce0;
reg x_local_12_V_we0;
reg x_local_13_V_ce0;
reg x_local_13_V_we0;
reg x_local_14_V_ce0;
reg x_local_14_V_we0;
reg x_local_15_V_ce0;
reg x_local_15_V_we0;
reg x_norm_in_V_out_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    x_V_blk_n_AR;
reg    x_V_blk_n_R;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg    x_norm_in_V_out_blk_n;
wire    ap_CS_fsm_state7;
reg   [6:0] i_i_i_reg_370;
reg    ap_block_state1;
reg    ap_sig_ioackin_m_axi_x_V_ARREADY;
wire   [0:0] exitcond1_i_i_fu_402_p2;
wire    ap_block_state8_pp0_stage0_iter0;
reg    ap_block_state9_pp0_stage0_iter1;
wire    ap_block_state10_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [6:0] i_fu_408_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] tmp_fu_414_p1;
reg   [0:0] tmp_reg_536;
reg   [0:0] tmp_reg_536_pp0_iter1_reg;
reg   [5:0] tmp_3_cast_i_i_reg_540;
reg   [5:0] tmp_3_cast_i_i_reg_540_pp0_iter1_reg;
wire   [7:0] tmp_1_fu_428_p1;
reg   [7:0] tmp_1_reg_545;
reg   [7:0] p_Result_1_i_i_reg_551;
reg   [7:0] p_Result_2_i_i_reg_557;
reg   [7:0] p_Result_3_i_i_reg_563;
reg   [7:0] p_Result_4_i_i_reg_569;
reg   [7:0] p_Result_5_i_i_reg_575;
reg   [7:0] p_Result_6_i_i_reg_581;
reg   [7:0] p_Result_7_i_i_reg_587;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state8;
reg    ap_enable_reg_pp0_iter2;
wire   [63:0] newIndex1_i_i_fu_502_p1;
wire   [63:0] sext_fu_391_p1;
reg    ap_reg_ioackin_m_axi_x_V_ARREADY;
wire   [28:0] x_V_offset1_fu_381_p4;
wire    ap_CS_fsm_state11;
reg   [8:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_472;
reg    ap_condition_239;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 9'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_reg_ioackin_m_axi_x_V_ARREADY = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state11)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state8) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((x_norm_in_V_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state8)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state8);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((x_norm_in_V_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ioackin_m_axi_x_V_ARREADY <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state1)) begin
            if ((1'b1 == ap_condition_239)) begin
                ap_reg_ioackin_m_axi_x_V_ARREADY <= 1'b0;
            end else if ((1'b1 == ap_condition_472)) begin
                ap_reg_ioackin_m_axi_x_V_ARREADY <= 1'b1;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_i_i_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_i_i_reg_370 <= i_fu_408_p2;
    end else if (((x_norm_in_V_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        i_i_i_reg_370 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_Result_1_i_i_reg_551 <= {{m_axi_x_V_RDATA[15:8]}};
        p_Result_2_i_i_reg_557 <= {{m_axi_x_V_RDATA[23:16]}};
        p_Result_3_i_i_reg_563 <= {{m_axi_x_V_RDATA[31:24]}};
        p_Result_4_i_i_reg_569 <= {{m_axi_x_V_RDATA[39:32]}};
        p_Result_5_i_i_reg_575 <= {{m_axi_x_V_RDATA[47:40]}};
        p_Result_6_i_i_reg_581 <= {{m_axi_x_V_RDATA[55:48]}};
        p_Result_7_i_i_reg_587 <= {{m_axi_x_V_RDATA[63:56]}};
        tmp_1_reg_545 <= tmp_1_fu_428_p1;
        tmp_3_cast_i_i_reg_540_pp0_iter1_reg <= tmp_3_cast_i_i_reg_540;
        tmp_reg_536_pp0_iter1_reg <= tmp_reg_536;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_i_i_fu_402_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_3_cast_i_i_reg_540 <= {{i_i_i_reg_370[6:1]}};
        tmp_reg_536 <= tmp_fu_414_p1;
    end
end

always @ (*) begin
    if ((exitcond1_i_i_fu_402_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state8 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state8 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((ap_reg_ioackin_m_axi_x_V_ARREADY == 1'b0)) begin
        ap_sig_ioackin_m_axi_x_V_ARREADY = m_axi_x_V_ARREADY;
    end else begin
        ap_sig_ioackin_m_axi_x_V_ARREADY = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (ap_reg_ioackin_m_axi_x_V_ARREADY == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_x_V_ARVALID = 1'b1;
    end else begin
        m_axi_x_V_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        m_axi_x_V_RREADY = 1'b1;
    end else begin
        m_axi_x_V_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        x_V_blk_n_AR = m_axi_x_V_ARREADY;
    end else begin
        x_V_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_V_blk_n_R = m_axi_x_V_RVALID;
    end else begin
        x_V_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_0_V_ce0 = 1'b1;
    end else begin
        x_local_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_536_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_0_V_we0 = 1'b1;
    end else begin
        x_local_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_10_V_ce0 = 1'b1;
    end else begin
        x_local_10_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_536_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_10_V_we0 = 1'b1;
    end else begin
        x_local_10_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_11_V_ce0 = 1'b1;
    end else begin
        x_local_11_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_536_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_11_V_we0 = 1'b1;
    end else begin
        x_local_11_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_12_V_ce0 = 1'b1;
    end else begin
        x_local_12_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_536_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_12_V_we0 = 1'b1;
    end else begin
        x_local_12_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_13_V_ce0 = 1'b1;
    end else begin
        x_local_13_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_536_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_13_V_we0 = 1'b1;
    end else begin
        x_local_13_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_14_V_ce0 = 1'b1;
    end else begin
        x_local_14_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_536_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_14_V_we0 = 1'b1;
    end else begin
        x_local_14_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_15_V_ce0 = 1'b1;
    end else begin
        x_local_15_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_536_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_15_V_we0 = 1'b1;
    end else begin
        x_local_15_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_1_V_ce0 = 1'b1;
    end else begin
        x_local_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_536_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_1_V_we0 = 1'b1;
    end else begin
        x_local_1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_2_V_ce0 = 1'b1;
    end else begin
        x_local_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_536_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_2_V_we0 = 1'b1;
    end else begin
        x_local_2_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_3_V_ce0 = 1'b1;
    end else begin
        x_local_3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_536_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_3_V_we0 = 1'b1;
    end else begin
        x_local_3_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_4_V_ce0 = 1'b1;
    end else begin
        x_local_4_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_536_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_4_V_we0 = 1'b1;
    end else begin
        x_local_4_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_5_V_ce0 = 1'b1;
    end else begin
        x_local_5_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_536_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_5_V_we0 = 1'b1;
    end else begin
        x_local_5_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_6_V_ce0 = 1'b1;
    end else begin
        x_local_6_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_536_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_6_V_we0 = 1'b1;
    end else begin
        x_local_6_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_7_V_ce0 = 1'b1;
    end else begin
        x_local_7_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_536_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_7_V_we0 = 1'b1;
    end else begin
        x_local_7_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_8_V_ce0 = 1'b1;
    end else begin
        x_local_8_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_536_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_8_V_we0 = 1'b1;
    end else begin
        x_local_8_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_9_V_ce0 = 1'b1;
    end else begin
        x_local_9_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_reg_536_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        x_local_9_V_we0 = 1'b1;
    end else begin
        x_local_9_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        x_norm_in_V_out_blk_n = x_norm_in_V_out_full_n;
    end else begin
        x_norm_in_V_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((x_norm_in_V_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        x_norm_in_V_out_write = 1'b1;
    end else begin
        x_norm_in_V_out_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_sig_ioackin_m_axi_x_V_ARREADY == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((x_norm_in_V_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (exitcond1_i_i_fu_402_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (exitcond1_i_i_fu_402_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((m_axi_x_V_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((m_axi_x_V_RVALID == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state10_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_pp0_stage0_iter1 = (m_axi_x_V_RVALID == 1'b0);
end

always @ (*) begin
    ap_condition_239 = ~((ap_sig_ioackin_m_axi_x_V_ARREADY == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_condition_472 = (~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (m_axi_x_V_ARREADY == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign exitcond1_i_i_fu_402_p2 = ((i_i_i_reg_370 == 7'd98) ? 1'b1 : 1'b0);

assign i_fu_408_p2 = (i_i_i_reg_370 + 7'd1);

assign m_axi_x_V_ARADDR = sext_fu_391_p1;

assign m_axi_x_V_ARBURST = 2'd0;

assign m_axi_x_V_ARCACHE = 4'd0;

assign m_axi_x_V_ARID = 1'd0;

assign m_axi_x_V_ARLEN = 32'd98;

assign m_axi_x_V_ARLOCK = 2'd0;

assign m_axi_x_V_ARPROT = 3'd0;

assign m_axi_x_V_ARQOS = 4'd0;

assign m_axi_x_V_ARREGION = 4'd0;

assign m_axi_x_V_ARSIZE = 3'd0;

assign m_axi_x_V_ARUSER = 1'd0;

assign m_axi_x_V_AWADDR = 32'd0;

assign m_axi_x_V_AWBURST = 2'd0;

assign m_axi_x_V_AWCACHE = 4'd0;

assign m_axi_x_V_AWID = 1'd0;

assign m_axi_x_V_AWLEN = 32'd0;

assign m_axi_x_V_AWLOCK = 2'd0;

assign m_axi_x_V_AWPROT = 3'd0;

assign m_axi_x_V_AWQOS = 4'd0;

assign m_axi_x_V_AWREGION = 4'd0;

assign m_axi_x_V_AWSIZE = 3'd0;

assign m_axi_x_V_AWUSER = 1'd0;

assign m_axi_x_V_AWVALID = 1'b0;

assign m_axi_x_V_BREADY = 1'b0;

assign m_axi_x_V_WDATA = 64'd0;

assign m_axi_x_V_WID = 1'd0;

assign m_axi_x_V_WLAST = 1'b0;

assign m_axi_x_V_WSTRB = 8'd0;

assign m_axi_x_V_WUSER = 1'd0;

assign m_axi_x_V_WVALID = 1'b0;

assign newIndex1_i_i_fu_502_p1 = tmp_3_cast_i_i_reg_540_pp0_iter1_reg;

assign sext_fu_391_p1 = x_V_offset1_fu_381_p4;

assign tmp_1_fu_428_p1 = m_axi_x_V_RDATA[7:0];

assign tmp_fu_414_p1 = i_i_i_reg_370[0:0];

assign x_V_offset1_fu_381_p4 = {{x_V_offset[31:3]}};

assign x_local_0_V_address0 = newIndex1_i_i_fu_502_p1;

assign x_local_0_V_d0 = tmp_1_reg_545;

assign x_local_10_V_address0 = newIndex1_i_i_fu_502_p1;

assign x_local_10_V_d0 = p_Result_2_i_i_reg_557;

assign x_local_11_V_address0 = newIndex1_i_i_fu_502_p1;

assign x_local_11_V_d0 = p_Result_3_i_i_reg_563;

assign x_local_12_V_address0 = newIndex1_i_i_fu_502_p1;

assign x_local_12_V_d0 = p_Result_4_i_i_reg_569;

assign x_local_13_V_address0 = newIndex1_i_i_fu_502_p1;

assign x_local_13_V_d0 = p_Result_5_i_i_reg_575;

assign x_local_14_V_address0 = newIndex1_i_i_fu_502_p1;

assign x_local_14_V_d0 = p_Result_6_i_i_reg_581;

assign x_local_15_V_address0 = newIndex1_i_i_fu_502_p1;

assign x_local_15_V_d0 = p_Result_7_i_i_reg_587;

assign x_local_1_V_address0 = newIndex1_i_i_fu_502_p1;

assign x_local_1_V_d0 = p_Result_1_i_i_reg_551;

assign x_local_2_V_address0 = newIndex1_i_i_fu_502_p1;

assign x_local_2_V_d0 = p_Result_2_i_i_reg_557;

assign x_local_3_V_address0 = newIndex1_i_i_fu_502_p1;

assign x_local_3_V_d0 = p_Result_3_i_i_reg_563;

assign x_local_4_V_address0 = newIndex1_i_i_fu_502_p1;

assign x_local_4_V_d0 = p_Result_4_i_i_reg_569;

assign x_local_5_V_address0 = newIndex1_i_i_fu_502_p1;

assign x_local_5_V_d0 = p_Result_5_i_i_reg_575;

assign x_local_6_V_address0 = newIndex1_i_i_fu_502_p1;

assign x_local_6_V_d0 = p_Result_6_i_i_reg_581;

assign x_local_7_V_address0 = newIndex1_i_i_fu_502_p1;

assign x_local_7_V_d0 = p_Result_7_i_i_reg_587;

assign x_local_8_V_address0 = newIndex1_i_i_fu_502_p1;

assign x_local_8_V_d0 = tmp_1_reg_545;

assign x_local_9_V_address0 = newIndex1_i_i_fu_502_p1;

assign x_local_9_V_d0 = p_Result_1_i_i_reg_551;

assign x_norm_in_V_out_din = x_norm_in_V;

endmodule //load_data48
