import re
import os
import sys

# ---------------------------------------------------------
# CONFIGURATION
# ---------------------------------------------------------
INPUT_FILENAME = "svs.h"
OUTPUT_FILENAME = "sv_norms.h"
IMG_SIZE = 784  # This must remain fixed for your image size

def generate_norms():
    print(f"--- Starting generation of {OUTPUT_FILENAME} ---")

    if not os.path.exists(INPUT_FILENAME):
        print(f"[ERROR] '{INPUT_FILENAME}' not found.")
        sys.exit(1)

    try:
        with open(INPUT_FILENAME, 'r') as f:
            content = f.read()

        # 1. Isolate the Array Content
        # We find the first '{' and the last '}' and only look inside there.
        start_idx = content.find('{')
        end_idx = content.rfind('}')

        if start_idx == -1 or end_idx == -1:
            print("[ERROR] Could not find curly braces { } containing data in svs.h")
            sys.exit(1)

        # Extract only the data block
        data_block = content[start_idx+1 : end_idx]

        # 2. Parse Numbers (Robust Regex)
        # Supports: -0.5, 12, 5.0, 1.2e-5, -3E+2
        pattern = r"[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?"
        matches = re.findall(pattern, data_block)
        
        # Convert to floats
        sv_data = [float(x) for x in matches]
        total_found = len(sv_data)

        # 3. Auto-Detect Number of Support Vectors
        if total_found % IMG_SIZE != 0:
            print(f"\n[WARNING] Found {total_found} numbers, which is not divisible by {IMG_SIZE}.")
            print("The array might be incomplete or contain comments with numbers.")
            print(f"Remainder: {total_found % IMG_SIZE}")
            # Proceeding anyway might be risky, but we'll truncate to safety
        
        num_svs_detected = total_found // IMG_SIZE
        print(f"Detected {num_svs_detected} Support Vectors (Total elements: {total_found})")

        if num_svs_detected == 0:
            print("[ERROR] No valid data found inside braces.")
            sys.exit(1)

        # 4. Calculate Norms
        norms = []
        print("Calculating squared norms...")
        for i in range(num_svs_detected):
            start = i * IMG_SIZE
            end = start + IMG_SIZE
            vector = sv_data[start:end]
            
            # Sum of squares
            sq_sum = sum(x*x for x in vector)
            norms.append(sq_sum)

        # 5. Write Output
        with open(OUTPUT_FILENAME, 'w') as f:
            f.write(f"// Automatically generated by generate_norms.py\n")
            f.write(f"#ifndef SV_NORMS_H\n")
            f.write(f"#define SV_NORMS_H\n\n")
            f.write(f"#include \"ap_fixed.h\"\n\n")
            f.write(f"// Detected Dimensions: [{num_svs_detected}]\n")
            # Using ap_fixed<32,16> to be safe against overflow
            f.write(f"const ap_fixed<32,16> sv_norms[{num_svs_detected}] = {{\n")
            
            for i, val in enumerate(norms):
                f.write(f"    {val:.6f}")
                if i < num_svs_detected - 1:
                    f.write(", ")
                if (i + 1) % 8 == 0:
                    f.write("\n")
            
            f.write("\n};\n\n")
            f.write("#endif\n")

        print(f"\n[SUCCESS] Generated '{OUTPUT_FILENAME}' with {num_svs_detected} norms.")

    except Exception as e:
        print(f"\n[CRITICAL ERROR] {e}")
        sys.exit(1)

if __name__ == "__main__":
    generate_norms()