// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_classify (
hls::stream<struct ap_axiu<64, 1, 1, 1 > > (&in_stream),
hls::stream<struct result_pkt > (&out_stream),
int num_images);
