// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __classify_alphas_V_6_H__
#define __classify_alphas_V_6_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct classify_alphas_V_6_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 6;
  static const unsigned AddressRange = 20;
  static const unsigned AddressWidth = 5;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(classify_alphas_V_6_ram) {
        ram[0] = "0b110010";
        ram[1] = "0b111111";
        ram[2] = "0b000000";
        ram[3] = "0b111000";
        ram[4] = "0b111001";
        ram[5] = "0b111100";
        ram[6] = "0b111111";
        ram[7] = "0b111100";
        ram[8] = "0b111111";
        ram[9] = "0b000000";
        ram[10] = "0b110101";
        ram[11] = "0b111110";
        ram[12] = "0b111110";
        ram[13] = "0b010000";
        ram[14] = "0b000011";
        ram[15] = "0b000010";
        ram[16] = "0b001001";
        ram[17] = "0b010010";
        ram[18] = "0b001101";
        ram[19] = "0b000010";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(classify_alphas_V_6) {


static const unsigned DataWidth = 6;
static const unsigned AddressRange = 20;
static const unsigned AddressWidth = 5;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


classify_alphas_V_6_ram* meminst;


SC_CTOR(classify_alphas_V_6) {
meminst = new classify_alphas_V_6_ram("classify_alphas_V_6_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~classify_alphas_V_6() {
    delete meminst;
}


};//endmodule
#endif
