// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __compute_class_sv_Ngs_H__
#define __compute_class_sv_Ngs_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct compute_class_sv_Ngs_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 29;
  static const unsigned AddressRange = 10;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(compute_class_sv_Ngs_ram) {
        ram[0] = "0b00001011101001100000000000000";
        ram[1] = "0b00111110110000100000000000000";
        ram[2] = "0b10000111111101100000000000000";
        ram[3] = "0b01010000001110100000000000000";
        ram[4] = "0b00010011000101000000000000000";
        ram[5] = "0b00000111011110100000000000000";
        ram[6] = "0b00100011000011100000000000000";
        ram[7] = "0b00011100011011000000000000000";
        ram[8] = "0b10001110110110100000000000000";
        ram[9] = "0b00001001111011000000000000000";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(compute_class_sv_Ngs) {


static const unsigned DataWidth = 29;
static const unsigned AddressRange = 10;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


compute_class_sv_Ngs_ram* meminst;


SC_CTOR(compute_class_sv_Ngs) {
meminst = new compute_class_sv_Ngs_ram("compute_class_sv_Ngs_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~compute_class_sv_Ngs() {
    delete meminst;
}


};//endmodule
#endif
