// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __compute_and_outpu6jw_H__
#define __compute_and_outpu6jw_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct compute_and_outpu6jw_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 26;
  static const unsigned AddressRange = 12;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(compute_and_outpu6jw_ram) {
        ram[0] = "0b01100010100000000000000000";
        ram[1] = "0b01000001000000000000000000";
        ram[2] = "0b01000010111000000000000000";
        ram[3] = "0b11101110111000000000000000";
        ram[4] = "0b01011101011000000000000000";
        ram[5] = "0b00110101101000000000000000";
        ram[6] = "0b01101001010000000000000000";
        ram[7] = "0b01001111111100000000000000";
        ram[8] = "0b11100101000100000000000000";
        ram[9] = "0b01000001010100000000000000";
        ram[10] = "0b00000000000000000000000000";
        ram[11] = "0b00000000000000000000000000";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(compute_and_outpu6jw) {


static const unsigned DataWidth = 26;
static const unsigned AddressRange = 12;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


compute_and_outpu6jw_ram* meminst;


SC_CTOR(compute_and_outpu6jw) {
meminst = new compute_and_outpu6jw_ram("compute_and_outpu6jw_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~compute_and_outpu6jw() {
    delete meminst;
}


};//endmodule
#endif
