// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dataflow_in_loop_HH_
#define _dataflow_in_loop_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "load_and_calc_norm51.h"
#include "compute_and_output.h"
#include "dataflow_in_loop_bAo.h"
#include "fifo_w31_d2_A.h"
#include "fifo_w32_d2_A.h"
#include "fifo_w24_d2_A.h"

namespace ap_rtl {

struct dataflow_in_loop : public sc_module {
    // Port declarations 26
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<64> > in_stream_TDATA;
    sc_in< sc_lv<8> > in_stream_TKEEP;
    sc_in< sc_lv<8> > in_stream_TSTRB;
    sc_in< sc_lv<1> > in_stream_TUSER;
    sc_in< sc_lv<1> > in_stream_TLAST;
    sc_in< sc_lv<1> > in_stream_TID;
    sc_in< sc_lv<1> > in_stream_TDEST;
    sc_out< sc_lv<32> > out_stream_TDATA;
    sc_out< sc_lv<1> > out_stream_TKEEP;
    sc_out< sc_lv<1> > out_stream_TSTRB;
    sc_out< sc_lv<1> > out_stream_TLAST;
    sc_in< sc_lv<31> > n;
    sc_in< sc_lv<32> > num_images;
    sc_in< sc_logic > in_stream_TVALID;
    sc_out< sc_logic > in_stream_TREADY;
    sc_in< sc_logic > n_ap_vld;
    sc_in< sc_logic > num_images_ap_vld;
    sc_out< sc_logic > out_stream_TVALID;
    sc_in< sc_logic > out_stream_TREADY;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > ap_idle;
    sc_in< sc_logic > ap_continue;
    sc_signal< sc_logic > ap_var_for_const3;
    sc_signal< sc_logic > ap_var_for_const1;
    sc_signal< sc_lv<128> > ap_var_for_const2;
    sc_signal< sc_lv<5> > ap_var_for_const0;


    // Module declarations
    dataflow_in_loop(sc_module_name name);
    SC_HAS_PROCESS(dataflow_in_loop);

    ~dataflow_in_loop();

    sc_trace_file* mVcdFile;

    dataflow_in_loop_bAo* x_pack_V_U;
    load_and_calc_norm51* load_and_calc_norm51_U0;
    compute_and_output* compute_and_output_U0;
    fifo_w31_d2_A* n_c_U;
    fifo_w32_d2_A* num_images_c_U;
    fifo_w24_d2_A* internal_norm_V_U;
    sc_signal< sc_lv<128> > x_pack_V_i_q0;
    sc_signal< sc_lv<128> > x_pack_V_t_q0;
    sc_signal< sc_logic > load_and_calc_norm51_U0_ap_start;
    sc_signal< sc_logic > load_and_calc_norm51_U0_ap_done;
    sc_signal< sc_logic > load_and_calc_norm51_U0_ap_continue;
    sc_signal< sc_logic > load_and_calc_norm51_U0_ap_idle;
    sc_signal< sc_logic > load_and_calc_norm51_U0_ap_ready;
    sc_signal< sc_logic > load_and_calc_norm51_U0_in_stream_TREADY;
    sc_signal< sc_lv<5> > load_and_calc_norm51_U0_x_pack_V_address1;
    sc_signal< sc_logic > load_and_calc_norm51_U0_x_pack_V_ce1;
    sc_signal< sc_logic > load_and_calc_norm51_U0_x_pack_V_we1;
    sc_signal< sc_lv<128> > load_and_calc_norm51_U0_x_pack_V_d1;
    sc_signal< sc_lv<31> > load_and_calc_norm51_U0_n_out_din;
    sc_signal< sc_logic > load_and_calc_norm51_U0_n_out_write;
    sc_signal< sc_lv<32> > load_and_calc_norm51_U0_num_images_out_din;
    sc_signal< sc_logic > load_and_calc_norm51_U0_num_images_out_write;
    sc_signal< sc_lv<24> > load_and_calc_norm51_U0_ap_return;
    sc_signal< sc_logic > ap_channel_done_internal_norm_V;
    sc_signal< sc_logic > internal_norm_V_full_n;
    sc_signal< sc_logic > ap_sync_reg_channel_write_internal_norm_V;
    sc_signal< sc_logic > ap_sync_channel_write_internal_norm_V;
    sc_signal< sc_logic > ap_channel_done_x_pack_V;
    sc_signal< sc_logic > load_and_calc_norm51_U0_x_pack_V_full_n;
    sc_signal< sc_logic > ap_sync_reg_channel_write_x_pack_V;
    sc_signal< sc_logic > ap_sync_channel_write_x_pack_V;
    sc_signal< sc_logic > compute_and_output_U0_ap_start;
    sc_signal< sc_logic > compute_and_output_U0_ap_done;
    sc_signal< sc_logic > compute_and_output_U0_ap_continue;
    sc_signal< sc_logic > compute_and_output_U0_ap_idle;
    sc_signal< sc_logic > compute_and_output_U0_ap_ready;
    sc_signal< sc_lv<5> > compute_and_output_U0_x_pack_V_address0;
    sc_signal< sc_logic > compute_and_output_U0_x_pack_V_ce0;
    sc_signal< sc_lv<32> > compute_and_output_U0_out_stream_TDATA;
    sc_signal< sc_logic > compute_and_output_U0_out_stream_TVALID;
    sc_signal< sc_lv<1> > compute_and_output_U0_out_stream_TKEEP;
    sc_signal< sc_lv<1> > compute_and_output_U0_out_stream_TSTRB;
    sc_signal< sc_lv<1> > compute_and_output_U0_out_stream_TLAST;
    sc_signal< sc_logic > compute_and_output_U0_n_read;
    sc_signal< sc_logic > compute_and_output_U0_num_images_read;
    sc_signal< sc_logic > ap_sync_continue;
    sc_signal< sc_logic > x_pack_V_i_full_n;
    sc_signal< sc_logic > x_pack_V_t_empty_n;
    sc_signal< sc_lv<128> > x_pack_V_t_d0;
    sc_signal< sc_logic > x_pack_V_t_we0;
    sc_signal< sc_logic > n_c_full_n;
    sc_signal< sc_lv<31> > n_c_dout;
    sc_signal< sc_logic > n_c_empty_n;
    sc_signal< sc_logic > num_images_c_full_n;
    sc_signal< sc_lv<32> > num_images_c_dout;
    sc_signal< sc_logic > num_images_c_empty_n;
    sc_signal< sc_lv<24> > internal_norm_V_dout;
    sc_signal< sc_logic > internal_norm_V_empty_n;
    sc_signal< sc_logic > ap_sync_done;
    sc_signal< sc_logic > ap_sync_ready;
    sc_signal< sc_logic > load_and_calc_norm51_U0_start_full_n;
    sc_signal< sc_logic > load_and_calc_norm51_U0_start_write;
    sc_signal< sc_logic > compute_and_output_U0_start_full_n;
    sc_signal< sc_logic > compute_and_output_U0_start_write;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<128> ap_const_lv128_lc_1;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<128> ap_const_lv128_lc_2;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const3();
    void thread_ap_var_for_const1();
    void thread_ap_var_for_const2();
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_channel_done_internal_norm_V();
    void thread_ap_channel_done_x_pack_V();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sync_channel_write_internal_norm_V();
    void thread_ap_sync_channel_write_x_pack_V();
    void thread_ap_sync_continue();
    void thread_ap_sync_done();
    void thread_ap_sync_ready();
    void thread_compute_and_output_U0_ap_continue();
    void thread_compute_and_output_U0_ap_start();
    void thread_compute_and_output_U0_start_full_n();
    void thread_compute_and_output_U0_start_write();
    void thread_in_stream_TREADY();
    void thread_load_and_calc_norm51_U0_ap_continue();
    void thread_load_and_calc_norm51_U0_ap_start();
    void thread_load_and_calc_norm51_U0_start_full_n();
    void thread_load_and_calc_norm51_U0_start_write();
    void thread_load_and_calc_norm51_U0_x_pack_V_full_n();
    void thread_out_stream_TDATA();
    void thread_out_stream_TKEEP();
    void thread_out_stream_TLAST();
    void thread_out_stream_TSTRB();
    void thread_out_stream_TVALID();
    void thread_x_pack_V_t_d0();
    void thread_x_pack_V_t_we0();
};

}

using namespace ap_rtl;

#endif
