// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _floor_to_int_HH_
#define _floor_to_int_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct floor_to_int : public sc_module {
    // Port declarations 3
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<37> > v_V;
    sc_out< sc_lv<9> > ap_return;


    // Module declarations
    floor_to_int(sc_module_name name);
    SC_HAS_PROCESS(floor_to_int);

    ~floor_to_int();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<37> > v_V_cast1_fu_26_p0;
    sc_signal< sc_lv<37> > tmp_fu_30_p1;
    sc_signal< sc_lv<5> > tmp_fu_30_p4;
    sc_signal< sc_lv<37> > tmp_1_fu_44_p1;
    sc_signal< sc_lv<37> > tmp_3_fu_52_p0;
    sc_signal< sc_lv<32> > tmp_3_fu_52_p1;
    sc_signal< sc_lv<8> > ret_V_fu_40_p1;
    sc_signal< sc_lv<1> > tmp_2_fu_56_p2;
    sc_signal< sc_lv<8> > ret_V_1_fu_62_p2;
    sc_signal< sc_lv<1> > tmp_1_fu_44_p3;
    sc_signal< sc_lv<8> > p_s_fu_68_p3;
    sc_signal< sc_lv<8> > p_2_fu_76_p3;
    sc_signal< sc_lv<37> > tmp_4_fu_88_p1;
    sc_signal< sc_lv<40> > tmp_7_fu_96_p3;
    sc_signal< sc_lv<40> > v_V_cast1_fu_26_p1;
    sc_signal< sc_lv<9> > iv_2_cast_fu_84_p1;
    sc_signal< sc_lv<1> > tmp_8_fu_104_p2;
    sc_signal< sc_lv<9> > iv_fu_110_p2;
    sc_signal< sc_lv<1> > tmp_4_fu_88_p3;
    sc_signal< sc_lv<9> > p_1_fu_116_p3;
    static const sc_logic ap_const_logic_1;
    static const bool ap_const_boolean_1;
    static const sc_lv<32> ap_const_lv32_20;
    static const sc_lv<32> ap_const_lv32_24;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<8> ap_const_lv8_1;
    static const sc_lv<9> ap_const_lv9_1FF;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_ready();
    void thread_ap_return();
    void thread_iv_2_cast_fu_84_p1();
    void thread_iv_fu_110_p2();
    void thread_p_1_fu_116_p3();
    void thread_p_2_fu_76_p3();
    void thread_p_s_fu_68_p3();
    void thread_ret_V_1_fu_62_p2();
    void thread_ret_V_fu_40_p1();
    void thread_tmp_1_fu_44_p1();
    void thread_tmp_1_fu_44_p3();
    void thread_tmp_2_fu_56_p2();
    void thread_tmp_3_fu_52_p0();
    void thread_tmp_3_fu_52_p1();
    void thread_tmp_4_fu_88_p1();
    void thread_tmp_4_fu_88_p3();
    void thread_tmp_7_fu_96_p3();
    void thread_tmp_8_fu_104_p2();
    void thread_tmp_fu_30_p1();
    void thread_tmp_fu_30_p4();
    void thread_v_V_cast1_fu_26_p0();
    void thread_v_V_cast1_fu_26_p1();
};

}

using namespace ap_rtl;

#endif
