// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _p_ADSD_Classifier_cp_4_HH_
#define _p_ADSD_Classifier_cp_4_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct p_ADSD_Classifier_cp_4 : public sc_module {
    // Port declarations 10
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<32> > p_read;
    sc_out< sc_lv<32> > tmp_data_V19;
    sc_out< sc_logic > tmp_data_V19_ap_vld;


    // Module declarations
    p_ADSD_Classifier_cp_4(sc_module_name name);
    SC_HAS_PROCESS(p_ADSD_Classifier_cp_4);

    ~p_ADSD_Classifier_cp_4();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<32> > tmp_data_V19_preg;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_fsm_state1;
    static const sc_lv<32> ap_const_lv32_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_block_state1();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_tmp_data_V19();
    void thread_tmp_data_V19_ap_vld();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
