// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "p_ADSD_Classifier_cp_1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic p_ADSD_Classifier_cp_1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic p_ADSD_Classifier_cp_1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> p_ADSD_Classifier_cp_1::ap_ST_fsm_state1 = "1";
const sc_lv<32> p_ADSD_Classifier_cp_1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> p_ADSD_Classifier_cp_1::ap_const_lv1_0 = "0";
const sc_lv<12> p_ADSD_Classifier_cp_1::ap_const_lv12_A28 = "101000101000";
const bool p_ADSD_Classifier_cp_1::ap_const_boolean_1 = true;

p_ADSD_Classifier_cp_1::p_ADSD_Classifier_cp_1(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( n_0_i_i_empty_n );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( n_0_i_i_empty_n );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( n_0_i_i_empty_n );

    SC_METHOD(thread_n_0_i_i_blk_n);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( n_0_i_i_empty_n );

    SC_METHOD(thread_n_0_i_i_read);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( n_0_i_i_empty_n );

    SC_METHOD(thread_out_val_last_V_i_fu_35_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( n_0_i_i_dout );
    sensitive << ( n_0_i_i_empty_n );

    SC_METHOD(thread_tmp_last_V22);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( n_0_i_i_empty_n );
    sensitive << ( out_val_last_V_i_fu_35_p2 );
    sensitive << ( tmp_last_V22_preg );

    SC_METHOD(thread_tmp_last_V22_ap_vld);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( n_0_i_i_empty_n );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( n_0_i_i_empty_n );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "1";
    tmp_last_V22_preg = "0";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "p_ADSD_Classifier_cp_1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, n_0_i_i_dout, "(port)n_0_i_i_dout");
    sc_trace(mVcdFile, n_0_i_i_empty_n, "(port)n_0_i_i_empty_n");
    sc_trace(mVcdFile, n_0_i_i_read, "(port)n_0_i_i_read");
    sc_trace(mVcdFile, tmp_last_V22, "(port)tmp_last_V22");
    sc_trace(mVcdFile, tmp_last_V22_ap_vld, "(port)tmp_last_V22_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, n_0_i_i_blk_n, "n_0_i_i_blk_n");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, out_val_last_V_i_fu_35_p2, "out_val_last_V_i_fu_35_p2");
    sc_trace(mVcdFile, tmp_last_V22_preg, "tmp_last_V22_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

p_ADSD_Classifier_cp_1::~p_ADSD_Classifier_cp_1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void p_ADSD_Classifier_cp_1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(n_0_i_i_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        tmp_last_V22_preg = ap_const_lv1_0;
    } else {
        if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(n_0_i_i_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
            tmp_last_V22_preg = out_val_last_V_i_fu_35_p2.read();
        }
    }
}

void p_ADSD_Classifier_cp_1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void p_ADSD_Classifier_cp_1::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(n_0_i_i_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void p_ADSD_Classifier_cp_1::thread_ap_done() {
    if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(n_0_i_i_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void p_ADSD_Classifier_cp_1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void p_ADSD_Classifier_cp_1::thread_ap_ready() {
    if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(n_0_i_i_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void p_ADSD_Classifier_cp_1::thread_n_0_i_i_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        n_0_i_i_blk_n = n_0_i_i_empty_n.read();
    } else {
        n_0_i_i_blk_n = ap_const_logic_1;
    }
}

void p_ADSD_Classifier_cp_1::thread_n_0_i_i_read() {
    if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(n_0_i_i_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        n_0_i_i_read = ap_const_logic_1;
    } else {
        n_0_i_i_read = ap_const_logic_0;
    }
}

void p_ADSD_Classifier_cp_1::thread_out_val_last_V_i_fu_35_p2() {
    out_val_last_V_i_fu_35_p2 = (!n_0_i_i_dout.read().is_01() || !ap_const_lv12_A28.is_01())? sc_lv<1>(): sc_lv<1>(n_0_i_i_dout.read() == ap_const_lv12_A28);
}

void p_ADSD_Classifier_cp_1::thread_tmp_last_V22() {
    if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(n_0_i_i_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        tmp_last_V22 = out_val_last_V_i_fu_35_p2.read();
    } else {
        tmp_last_V22 = tmp_last_V22_preg.read();
    }
}

void p_ADSD_Classifier_cp_1::thread_tmp_last_V22_ap_vld() {
    if ((!(esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(n_0_i_i_empty_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        tmp_last_V22_ap_vld = ap_const_logic_1;
    } else {
        tmp_last_V22_ap_vld = ap_const_logic_0;
    }
}

void p_ADSD_Classifier_cp_1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state1;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

