-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity load_and_calc_norm51 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
    in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    x_pack_V_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    x_pack_V_ce1 : OUT STD_LOGIC;
    x_pack_V_we1 : OUT STD_LOGIC;
    x_pack_V_d1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    n : IN STD_LOGIC_VECTOR (30 downto 0);
    num_images : IN STD_LOGIC_VECTOR (31 downto 0);
    n_out_din : OUT STD_LOGIC_VECTOR (30 downto 0);
    n_out_full_n : IN STD_LOGIC;
    n_out_write : OUT STD_LOGIC;
    num_images_out_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    num_images_out_full_n : IN STD_LOGIC;
    num_images_out_write : OUT STD_LOGIC;
    ap_return : OUT STD_LOGIC_VECTOR (23 downto 0) );
end;


architecture behav of load_and_calc_norm51 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage1 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv5_1F : STD_LOGIC_VECTOR (4 downto 0) := "11111";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal in_stream_V_data_V_0_data_out : STD_LOGIC_VECTOR (63 downto 0);
    signal in_stream_V_data_V_0_vld_in : STD_LOGIC;
    signal in_stream_V_data_V_0_vld_out : STD_LOGIC;
    signal in_stream_V_data_V_0_ack_in : STD_LOGIC;
    signal in_stream_V_data_V_0_ack_out : STD_LOGIC;
    signal in_stream_V_data_V_0_payload_A : STD_LOGIC_VECTOR (63 downto 0);
    signal in_stream_V_data_V_0_payload_B : STD_LOGIC_VECTOR (63 downto 0);
    signal in_stream_V_data_V_0_sel_rd : STD_LOGIC := '0';
    signal in_stream_V_data_V_0_sel_wr : STD_LOGIC := '0';
    signal in_stream_V_data_V_0_sel : STD_LOGIC;
    signal in_stream_V_data_V_0_load_A : STD_LOGIC;
    signal in_stream_V_data_V_0_load_B : STD_LOGIC;
    signal in_stream_V_data_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal in_stream_V_data_V_0_state_cmp_full : STD_LOGIC;
    signal in_stream_V_dest_V_0_vld_in : STD_LOGIC;
    signal in_stream_V_dest_V_0_ack_out : STD_LOGIC;
    signal in_stream_V_dest_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage1 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage1 : BOOLEAN;
    signal exitcond1_i_i_reg_699 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal n_out_blk_n : STD_LOGIC;
    signal num_images_out_blk_n : STD_LOGIC;
    signal agg_result_V_write_a_reg_191 : STD_LOGIC_VECTOR (23 downto 0);
    signal g_i_i_reg_203 : STD_LOGIC_VECTOR (4 downto 0);
    signal exitcond1_i_i_fu_289_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal exitcond1_i_i_reg_699_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal g_fu_295_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal g_reg_703 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_data_V_reg_708 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_state3_pp0_stage1_iter0 : BOOLEAN;
    signal ap_block_state5_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_pp0_stage1_11001 : BOOLEAN;
    signal tmp_1_fu_301_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_reg_713 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_219_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_0_1_i_i_reg_718 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_229_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_0_2_i_i_reg_723 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_239_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_0_3_i_i_reg_728 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_249_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_0_4_i_i_reg_733 : STD_LOGIC_VECTOR (7 downto 0);
    signal sq_V_6_fu_309_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_6_reg_738 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_269_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_0_6_i_i_reg_743 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_279_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Result_0_7_i_i_reg_748 : STD_LOGIC_VECTOR (7 downto 0);
    signal sq_V_9_fu_330_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_9_reg_753 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_467_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_reg_758 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp1_fu_473_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp1_reg_763 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp4_fu_479_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp4_reg_768 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp11_fu_485_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp11_reg_773 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp5_fu_636_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp5_reg_778 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp7_fu_641_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp7_reg_783 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp8_fu_647_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp8_reg_788 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp12_fu_659_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp12_reg_793 : STD_LOGIC_VECTOR (23 downto 0);
    signal calculated_norm_V_fu_688_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_block_pp0_stage1_subdone : BOOLEAN;
    signal ap_phi_mux_g_i_i_phi_fu_207_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_i_i_fu_499_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sq_V_16_fu_448_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_259_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal sq_V_6_fu_309_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal OP1_V_0_5_i_i_fu_305_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_6_fu_309_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_322_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sq_V_9_fu_330_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal OP1_V_1_i_i_fu_326_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_9_fu_330_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sq_V_10_fu_340_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal OP1_V_1_1_i_i_fu_336_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_10_fu_340_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sq_V_10_fu_340_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_11_fu_358_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal OP1_V_1_2_i_i_fu_354_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_11_fu_358_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sq_V_11_fu_358_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_12_fu_376_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal OP1_V_1_3_i_i_fu_372_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_12_fu_376_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sq_V_12_fu_376_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_13_fu_394_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal OP1_V_1_4_i_i_fu_390_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_13_fu_394_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sq_V_13_fu_394_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_14_fu_412_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal OP1_V_1_5_i_i_fu_408_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_14_fu_412_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sq_V_14_fu_412_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_15_fu_430_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal OP1_V_1_6_i_i_fu_426_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_15_fu_430_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sq_V_15_fu_430_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_16_fu_448_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal OP1_V_1_7_i_i_fu_444_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_16_fu_448_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_9_1_5_i_i_fu_418_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_9_1_6_i_i_fu_436_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_9_1_4_i_i_fu_400_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_9_1_3_i_i_fu_382_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_9_1_2_i_i_fu_364_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_9_1_1_i_i_fu_346_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_9_0_5_i_i_fu_315_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_9_1_7_i_i_fu_459_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal sq_V_1_fu_507_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal OP1_V_0_i_i_fu_504_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_1_fu_507_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sq_V_1_fu_507_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_2_fu_524_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal OP1_V_0_1_i_i_fu_521_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_2_fu_524_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sq_V_2_fu_524_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_3_fu_541_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal OP1_V_0_2_i_i_fu_538_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_3_fu_541_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sq_V_3_fu_541_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_4_fu_558_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal OP1_V_0_3_i_i_fu_555_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_4_fu_558_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sq_V_4_fu_558_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_5_fu_575_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal OP1_V_0_4_i_i_fu_572_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_5_fu_575_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sq_V_5_fu_575_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_7_fu_592_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal OP1_V_0_6_i_i_fu_589_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_7_fu_592_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sq_V_7_fu_592_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_8_fu_609_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal OP1_V_0_7_i_i_fu_606_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sq_V_8_fu_609_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal sq_V_8_fu_609_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_9_1_i_i_fu_623_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_9_0_7_i_i_fu_615_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp3_fu_630_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_9_0_i_i_fu_513_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_9_0_2_i_i_fu_547_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_9_0_1_i_i_fu_530_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_9_0_4_i_i_fu_581_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_9_0_3_i_i_fu_564_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_9_0_6_i_i_fu_598_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp10_fu_653_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp2_fu_664_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp9_fu_673_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp13_fu_677_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp6_fu_668_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_s_fu_682_p2 : STD_LOGIC_VECTOR (23 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((not(((ap_start = ap_const_logic_0) or (num_images_out_full_n = ap_const_logic_0) or (n_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                elsif ((not(((ap_start = ap_const_logic_0) or (num_images_out_full_n = ap_const_logic_0) or (n_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    in_stream_V_data_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                in_stream_V_data_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((in_stream_V_data_V_0_ack_out = ap_const_logic_1) and (in_stream_V_data_V_0_vld_out = ap_const_logic_1))) then 
                                        in_stream_V_data_V_0_sel_rd <= not(in_stream_V_data_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    in_stream_V_data_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                in_stream_V_data_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((in_stream_V_data_V_0_ack_in = ap_const_logic_1) and (in_stream_V_data_V_0_vld_in = ap_const_logic_1))) then 
                                        in_stream_V_data_V_0_sel_wr <= not(in_stream_V_data_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    in_stream_V_data_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                in_stream_V_data_V_0_state <= ap_const_lv2_0;
            else
                if ((((in_stream_V_data_V_0_state = ap_const_lv2_2) and (in_stream_V_data_V_0_vld_in = ap_const_logic_0)) or ((in_stream_V_data_V_0_state = ap_const_lv2_3) and (in_stream_V_data_V_0_vld_in = ap_const_logic_0) and (in_stream_V_data_V_0_ack_out = ap_const_logic_1)))) then 
                    in_stream_V_data_V_0_state <= ap_const_lv2_2;
                elsif ((((in_stream_V_data_V_0_state = ap_const_lv2_1) and (in_stream_V_data_V_0_ack_out = ap_const_logic_0)) or ((in_stream_V_data_V_0_state = ap_const_lv2_3) and (in_stream_V_data_V_0_ack_out = ap_const_logic_0) and (in_stream_V_data_V_0_vld_in = ap_const_logic_1)))) then 
                    in_stream_V_data_V_0_state <= ap_const_lv2_1;
                elsif (((not(((in_stream_V_data_V_0_vld_in = ap_const_logic_0) and (in_stream_V_data_V_0_ack_out = ap_const_logic_1))) and not(((in_stream_V_data_V_0_ack_out = ap_const_logic_0) and (in_stream_V_data_V_0_vld_in = ap_const_logic_1))) and (in_stream_V_data_V_0_state = ap_const_lv2_3)) or ((in_stream_V_data_V_0_state = ap_const_lv2_1) and (in_stream_V_data_V_0_ack_out = ap_const_logic_1)) or ((in_stream_V_data_V_0_state = ap_const_lv2_2) and (in_stream_V_data_V_0_vld_in = ap_const_logic_1)))) then 
                    in_stream_V_data_V_0_state <= ap_const_lv2_3;
                else 
                    in_stream_V_data_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    in_stream_V_dest_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                in_stream_V_dest_V_0_state <= ap_const_lv2_0;
            else
                if ((((in_stream_V_dest_V_0_state = ap_const_lv2_2) and (in_stream_V_dest_V_0_vld_in = ap_const_logic_0)) or ((in_stream_V_dest_V_0_state = ap_const_lv2_3) and (in_stream_V_dest_V_0_vld_in = ap_const_logic_0) and (in_stream_V_dest_V_0_ack_out = ap_const_logic_1)))) then 
                    in_stream_V_dest_V_0_state <= ap_const_lv2_2;
                elsif ((((in_stream_V_dest_V_0_state = ap_const_lv2_1) and (in_stream_V_dest_V_0_ack_out = ap_const_logic_0)) or ((in_stream_V_dest_V_0_state = ap_const_lv2_3) and (in_stream_V_dest_V_0_ack_out = ap_const_logic_0) and (in_stream_V_dest_V_0_vld_in = ap_const_logic_1)))) then 
                    in_stream_V_dest_V_0_state <= ap_const_lv2_1;
                elsif (((not(((in_stream_V_dest_V_0_vld_in = ap_const_logic_0) and (in_stream_V_dest_V_0_ack_out = ap_const_logic_1))) and not(((in_stream_V_dest_V_0_ack_out = ap_const_logic_0) and (in_stream_V_dest_V_0_vld_in = ap_const_logic_1))) and (in_stream_V_dest_V_0_state = ap_const_lv2_3)) or ((in_stream_V_dest_V_0_state = ap_const_lv2_1) and (in_stream_V_dest_V_0_ack_out = ap_const_logic_1)) or ((in_stream_V_dest_V_0_state = ap_const_lv2_2) and (in_stream_V_dest_V_0_vld_in = ap_const_logic_1)))) then 
                    in_stream_V_dest_V_0_state <= ap_const_lv2_3;
                else 
                    in_stream_V_dest_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    agg_result_V_write_a_reg_191_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond1_i_i_reg_699_pp0_iter1_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                agg_result_V_write_a_reg_191 <= calculated_norm_V_fu_688_p2;
            elsif ((not(((ap_start = ap_const_logic_0) or (num_images_out_full_n = ap_const_logic_0) or (n_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                agg_result_V_write_a_reg_191 <= ap_const_lv24_0;
            end if; 
        end if;
    end process;

    g_i_i_reg_203_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond1_i_i_reg_699 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                g_i_i_reg_203 <= g_reg_703;
            elsif ((not(((ap_start = ap_const_logic_0) or (num_images_out_full_n = ap_const_logic_0) or (n_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                g_i_i_reg_203 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                exitcond1_i_i_reg_699 <= exitcond1_i_i_fu_289_p2;
                exitcond1_i_i_reg_699_pp0_iter1_reg <= exitcond1_i_i_reg_699;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                g_reg_703 <= g_fu_295_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((in_stream_V_data_V_0_load_A = ap_const_logic_1)) then
                in_stream_V_data_V_0_payload_A <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((in_stream_V_data_V_0_load_B = ap_const_logic_1)) then
                in_stream_V_data_V_0_payload_B <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (exitcond1_i_i_reg_699 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                p_Result_0_1_i_i_reg_718 <= in_stream_V_data_V_0_data_out(15 downto 8);
                p_Result_0_2_i_i_reg_723 <= in_stream_V_data_V_0_data_out(23 downto 16);
                p_Result_0_3_i_i_reg_728 <= in_stream_V_data_V_0_data_out(31 downto 24);
                p_Result_0_4_i_i_reg_733 <= in_stream_V_data_V_0_data_out(39 downto 32);
                p_Result_0_6_i_i_reg_743 <= in_stream_V_data_V_0_data_out(55 downto 48);
                p_Result_0_7_i_i_reg_748 <= in_stream_V_data_V_0_data_out(63 downto 56);
                tmp_data_V_reg_708 <= in_stream_V_data_V_0_data_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (exitcond1_i_i_reg_699 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                sq_V_6_reg_738 <= sq_V_6_fu_309_p2;
                tmp_1_reg_713 <= tmp_1_fu_301_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond1_i_i_reg_699 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                sq_V_9_reg_753 <= sq_V_9_fu_330_p2;
                    tmp11_reg_773(23 downto 8) <= tmp11_fu_485_p2(23 downto 8);
                    tmp1_reg_763(23 downto 8) <= tmp1_fu_473_p2(23 downto 8);
                    tmp4_reg_768(23 downto 8) <= tmp4_fu_479_p2(23 downto 8);
                    tmp_reg_758(23 downto 8) <= tmp_fu_467_p2(23 downto 8);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (exitcond1_i_i_reg_699_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1))) then
                    tmp12_reg_793(23 downto 8) <= tmp12_fu_659_p2(23 downto 8);
                    tmp5_reg_778(23 downto 8) <= tmp5_fu_636_p2(23 downto 8);
                    tmp7_reg_783(23 downto 8) <= tmp7_fu_641_p2(23 downto 8);
                    tmp8_reg_788(23 downto 8) <= tmp8_fu_647_p2(23 downto 8);
            end if;
        end if;
    end process;
    tmp_reg_758(7 downto 0) <= "00000000";
    tmp1_reg_763(7 downto 0) <= "00000000";
    tmp4_reg_768(7 downto 0) <= "00000000";
    tmp11_reg_773(7 downto 0) <= "00000000";
    tmp5_reg_778(7 downto 0) <= "00000000";
    tmp7_reg_783(7 downto 0) <= "00000000";
    tmp8_reg_788(7 downto 0) <= "00000000";
    tmp12_reg_793(7 downto 0) <= "00000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, n_out_full_n, num_images_out_full_n, ap_enable_reg_pp0_iter0, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, exitcond1_i_i_fu_289_p2, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_subdone, ap_block_pp0_stage1_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (num_images_out_full_n = ap_const_logic_0) or (n_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (exitcond1_i_i_fu_289_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) and not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (exitcond1_i_i_fu_289_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage1 => 
                if ((ap_const_boolean_0 = ap_block_pp0_stage1_subdone)) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage1;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
        OP1_V_0_1_i_i_fu_521_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Result_0_1_i_i_reg_718),16));

        OP1_V_0_2_i_i_fu_538_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Result_0_2_i_i_reg_723),16));

        OP1_V_0_3_i_i_fu_555_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Result_0_3_i_i_reg_728),16));

        OP1_V_0_4_i_i_fu_572_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Result_0_4_i_i_reg_733),16));

        OP1_V_0_5_i_i_fu_305_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_259_p4),16));

        OP1_V_0_6_i_i_fu_589_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Result_0_6_i_i_reg_743),16));

        OP1_V_0_7_i_i_fu_606_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(p_Result_0_7_i_i_reg_748),16));

        OP1_V_0_i_i_fu_504_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_1_reg_713),16));

        OP1_V_1_1_i_i_fu_336_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_219_p4),16));

        OP1_V_1_2_i_i_fu_354_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_229_p4),16));

        OP1_V_1_3_i_i_fu_372_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_239_p4),16));

        OP1_V_1_4_i_i_fu_390_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_249_p4),16));

        OP1_V_1_5_i_i_fu_408_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_259_p4),16));

        OP1_V_1_6_i_i_fu_426_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_269_p4),16));

        OP1_V_1_7_i_i_fu_444_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(grp_fu_279_p4),16));

        OP1_V_1_i_i_fu_326_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2_fu_322_p1),16));

    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_pp0_stage1 <= ap_CS_fsm(2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state7 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(in_stream_V_data_V_0_vld_out, exitcond1_i_i_reg_699, ap_enable_reg_pp0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= ((exitcond1_i_i_reg_699 = ap_const_lv1_0) and (in_stream_V_data_V_0_vld_out = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(in_stream_V_data_V_0_vld_out, exitcond1_i_i_reg_699, ap_enable_reg_pp0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= ((exitcond1_i_i_reg_699 = ap_const_lv1_0) and (in_stream_V_data_V_0_vld_out = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage1_11001_assign_proc : process(in_stream_V_data_V_0_vld_out, ap_enable_reg_pp0_iter0, exitcond1_i_i_reg_699)
    begin
                ap_block_pp0_stage1_11001 <= ((exitcond1_i_i_reg_699 = ap_const_lv1_0) and (in_stream_V_data_V_0_vld_out = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage1_subdone_assign_proc : process(in_stream_V_data_V_0_vld_out, ap_enable_reg_pp0_iter0, exitcond1_i_i_reg_699)
    begin
                ap_block_pp0_stage1_subdone <= ((exitcond1_i_i_reg_699 = ap_const_lv1_0) and (in_stream_V_data_V_0_vld_out = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, n_out_full_n, num_images_out_full_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (num_images_out_full_n = ap_const_logic_0) or (n_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage1_iter0_assign_proc : process(in_stream_V_data_V_0_vld_out, exitcond1_i_i_reg_699)
    begin
                ap_block_state3_pp0_stage1_iter0 <= ((exitcond1_i_i_reg_699 = ap_const_lv1_0) and (in_stream_V_data_V_0_vld_out = ap_const_logic_0));
    end process;


    ap_block_state4_pp0_stage0_iter1_assign_proc : process(in_stream_V_data_V_0_vld_out, exitcond1_i_i_reg_699)
    begin
                ap_block_state4_pp0_stage0_iter1 <= ((exitcond1_i_i_reg_699 = ap_const_lv1_0) and (in_stream_V_data_V_0_vld_out = ap_const_logic_0));
    end process;

        ap_block_state5_pp0_stage1_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state2_assign_proc : process(exitcond1_i_i_fu_289_p2)
    begin
        if ((exitcond1_i_i_fu_289_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_g_i_i_phi_fu_207_p4_assign_proc : process(exitcond1_i_i_reg_699, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, g_i_i_reg_203, g_reg_703)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (exitcond1_i_i_reg_699 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_phi_mux_g_i_i_phi_fu_207_p4 <= g_reg_703;
        else 
            ap_phi_mux_g_i_i_phi_fu_207_p4 <= g_i_i_reg_203;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= agg_result_V_write_a_reg_191;
    calculated_norm_V_fu_688_p2 <= std_logic_vector(unsigned(agg_result_V_write_a_reg_191) + unsigned(tmp_s_fu_682_p2));
    exitcond1_i_i_fu_289_p2 <= "1" when (ap_phi_mux_g_i_i_phi_fu_207_p4 = ap_const_lv5_1F) else "0";
    g_fu_295_p2 <= std_logic_vector(unsigned(ap_phi_mux_g_i_i_phi_fu_207_p4) + unsigned(ap_const_lv5_1));
    grp_fu_219_p4 <= in_stream_V_data_V_0_data_out(15 downto 8);
    grp_fu_229_p4 <= in_stream_V_data_V_0_data_out(23 downto 16);
    grp_fu_239_p4 <= in_stream_V_data_V_0_data_out(31 downto 24);
    grp_fu_249_p4 <= in_stream_V_data_V_0_data_out(39 downto 32);
    grp_fu_259_p4 <= in_stream_V_data_V_0_data_out(47 downto 40);
    grp_fu_269_p4 <= in_stream_V_data_V_0_data_out(55 downto 48);
    grp_fu_279_p4 <= in_stream_V_data_V_0_data_out(63 downto 56);

    in_stream_TDATA_blk_n_assign_proc : process(in_stream_V_data_V_0_state, ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, ap_block_pp0_stage1, exitcond1_i_i_reg_699, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (exitcond1_i_i_reg_699 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((exitcond1_i_i_reg_699 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            in_stream_TDATA_blk_n <= in_stream_V_data_V_0_state(0);
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in_stream_TREADY <= in_stream_V_dest_V_0_state(1);
    in_stream_V_data_V_0_ack_in <= in_stream_V_data_V_0_state(1);

    in_stream_V_data_V_0_ack_out_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, exitcond1_i_i_reg_699, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond1_i_i_reg_699 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (exitcond1_i_i_reg_699 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            in_stream_V_data_V_0_ack_out <= ap_const_logic_1;
        else 
            in_stream_V_data_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    in_stream_V_data_V_0_data_out_assign_proc : process(in_stream_V_data_V_0_payload_A, in_stream_V_data_V_0_payload_B, in_stream_V_data_V_0_sel)
    begin
        if ((in_stream_V_data_V_0_sel = ap_const_logic_1)) then 
            in_stream_V_data_V_0_data_out <= in_stream_V_data_V_0_payload_B;
        else 
            in_stream_V_data_V_0_data_out <= in_stream_V_data_V_0_payload_A;
        end if; 
    end process;

    in_stream_V_data_V_0_load_A <= (in_stream_V_data_V_0_state_cmp_full and not(in_stream_V_data_V_0_sel_wr));
    in_stream_V_data_V_0_load_B <= (in_stream_V_data_V_0_state_cmp_full and in_stream_V_data_V_0_sel_wr);
    in_stream_V_data_V_0_sel <= in_stream_V_data_V_0_sel_rd;
    in_stream_V_data_V_0_state_cmp_full <= '0' when (in_stream_V_data_V_0_state = ap_const_lv2_1) else '1';
    in_stream_V_data_V_0_vld_in <= in_stream_TVALID;
    in_stream_V_data_V_0_vld_out <= in_stream_V_data_V_0_state(0);

    in_stream_V_dest_V_0_ack_out_assign_proc : process(ap_CS_fsm_pp0_stage1, ap_enable_reg_pp0_iter0, exitcond1_i_i_reg_699, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, ap_block_pp0_stage1_11001)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond1_i_i_reg_699 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage1_11001) and (exitcond1_i_i_reg_699 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage1)))) then 
            in_stream_V_dest_V_0_ack_out <= ap_const_logic_1;
        else 
            in_stream_V_dest_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;

    in_stream_V_dest_V_0_vld_in <= in_stream_TVALID;

    n_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, n_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            n_out_blk_n <= n_out_full_n;
        else 
            n_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    n_out_din <= n;

    n_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, n_out_full_n, num_images_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (num_images_out_full_n = ap_const_logic_0) or (n_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            n_out_write <= ap_const_logic_1;
        else 
            n_out_write <= ap_const_logic_0;
        end if; 
    end process;


    num_images_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, num_images_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            num_images_out_blk_n <= num_images_out_full_n;
        else 
            num_images_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    num_images_out_din <= num_images;

    num_images_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, n_out_full_n, num_images_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (num_images_out_full_n = ap_const_logic_0) or (n_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            num_images_out_write <= ap_const_logic_1;
        else 
            num_images_out_write <= ap_const_logic_0;
        end if; 
    end process;

    sq_V_10_fu_340_p0 <= OP1_V_1_1_i_i_fu_336_p1(8 - 1 downto 0);
    sq_V_10_fu_340_p1 <= OP1_V_1_1_i_i_fu_336_p1(8 - 1 downto 0);
    sq_V_10_fu_340_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(sq_V_10_fu_340_p0) * signed(sq_V_10_fu_340_p1))), 16));
    sq_V_11_fu_358_p0 <= OP1_V_1_2_i_i_fu_354_p1(8 - 1 downto 0);
    sq_V_11_fu_358_p1 <= OP1_V_1_2_i_i_fu_354_p1(8 - 1 downto 0);
    sq_V_11_fu_358_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(sq_V_11_fu_358_p0) * signed(sq_V_11_fu_358_p1))), 16));
    sq_V_12_fu_376_p0 <= OP1_V_1_3_i_i_fu_372_p1(8 - 1 downto 0);
    sq_V_12_fu_376_p1 <= OP1_V_1_3_i_i_fu_372_p1(8 - 1 downto 0);
    sq_V_12_fu_376_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(sq_V_12_fu_376_p0) * signed(sq_V_12_fu_376_p1))), 16));
    sq_V_13_fu_394_p0 <= OP1_V_1_4_i_i_fu_390_p1(8 - 1 downto 0);
    sq_V_13_fu_394_p1 <= OP1_V_1_4_i_i_fu_390_p1(8 - 1 downto 0);
    sq_V_13_fu_394_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(sq_V_13_fu_394_p0) * signed(sq_V_13_fu_394_p1))), 16));
    sq_V_14_fu_412_p0 <= OP1_V_1_5_i_i_fu_408_p1(8 - 1 downto 0);
    sq_V_14_fu_412_p1 <= OP1_V_1_5_i_i_fu_408_p1(8 - 1 downto 0);
    sq_V_14_fu_412_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(sq_V_14_fu_412_p0) * signed(sq_V_14_fu_412_p1))), 16));
    sq_V_15_fu_430_p0 <= OP1_V_1_6_i_i_fu_426_p1(8 - 1 downto 0);
    sq_V_15_fu_430_p1 <= OP1_V_1_6_i_i_fu_426_p1(8 - 1 downto 0);
    sq_V_15_fu_430_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(sq_V_15_fu_430_p0) * signed(sq_V_15_fu_430_p1))), 16));
    sq_V_16_fu_448_p0 <= OP1_V_1_7_i_i_fu_444_p1(8 - 1 downto 0);
    sq_V_16_fu_448_p1 <= OP1_V_1_7_i_i_fu_444_p1(8 - 1 downto 0);
    sq_V_16_fu_448_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(sq_V_16_fu_448_p0) * signed(sq_V_16_fu_448_p1))), 16));
    sq_V_1_fu_507_p0 <= OP1_V_0_i_i_fu_504_p1(8 - 1 downto 0);
    sq_V_1_fu_507_p1 <= OP1_V_0_i_i_fu_504_p1(8 - 1 downto 0);
    sq_V_1_fu_507_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(sq_V_1_fu_507_p0) * signed(sq_V_1_fu_507_p1))), 16));
    sq_V_2_fu_524_p0 <= OP1_V_0_1_i_i_fu_521_p1(8 - 1 downto 0);
    sq_V_2_fu_524_p1 <= OP1_V_0_1_i_i_fu_521_p1(8 - 1 downto 0);
    sq_V_2_fu_524_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(sq_V_2_fu_524_p0) * signed(sq_V_2_fu_524_p1))), 16));
    sq_V_3_fu_541_p0 <= OP1_V_0_2_i_i_fu_538_p1(8 - 1 downto 0);
    sq_V_3_fu_541_p1 <= OP1_V_0_2_i_i_fu_538_p1(8 - 1 downto 0);
    sq_V_3_fu_541_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(sq_V_3_fu_541_p0) * signed(sq_V_3_fu_541_p1))), 16));
    sq_V_4_fu_558_p0 <= OP1_V_0_3_i_i_fu_555_p1(8 - 1 downto 0);
    sq_V_4_fu_558_p1 <= OP1_V_0_3_i_i_fu_555_p1(8 - 1 downto 0);
    sq_V_4_fu_558_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(sq_V_4_fu_558_p0) * signed(sq_V_4_fu_558_p1))), 16));
    sq_V_5_fu_575_p0 <= OP1_V_0_4_i_i_fu_572_p1(8 - 1 downto 0);
    sq_V_5_fu_575_p1 <= OP1_V_0_4_i_i_fu_572_p1(8 - 1 downto 0);
    sq_V_5_fu_575_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(sq_V_5_fu_575_p0) * signed(sq_V_5_fu_575_p1))), 16));
    sq_V_6_fu_309_p0 <= OP1_V_0_5_i_i_fu_305_p1(8 - 1 downto 0);
    sq_V_6_fu_309_p1 <= OP1_V_0_5_i_i_fu_305_p1(8 - 1 downto 0);
    sq_V_6_fu_309_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(sq_V_6_fu_309_p0) * signed(sq_V_6_fu_309_p1))), 16));
    sq_V_7_fu_592_p0 <= OP1_V_0_6_i_i_fu_589_p1(8 - 1 downto 0);
    sq_V_7_fu_592_p1 <= OP1_V_0_6_i_i_fu_589_p1(8 - 1 downto 0);
    sq_V_7_fu_592_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(sq_V_7_fu_592_p0) * signed(sq_V_7_fu_592_p1))), 16));
    sq_V_8_fu_609_p0 <= OP1_V_0_7_i_i_fu_606_p1(8 - 1 downto 0);
    sq_V_8_fu_609_p1 <= OP1_V_0_7_i_i_fu_606_p1(8 - 1 downto 0);
    sq_V_8_fu_609_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(sq_V_8_fu_609_p0) * signed(sq_V_8_fu_609_p1))), 16));
    sq_V_9_fu_330_p0 <= OP1_V_1_i_i_fu_326_p1(8 - 1 downto 0);
    sq_V_9_fu_330_p1 <= OP1_V_1_i_i_fu_326_p1(8 - 1 downto 0);
    sq_V_9_fu_330_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(sq_V_9_fu_330_p0) * signed(sq_V_9_fu_330_p1))), 16));
    tmp10_fu_653_p2 <= std_logic_vector(unsigned(tmp_9_0_3_i_i_fu_564_p3) + unsigned(tmp_9_0_6_i_i_fu_598_p3));
    tmp11_fu_485_p2 <= std_logic_vector(unsigned(tmp_9_0_5_i_i_fu_315_p3) + unsigned(tmp_9_1_7_i_i_fu_459_p3));
    tmp12_fu_659_p2 <= std_logic_vector(unsigned(tmp11_reg_773) + unsigned(tmp10_fu_653_p2));
    tmp13_fu_677_p2 <= std_logic_vector(unsigned(tmp12_reg_793) + unsigned(tmp9_fu_673_p2));
    tmp1_fu_473_p2 <= std_logic_vector(unsigned(tmp_9_1_4_i_i_fu_400_p3) + unsigned(tmp_9_1_3_i_i_fu_382_p3));
    tmp2_fu_664_p2 <= std_logic_vector(unsigned(tmp1_reg_763) + unsigned(tmp_reg_758));
    tmp3_fu_630_p2 <= std_logic_vector(unsigned(tmp_9_1_i_i_fu_623_p3) + unsigned(tmp_9_0_7_i_i_fu_615_p3));
    tmp4_fu_479_p2 <= std_logic_vector(unsigned(tmp_9_1_2_i_i_fu_364_p3) + unsigned(tmp_9_1_1_i_i_fu_346_p3));
    tmp5_fu_636_p2 <= std_logic_vector(unsigned(tmp4_reg_768) + unsigned(tmp3_fu_630_p2));
    tmp6_fu_668_p2 <= std_logic_vector(unsigned(tmp5_reg_778) + unsigned(tmp2_fu_664_p2));
    tmp7_fu_641_p2 <= std_logic_vector(unsigned(tmp_9_0_i_i_fu_513_p3) + unsigned(tmp_9_0_2_i_i_fu_547_p3));
    tmp8_fu_647_p2 <= std_logic_vector(unsigned(tmp_9_0_1_i_i_fu_530_p3) + unsigned(tmp_9_0_4_i_i_fu_581_p3));
    tmp9_fu_673_p2 <= std_logic_vector(unsigned(tmp8_reg_788) + unsigned(tmp7_reg_783));
    tmp_1_fu_301_p1 <= in_stream_V_data_V_0_data_out(8 - 1 downto 0);
    tmp_2_fu_322_p1 <= in_stream_V_data_V_0_data_out(8 - 1 downto 0);
    tmp_9_0_1_i_i_fu_530_p3 <= (sq_V_2_fu_524_p2 & ap_const_lv8_0);
    tmp_9_0_2_i_i_fu_547_p3 <= (sq_V_3_fu_541_p2 & ap_const_lv8_0);
    tmp_9_0_3_i_i_fu_564_p3 <= (sq_V_4_fu_558_p2 & ap_const_lv8_0);
    tmp_9_0_4_i_i_fu_581_p3 <= (sq_V_5_fu_575_p2 & ap_const_lv8_0);
    tmp_9_0_5_i_i_fu_315_p3 <= (sq_V_6_reg_738 & ap_const_lv8_0);
    tmp_9_0_6_i_i_fu_598_p3 <= (sq_V_7_fu_592_p2 & ap_const_lv8_0);
    tmp_9_0_7_i_i_fu_615_p3 <= (sq_V_8_fu_609_p2 & ap_const_lv8_0);
    tmp_9_0_i_i_fu_513_p3 <= (sq_V_1_fu_507_p2 & ap_const_lv8_0);
    tmp_9_1_1_i_i_fu_346_p3 <= (sq_V_10_fu_340_p2 & ap_const_lv8_0);
    tmp_9_1_2_i_i_fu_364_p3 <= (sq_V_11_fu_358_p2 & ap_const_lv8_0);
    tmp_9_1_3_i_i_fu_382_p3 <= (sq_V_12_fu_376_p2 & ap_const_lv8_0);
    tmp_9_1_4_i_i_fu_400_p3 <= (sq_V_13_fu_394_p2 & ap_const_lv8_0);
    tmp_9_1_5_i_i_fu_418_p3 <= (sq_V_14_fu_412_p2 & ap_const_lv8_0);
    tmp_9_1_6_i_i_fu_436_p3 <= (sq_V_15_fu_430_p2 & ap_const_lv8_0);
    tmp_9_1_7_i_i_fu_459_p3 <= (sq_V_16_fu_448_p2 & ap_const_lv8_0);
    tmp_9_1_i_i_fu_623_p3 <= (sq_V_9_reg_753 & ap_const_lv8_0);
    tmp_fu_467_p2 <= std_logic_vector(unsigned(tmp_9_1_5_i_i_fu_418_p3) + unsigned(tmp_9_1_6_i_i_fu_436_p3));
    tmp_i_i_fu_499_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(g_i_i_reg_203),64));
    tmp_s_fu_682_p2 <= std_logic_vector(unsigned(tmp13_fu_677_p2) + unsigned(tmp6_fu_668_p2));
    x_pack_V_address1 <= tmp_i_i_fu_499_p1(5 - 1 downto 0);

    x_pack_V_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_pack_V_ce1 <= ap_const_logic_1;
        else 
            x_pack_V_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    x_pack_V_d1 <= (in_stream_V_data_V_0_data_out & tmp_data_V_reg_708);

    x_pack_V_we1_assign_proc : process(exitcond1_i_i_reg_699, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond1_i_i_reg_699 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_pack_V_we1 <= ap_const_logic_1;
        else 
            x_pack_V_we1 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
