-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.2
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity load_data55 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    in_stream_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    in_stream_TVALID : IN STD_LOGIC;
    in_stream_TREADY : OUT STD_LOGIC;
    in_stream_TKEEP : IN STD_LOGIC_VECTOR (7 downto 0);
    in_stream_TSTRB : IN STD_LOGIC_VECTOR (7 downto 0);
    in_stream_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    in_stream_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    x_local_0_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    x_local_0_V_ce0 : OUT STD_LOGIC;
    x_local_0_V_we0 : OUT STD_LOGIC;
    x_local_0_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    x_local_1_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    x_local_1_V_ce0 : OUT STD_LOGIC;
    x_local_1_V_we0 : OUT STD_LOGIC;
    x_local_1_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    x_local_2_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    x_local_2_V_ce0 : OUT STD_LOGIC;
    x_local_2_V_we0 : OUT STD_LOGIC;
    x_local_2_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    x_local_3_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    x_local_3_V_ce0 : OUT STD_LOGIC;
    x_local_3_V_we0 : OUT STD_LOGIC;
    x_local_3_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    x_local_4_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    x_local_4_V_ce0 : OUT STD_LOGIC;
    x_local_4_V_we0 : OUT STD_LOGIC;
    x_local_4_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    x_local_5_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    x_local_5_V_ce0 : OUT STD_LOGIC;
    x_local_5_V_we0 : OUT STD_LOGIC;
    x_local_5_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    x_local_6_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    x_local_6_V_ce0 : OUT STD_LOGIC;
    x_local_6_V_we0 : OUT STD_LOGIC;
    x_local_6_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    x_local_7_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    x_local_7_V_ce0 : OUT STD_LOGIC;
    x_local_7_V_we0 : OUT STD_LOGIC;
    x_local_7_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    x_local_8_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    x_local_8_V_ce0 : OUT STD_LOGIC;
    x_local_8_V_we0 : OUT STD_LOGIC;
    x_local_8_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    x_local_9_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    x_local_9_V_ce0 : OUT STD_LOGIC;
    x_local_9_V_we0 : OUT STD_LOGIC;
    x_local_9_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    x_local_10_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    x_local_10_V_ce0 : OUT STD_LOGIC;
    x_local_10_V_we0 : OUT STD_LOGIC;
    x_local_10_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    x_local_11_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    x_local_11_V_ce0 : OUT STD_LOGIC;
    x_local_11_V_we0 : OUT STD_LOGIC;
    x_local_11_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    x_local_12_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    x_local_12_V_ce0 : OUT STD_LOGIC;
    x_local_12_V_we0 : OUT STD_LOGIC;
    x_local_12_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    x_local_13_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    x_local_13_V_ce0 : OUT STD_LOGIC;
    x_local_13_V_we0 : OUT STD_LOGIC;
    x_local_13_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    x_local_14_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    x_local_14_V_ce0 : OUT STD_LOGIC;
    x_local_14_V_we0 : OUT STD_LOGIC;
    x_local_14_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    x_local_15_V_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    x_local_15_V_ce0 : OUT STD_LOGIC;
    x_local_15_V_we0 : OUT STD_LOGIC;
    x_local_15_V_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    x_norm_in_V : IN STD_LOGIC_VECTOR (23 downto 0);
    x_norm_in_V_out_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    x_norm_in_V_out_full_n : IN STD_LOGIC;
    x_norm_in_V_out_write : OUT STD_LOGIC );
end;


architecture behav of load_data55 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_62 : STD_LOGIC_VECTOR (6 downto 0) := "1100010";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal in_stream_V_data_V_0_data_out : STD_LOGIC_VECTOR (63 downto 0);
    signal in_stream_V_data_V_0_vld_in : STD_LOGIC;
    signal in_stream_V_data_V_0_vld_out : STD_LOGIC;
    signal in_stream_V_data_V_0_ack_in : STD_LOGIC;
    signal in_stream_V_data_V_0_ack_out : STD_LOGIC;
    signal in_stream_V_data_V_0_payload_A : STD_LOGIC_VECTOR (63 downto 0);
    signal in_stream_V_data_V_0_payload_B : STD_LOGIC_VECTOR (63 downto 0);
    signal in_stream_V_data_V_0_sel_rd : STD_LOGIC := '0';
    signal in_stream_V_data_V_0_sel_wr : STD_LOGIC := '0';
    signal in_stream_V_data_V_0_sel : STD_LOGIC;
    signal in_stream_V_data_V_0_load_A : STD_LOGIC;
    signal in_stream_V_data_V_0_load_B : STD_LOGIC;
    signal in_stream_V_data_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal in_stream_V_data_V_0_state_cmp_full : STD_LOGIC;
    signal in_stream_V_dest_V_0_vld_in : STD_LOGIC;
    signal in_stream_V_dest_V_0_ack_out : STD_LOGIC;
    signal in_stream_V_dest_V_0_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal in_stream_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal x_norm_in_V_out_blk_n : STD_LOGIC;
    signal i_i_i_reg_368 : STD_LOGIC_VECTOR (6 downto 0);
    signal exitcond1_i_i_fu_379_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_fu_385_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal tmp_fu_391_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_527 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_cast_i_i_reg_531 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal newIndex1_i_i_fu_415_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_1_fu_409_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((not(((ap_start = ap_const_logic_0) or (x_norm_in_V_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif ((not(((ap_start = ap_const_logic_0) or (x_norm_in_V_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    in_stream_V_data_V_0_sel_rd_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                in_stream_V_data_V_0_sel_rd <= ap_const_logic_0;
            else
                if (((in_stream_V_data_V_0_ack_out = ap_const_logic_1) and (in_stream_V_data_V_0_vld_out = ap_const_logic_1))) then 
                                        in_stream_V_data_V_0_sel_rd <= not(in_stream_V_data_V_0_sel_rd);
                end if; 
            end if;
        end if;
    end process;


    in_stream_V_data_V_0_sel_wr_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                in_stream_V_data_V_0_sel_wr <= ap_const_logic_0;
            else
                if (((in_stream_V_data_V_0_ack_in = ap_const_logic_1) and (in_stream_V_data_V_0_vld_in = ap_const_logic_1))) then 
                                        in_stream_V_data_V_0_sel_wr <= not(in_stream_V_data_V_0_sel_wr);
                end if; 
            end if;
        end if;
    end process;


    in_stream_V_data_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                in_stream_V_data_V_0_state <= ap_const_lv2_0;
            else
                if ((((in_stream_V_data_V_0_state = ap_const_lv2_2) and (in_stream_V_data_V_0_vld_in = ap_const_logic_0)) or ((in_stream_V_data_V_0_state = ap_const_lv2_3) and (in_stream_V_data_V_0_vld_in = ap_const_logic_0) and (in_stream_V_data_V_0_ack_out = ap_const_logic_1)))) then 
                    in_stream_V_data_V_0_state <= ap_const_lv2_2;
                elsif ((((in_stream_V_data_V_0_state = ap_const_lv2_1) and (in_stream_V_data_V_0_ack_out = ap_const_logic_0)) or ((in_stream_V_data_V_0_state = ap_const_lv2_3) and (in_stream_V_data_V_0_ack_out = ap_const_logic_0) and (in_stream_V_data_V_0_vld_in = ap_const_logic_1)))) then 
                    in_stream_V_data_V_0_state <= ap_const_lv2_1;
                elsif (((not(((in_stream_V_data_V_0_vld_in = ap_const_logic_0) and (in_stream_V_data_V_0_ack_out = ap_const_logic_1))) and not(((in_stream_V_data_V_0_ack_out = ap_const_logic_0) and (in_stream_V_data_V_0_vld_in = ap_const_logic_1))) and (in_stream_V_data_V_0_state = ap_const_lv2_3)) or ((in_stream_V_data_V_0_state = ap_const_lv2_1) and (in_stream_V_data_V_0_ack_out = ap_const_logic_1)) or ((in_stream_V_data_V_0_state = ap_const_lv2_2) and (in_stream_V_data_V_0_vld_in = ap_const_logic_1)))) then 
                    in_stream_V_data_V_0_state <= ap_const_lv2_3;
                else 
                    in_stream_V_data_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    in_stream_V_dest_V_0_state_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                in_stream_V_dest_V_0_state <= ap_const_lv2_0;
            else
                if ((((in_stream_V_dest_V_0_state = ap_const_lv2_2) and (in_stream_V_dest_V_0_vld_in = ap_const_logic_0)) or ((in_stream_V_dest_V_0_state = ap_const_lv2_3) and (in_stream_V_dest_V_0_vld_in = ap_const_logic_0) and (in_stream_V_dest_V_0_ack_out = ap_const_logic_1)))) then 
                    in_stream_V_dest_V_0_state <= ap_const_lv2_2;
                elsif ((((in_stream_V_dest_V_0_state = ap_const_lv2_1) and (in_stream_V_dest_V_0_ack_out = ap_const_logic_0)) or ((in_stream_V_dest_V_0_state = ap_const_lv2_3) and (in_stream_V_dest_V_0_ack_out = ap_const_logic_0) and (in_stream_V_dest_V_0_vld_in = ap_const_logic_1)))) then 
                    in_stream_V_dest_V_0_state <= ap_const_lv2_1;
                elsif (((not(((in_stream_V_dest_V_0_vld_in = ap_const_logic_0) and (in_stream_V_dest_V_0_ack_out = ap_const_logic_1))) and not(((in_stream_V_dest_V_0_ack_out = ap_const_logic_0) and (in_stream_V_dest_V_0_vld_in = ap_const_logic_1))) and (in_stream_V_dest_V_0_state = ap_const_lv2_3)) or ((in_stream_V_dest_V_0_state = ap_const_lv2_1) and (in_stream_V_dest_V_0_ack_out = ap_const_logic_1)) or ((in_stream_V_dest_V_0_state = ap_const_lv2_2) and (in_stream_V_dest_V_0_vld_in = ap_const_logic_1)))) then 
                    in_stream_V_dest_V_0_state <= ap_const_lv2_3;
                else 
                    in_stream_V_dest_V_0_state <= ap_const_lv2_2;
                end if; 
            end if;
        end if;
    end process;


    i_i_i_reg_368_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond1_i_i_fu_379_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                i_i_i_reg_368 <= i_fu_385_p2;
            elsif ((not(((ap_start = ap_const_logic_0) or (x_norm_in_V_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_i_i_reg_368 <= ap_const_lv7_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((in_stream_V_data_V_0_load_A = ap_const_logic_1)) then
                in_stream_V_data_V_0_payload_A <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((in_stream_V_data_V_0_load_B = ap_const_logic_1)) then
                in_stream_V_data_V_0_payload_B <= in_stream_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond1_i_i_fu_379_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                tmp_2_cast_i_i_reg_531 <= i_i_i_reg_368(6 downto 1);
                tmp_reg_527 <= tmp_fu_391_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, x_norm_in_V_out_full_n, exitcond1_i_i_fu_379_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (x_norm_in_V_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (exitcond1_i_i_fu_379_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (exitcond1_i_i_fu_379_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state4 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(in_stream_V_data_V_0_vld_out, ap_enable_reg_pp0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= ((in_stream_V_data_V_0_vld_out = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(in_stream_V_data_V_0_vld_out, ap_enable_reg_pp0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= ((in_stream_V_data_V_0_vld_out = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, x_norm_in_V_out_full_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (x_norm_in_V_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter1_assign_proc : process(in_stream_V_data_V_0_vld_out)
    begin
                ap_block_state3_pp0_stage0_iter1 <= (in_stream_V_data_V_0_vld_out = ap_const_logic_0);
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(exitcond1_i_i_fu_379_p2)
    begin
        if ((exitcond1_i_i_fu_379_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    exitcond1_i_i_fu_379_p2 <= "1" when (i_i_i_reg_368 = ap_const_lv7_62) else "0";
    i_fu_385_p2 <= std_logic_vector(unsigned(i_i_i_reg_368) + unsigned(ap_const_lv7_1));

    in_stream_TDATA_blk_n_assign_proc : process(in_stream_V_data_V_0_state, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_TDATA_blk_n <= in_stream_V_data_V_0_state(0);
        else 
            in_stream_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    in_stream_TREADY <= in_stream_V_dest_V_0_state(1);
    in_stream_V_data_V_0_ack_in <= in_stream_V_data_V_0_state(1);

    in_stream_V_data_V_0_ack_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_V_data_V_0_ack_out <= ap_const_logic_1;
        else 
            in_stream_V_data_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;


    in_stream_V_data_V_0_data_out_assign_proc : process(in_stream_V_data_V_0_payload_A, in_stream_V_data_V_0_payload_B, in_stream_V_data_V_0_sel)
    begin
        if ((in_stream_V_data_V_0_sel = ap_const_logic_1)) then 
            in_stream_V_data_V_0_data_out <= in_stream_V_data_V_0_payload_B;
        else 
            in_stream_V_data_V_0_data_out <= in_stream_V_data_V_0_payload_A;
        end if; 
    end process;

    in_stream_V_data_V_0_load_A <= (in_stream_V_data_V_0_state_cmp_full and not(in_stream_V_data_V_0_sel_wr));
    in_stream_V_data_V_0_load_B <= (in_stream_V_data_V_0_state_cmp_full and in_stream_V_data_V_0_sel_wr);
    in_stream_V_data_V_0_sel <= in_stream_V_data_V_0_sel_rd;
    in_stream_V_data_V_0_state_cmp_full <= '0' when (in_stream_V_data_V_0_state = ap_const_lv2_1) else '1';
    in_stream_V_data_V_0_vld_in <= in_stream_TVALID;
    in_stream_V_data_V_0_vld_out <= in_stream_V_data_V_0_state(0);

    in_stream_V_dest_V_0_ack_out_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            in_stream_V_dest_V_0_ack_out <= ap_const_logic_1;
        else 
            in_stream_V_dest_V_0_ack_out <= ap_const_logic_0;
        end if; 
    end process;

    in_stream_V_dest_V_0_vld_in <= in_stream_TVALID;
    newIndex1_i_i_fu_415_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_cast_i_i_reg_531),64));
    tmp_1_fu_409_p1 <= in_stream_V_data_V_0_data_out(8 - 1 downto 0);
    tmp_fu_391_p1 <= i_i_i_reg_368(1 - 1 downto 0);
    x_local_0_V_address0 <= newIndex1_i_i_fu_415_p1(6 - 1 downto 0);

    x_local_0_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_0_V_ce0 <= ap_const_logic_1;
        else 
            x_local_0_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_0_V_d0 <= tmp_1_fu_409_p1;

    x_local_0_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, tmp_reg_527)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_527 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_0_V_we0 <= ap_const_logic_1;
        else 
            x_local_0_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_10_V_address0 <= newIndex1_i_i_fu_415_p1(6 - 1 downto 0);

    x_local_10_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_10_V_ce0 <= ap_const_logic_1;
        else 
            x_local_10_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_10_V_d0 <= in_stream_V_data_V_0_data_out(23 downto 16);

    x_local_10_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, tmp_reg_527)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_527 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_10_V_we0 <= ap_const_logic_1;
        else 
            x_local_10_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_11_V_address0 <= newIndex1_i_i_fu_415_p1(6 - 1 downto 0);

    x_local_11_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_11_V_ce0 <= ap_const_logic_1;
        else 
            x_local_11_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_11_V_d0 <= in_stream_V_data_V_0_data_out(31 downto 24);

    x_local_11_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, tmp_reg_527)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_527 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_11_V_we0 <= ap_const_logic_1;
        else 
            x_local_11_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_12_V_address0 <= newIndex1_i_i_fu_415_p1(6 - 1 downto 0);

    x_local_12_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_12_V_ce0 <= ap_const_logic_1;
        else 
            x_local_12_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_12_V_d0 <= in_stream_V_data_V_0_data_out(39 downto 32);

    x_local_12_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, tmp_reg_527)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_527 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_12_V_we0 <= ap_const_logic_1;
        else 
            x_local_12_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_13_V_address0 <= newIndex1_i_i_fu_415_p1(6 - 1 downto 0);

    x_local_13_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_13_V_ce0 <= ap_const_logic_1;
        else 
            x_local_13_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_13_V_d0 <= in_stream_V_data_V_0_data_out(47 downto 40);

    x_local_13_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, tmp_reg_527)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_527 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_13_V_we0 <= ap_const_logic_1;
        else 
            x_local_13_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_14_V_address0 <= newIndex1_i_i_fu_415_p1(6 - 1 downto 0);

    x_local_14_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_14_V_ce0 <= ap_const_logic_1;
        else 
            x_local_14_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_14_V_d0 <= in_stream_V_data_V_0_data_out(55 downto 48);

    x_local_14_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, tmp_reg_527)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_527 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_14_V_we0 <= ap_const_logic_1;
        else 
            x_local_14_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_15_V_address0 <= newIndex1_i_i_fu_415_p1(6 - 1 downto 0);

    x_local_15_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_15_V_ce0 <= ap_const_logic_1;
        else 
            x_local_15_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_15_V_d0 <= in_stream_V_data_V_0_data_out(63 downto 56);

    x_local_15_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, tmp_reg_527)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_527 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_15_V_we0 <= ap_const_logic_1;
        else 
            x_local_15_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_1_V_address0 <= newIndex1_i_i_fu_415_p1(6 - 1 downto 0);

    x_local_1_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_1_V_ce0 <= ap_const_logic_1;
        else 
            x_local_1_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_1_V_d0 <= in_stream_V_data_V_0_data_out(15 downto 8);

    x_local_1_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, tmp_reg_527)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_527 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_1_V_we0 <= ap_const_logic_1;
        else 
            x_local_1_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_2_V_address0 <= newIndex1_i_i_fu_415_p1(6 - 1 downto 0);

    x_local_2_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_2_V_ce0 <= ap_const_logic_1;
        else 
            x_local_2_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_2_V_d0 <= in_stream_V_data_V_0_data_out(23 downto 16);

    x_local_2_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, tmp_reg_527)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_527 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_2_V_we0 <= ap_const_logic_1;
        else 
            x_local_2_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_3_V_address0 <= newIndex1_i_i_fu_415_p1(6 - 1 downto 0);

    x_local_3_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_3_V_ce0 <= ap_const_logic_1;
        else 
            x_local_3_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_3_V_d0 <= in_stream_V_data_V_0_data_out(31 downto 24);

    x_local_3_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, tmp_reg_527)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_527 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_3_V_we0 <= ap_const_logic_1;
        else 
            x_local_3_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_4_V_address0 <= newIndex1_i_i_fu_415_p1(6 - 1 downto 0);

    x_local_4_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_4_V_ce0 <= ap_const_logic_1;
        else 
            x_local_4_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_4_V_d0 <= in_stream_V_data_V_0_data_out(39 downto 32);

    x_local_4_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, tmp_reg_527)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_527 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_4_V_we0 <= ap_const_logic_1;
        else 
            x_local_4_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_5_V_address0 <= newIndex1_i_i_fu_415_p1(6 - 1 downto 0);

    x_local_5_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_5_V_ce0 <= ap_const_logic_1;
        else 
            x_local_5_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_5_V_d0 <= in_stream_V_data_V_0_data_out(47 downto 40);

    x_local_5_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, tmp_reg_527)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_527 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_5_V_we0 <= ap_const_logic_1;
        else 
            x_local_5_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_6_V_address0 <= newIndex1_i_i_fu_415_p1(6 - 1 downto 0);

    x_local_6_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_6_V_ce0 <= ap_const_logic_1;
        else 
            x_local_6_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_6_V_d0 <= in_stream_V_data_V_0_data_out(55 downto 48);

    x_local_6_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, tmp_reg_527)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_527 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_6_V_we0 <= ap_const_logic_1;
        else 
            x_local_6_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_7_V_address0 <= newIndex1_i_i_fu_415_p1(6 - 1 downto 0);

    x_local_7_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_7_V_ce0 <= ap_const_logic_1;
        else 
            x_local_7_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_7_V_d0 <= in_stream_V_data_V_0_data_out(63 downto 56);

    x_local_7_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, tmp_reg_527)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_527 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_7_V_we0 <= ap_const_logic_1;
        else 
            x_local_7_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_8_V_address0 <= newIndex1_i_i_fu_415_p1(6 - 1 downto 0);

    x_local_8_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_8_V_ce0 <= ap_const_logic_1;
        else 
            x_local_8_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_8_V_d0 <= tmp_1_fu_409_p1;

    x_local_8_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, tmp_reg_527)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_527 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_8_V_we0 <= ap_const_logic_1;
        else 
            x_local_8_V_we0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_9_V_address0 <= newIndex1_i_i_fu_415_p1(6 - 1 downto 0);

    x_local_9_V_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_9_V_ce0 <= ap_const_logic_1;
        else 
            x_local_9_V_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    x_local_9_V_d0 <= in_stream_V_data_V_0_data_out(15 downto 8);

    x_local_9_V_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, tmp_reg_527)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (tmp_reg_527 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            x_local_9_V_we0 <= ap_const_logic_1;
        else 
            x_local_9_V_we0 <= ap_const_logic_0;
        end if; 
    end process;


    x_norm_in_V_out_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, x_norm_in_V_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            x_norm_in_V_out_blk_n <= x_norm_in_V_out_full_n;
        else 
            x_norm_in_V_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    x_norm_in_V_out_din <= x_norm_in_V;

    x_norm_in_V_out_write_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, x_norm_in_V_out_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (x_norm_in_V_out_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            x_norm_in_V_out_write <= ap_const_logic_1;
        else 
            x_norm_in_V_out_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
