// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __classify_alphas_V_H__
#define __classify_alphas_V_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct classify_alphas_V_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 8;
  static const unsigned AddressRange = 165;
  static const unsigned AddressWidth = 8;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(classify_alphas_V_ram) {
        ram[0] = "0b11111111";
        ram[1] = "0b00000000";
        ram[2] = "0b11111100";
        ram[3] = "0b11111111";
        ram[4] = "0b11111011";
        ram[5] = "0b11111101";
        ram[6] = "0b11110010";
        ram[7] = "0b11111111";
        ram[8] = "0b00000000";
        ram[9] = "0b11110010";
        ram[10] = "0b11111000";
        ram[11] = "0b11111001";
        ram[12] = "0b11111101";
        ram[13] = "0b11111111";
        ram[14] = "0b11111111";
        ram[15] = "0b11111001";
        ram[16] = "0b11000001";
        ram[17] = "0b11111101";
        ram[18] = "0b11111001";
        ram[19] = "0b11111111";
        ram[20] = "0b11111001";
        ram[21] = "0b11111111";
        ram[22] = "0b00000000";
        ram[23] = "0b11111111";
        ram[24] = "0b11111111";
        ram[25] = "0b11111011";
        ram[26] = "0b11111110";
        ram[27] = "0b11111111";
        ram[28] = "0b11111111";
        ram[29] = "0b11111010";
        ram[30] = "0b11111000";
        ram[31] = "0b11111110";
        ram[32] = "0b11010111";
        ram[33] = "0b11111101";
        ram[34] = "0b11111100";
        ram[35] = "0b11111110";
        ram[36] = "0b11111011";
        ram[37] = "0b11111100";
        ram[38] = "0b11111001";
        ram[39] = "0b11111100";
        ram[40] = "0b11111001";
        ram[41] = "0b11111100";
        ram[42] = "0b11111111";
        ram[43] = "0b11111010";
        ram[44] = "0b11111111";
        ram[45] = "0b11111110";
        ram[46] = "0b11111100";
        ram[47] = "0b11111001";
        ram[48] = "0b11111011";
        ram[49] = "0b11101110";
        ram[50] = "0b11111010";
        ram[51] = "0b11111011";
        ram[52] = "0b11111100";
        ram[53] = "0b11111110";
        ram[54] = "0b11111111";
        ram[55] = "0b00000000";
        ram[56] = "0b11111111";
        ram[57] = "0b11111010";
        ram[58] = "0b00000000";
        ram[59] = "0b11011000";
        ram[60] = "0b11111110";
        ram[61] = "0b11111111";
        ram[62] = "0b11111100";
        ram[63] = "0b11111001";
        ram[64] = "0b11111111";
        ram[65] = "0b11111110";
        ram[66] = "0b11111101";
        ram[67] = "0b11111000";
        ram[68] = "0b11111110";
        ram[69] = "0b11111011";
        ram[70] = "0b11111111";
        ram[71] = "0b11110100";
        ram[72] = "0b11111101";
        ram[73] = "0b11111011";
        ram[74] = "0b11111110";
        ram[75] = "0b11011110";
        ram[76] = "0b11111011";
        ram[77] = "0b00000000";
        ram[78] = "0b00000000";
        ram[79] = "0b00000000";
        ram[80] = "0b00000000";
        ram[81] = "0b11111100";
        ram[82] = "0b11111001";
        ram[83] = "0b10110101";
        ram[84] = "0b11111110";
        ram[85] = "0b11111111";
        ram[86] = "0b11110101";
        ram[87] = "0b11101010";
        ram[88] = "0b11110101";
        ram[89] = "0b11111110";
        ram[90] = "0b11111111";
        ram[91] = "0b00000000";
        ram[92] = "0b11110000";
        ram[93] = "0b11111110";
        ram[94] = "0b11111110";
        ram[95] = "0b11111101";
        ram[96] = "0b11111101";
        ram[97] = "0b11111110";
        ram[98] = "0b11111111";
        ram[99] = "0b11111101";
        ram[100] = "0b11111111";
        ram[101] = "0b00000000";
        ram[102] = "0b11111110";
        ram[103] = "0b00000111";
        ram[104] = "0b00001000";
        ram[105] = "0b00000011";
        ram[106] = "0b00000100";
        ram[107] = "0b00000011";
        ram[108] = "0b00001001";
        ram[109] = "0b00000111";
        ram[110] = "0b00010000";
        ram[111] = "0b00000000";
        ram[112] = "0b00000110";
        ram[113] = "0b00001111";
        ram[114] = "0b00011111";
        ram[115] = "0b01000100";
        ram[116] = "0b00000101";
        ram[117] = "0b00001010";
        ram[118] = "0b00000011";
        ram[119] = "0b00010101";
        ram[120] = "0b00000101";
        ram[121] = "0b00001100";
        ram[122] = "0b00000001";
        ram[123] = "0b00000111";
        ram[124] = "0b00001001";
        ram[125] = "0b00000011";
        ram[126] = "0b00000010";
        ram[127] = "0b00001001";
        ram[128] = "0b00001001";
        ram[129] = "0b00000111";
        ram[130] = "0b00011000";
        ram[131] = "0b00001110";
        ram[132] = "0b00010100";
        ram[133] = "0b00001000";
        ram[134] = "0b00001001";
        ram[135] = "0b00000110";
        ram[136] = "0b00001000";
        ram[137] = "0b00001001";
        ram[138] = "0b00010001";
        ram[139] = "0b00000100";
        ram[140] = "0b00001111";
        ram[141] = "0b00001110";
        ram[142] = "0b00010010";
        ram[143] = "0b00000001";
        ram[144] = "0b00001001";
        ram[145] = "0b00011100";
        ram[146] = "0b00000110";
        ram[147] = "0b00100000";
        ram[148] = "0b00000111";
        ram[149] = "0b00001001";
        ram[150] = "0b00001101";
        ram[151] = "0b00000011";
        ram[152] = "0b00000010";
        ram[153] = "0b00000111";
        ram[154] = "0b00000001";
        ram[155] = "0b00001100";
        ram[156] = "0b00000011";
        ram[157] = "0b00001100";
        ram[158] = "0b00000010";
        ram[159] = "0b00001001";
        ram[160] = "0b00001001";
        ram[161] = "0b00000101";
        ram[162] = "0b00001001";
        ram[163] = "0b00000100";
        ram[164] = "0b00001010";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(classify_alphas_V) {


static const unsigned DataWidth = 8;
static const unsigned AddressRange = 165;
static const unsigned AddressWidth = 8;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


classify_alphas_V_ram* meminst;


SC_CTOR(classify_alphas_V) {
meminst = new classify_alphas_V_ram("classify_alphas_V_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~classify_alphas_V() {
    delete meminst;
}


};//endmodule
#endif
